import {UI} from './ui.js';
import {constructionStats,roomAt,groupForNpc,territoryAt,MATERIAL} from '../systems/construction.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!UI.prototype.__phaseGUI){
 const baseInspect=UI.prototype.inspect,baseStats=UI.prototype.showStats,baseMenu=UI.prototype.showMenu;
 UI.prototype.inspect=function(i,open=true){baseInspect.call(this,i,open);const n=this.sim.npcs;if(!n.alive[i])return;const w=this.sim.world,r=roomAt(w,n.x[i],n.y[i]),group=groupForNpc(this.sim,i),territory=territoryAt(this.sim,n.x[i],n.y[i]),ownPieces=w.pieceStore?.filter(p=>p&&p.ownerUid===n.uid[i]&&p.durability>0).length||0,active=w.blueprints?.filter(bp=>!bp.done&&!bp.abandoned&&(bp.owner===n.uid[i]||bp.group===group)).length||0,body=document.querySelector('#panelBody');if(!body)return;body.insertAdjacentHTML('afterbegin',`<section class="section"><h3>Construção / território</h3><div class="memory">Grupo material: <b>${group}</b><br>Local: <b>${territory<0?'sem território':territory===group?'território próprio':`território do grupo ${territory}`}</b><br>Peças próprias: ${ownPieces} · projetos do grupo: ${active}<br>${r?`Cômodo fechado: ${r.area} tiles · cobertura ${Math.round(r.coverage*100)}% · vedação ${Math.round(r.seal*100)}%`:'Ao ar livre / região aberta'}</div></section>`)};
 UI.prototype.showStats=function(){baseStats.call(this);const c=constructionStats(this.sim),m=c.metrics,body=document.querySelector('#drawerBody');if(!body)return;const mats=Object.entries(c.materials).sort((a,b)=>b[1]-a[1]);body.insertAdjacentHTML('afterbegin',`<section class="section"><h3>Construção física</h3><div class="statGrid"><div class="statCard"><small>Peças</small><b>${c.pieces}</b>${c.blueprints} projetos</div><div class="statCard"><small>Cômodos</small><b>${c.rooms}</b>fechados</div><div class="statCard"><small>Territórios</small><b>${c.territories}</b>grupos</div><div class="statCard"><small>Manutenção</small><b>${m.repaired||0}</b>${m.collapsed||0} colapsos</div></div>${mats.map(([k,v])=>`<div class="score"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}<div class="metaLine">Roubo ${m.thefts||0} · dádiva ${m.gifts||0} · contatos de fronteira ${m.frontierContacts||0} · incêndios ${m.fires||0}</div></section>`)};
 UI.prototype.showMenu=function(){baseMenu.call(this);const body=document.querySelector('#drawerBody');if(!body)return;body.innerHTML=body.innerHTML.replace('v9 · Fase F','v10 · Fase G').replace('Sobrevivência profunda: comida perecível, temperatura corporal, roupa, ferimentos persistentes, cicatrizes, dieta e água transportável.','Construção física: obras peça por peça, cômodos, manutenção, propriedade, território e materiais arquitetônicos emergentes.')};
 Object.defineProperty(UI.prototype,'__phaseGUI',{value:true});
}
