import {NPC_STATE,RESOURCE,BUILDING} from '../core/constants.js';
import {techniqueName} from '../systems/technology.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installPhaseBUI(ui){
 const inspect=ui.inspect.bind(ui);
 ui.inspect=(i,open=true)=>{inspect(i,open);const n=ui.sim.npcs;if(!n.alive[i])return;const body=document.querySelector('#panelBody'),known=ui.sim.technology?.knownList(i)||[],uid=n.uid[i],owned=ui.sim.world.buildings.filter(b=>b.ownerUid===uid&&b.finished),territory=owned.length?`${owned.length} estrutura${owned.length===1?'':'s'} própria${owned.length===1?'':'s'}`:'sem território fixado',state=NPC_STATE.NAMES[n.state[i]]||'desconhecido',dest=n.intent[i]?`${n.taskTargetX[i].toFixed(1)}, ${n.taskTargetY[i].toFixed(1)}`:'—',remaining=n.intent[i]&&n.taskDuration[i]?Math.max(0,Math.ceil((1-n.taskProgress[i])*n.taskDuration[i])):0;const section=document.createElement('section');section.className='section';section.innerHTML=`<h3>Fase B · autonomia</h3><div class="memory"><b>${esc(state)}</b><br><small>destino ${esc(dest)} · ~${remaining} ticks restantes</small></div><div class="memory">${esc(territory)}</div><div class="metaLine">Técnicas conhecidas</div>${known.length?known.map(t=>`<span class="tag">${esc(techniqueName(t))}</span>`).join(''):'<span class="muted">Nenhuma. O conhecimento começa do zero.</span>'}`;body.prepend(section)};
 const stats=ui.showStats.bind(ui);ui.showStats=()=>{stats();const w=ui.sim.world,el=document.querySelector('#drawerBody'),box=document.createElement('section');box.className='section';box.innerHTML=`<h3>Mundo físico</h3><div class="score"><span>Seed</span><b>${ui.sim.seed}</b></div><div class="score"><span>Geração</span><b>${w.generationStats?.ms??0} ms</b></div><div class="score"><span>Água</span><b>${((w.generationStats?.waterFraction||0)*100).toFixed(1)}%</b></div><div class="score"><span>Sementes humanas</span><b>${w.spawnSeeds.length}</b></div><div class="score"><span>Transferências culturais</span><b>${ui.sim.technology?.crossGroupTransfers||0}</b></div>`;el.prepend(box)};
 const menu=ui.showMenu.bind(ui);ui.showMenu=()=>{menu();const body=document.querySelector('#drawerBody');body.innerHTML=body.innerHTML.replace(/<h3>v3<\/h3>/,'<h3>v5 · Fase B</h3>').replace(/Decisão esparsa[^<]*/,'Civilização em estado zero, geração física determinística, cultura emergente e território pessoal.')};
}
