import {NEED,GENE,SKILLS,RESOURCE} from '../core/constants.js';
import {traitNames} from '../genetics/genome.js';
import {naturalMemory,chronicleLabel} from '../narrative/templates.js';
const needNames=['fome','sede','sono','frio','insegurança','social','propósito'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class UI{
 constructor(sim,renderer,loop){this.sim=sim;this.renderer=renderer;this.loop=loop;this.selected=-1;this.bind()}
 bind(){document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active');this.loop.setSpeed(+b.dataset.speed)});document.querySelector('#panelClose').onclick=()=>document.querySelector('#sidePanel').classList.add('hidden');document.querySelector('#drawerClose').onclick=()=>this.closeDrawer();document.querySelector('#chronicleBtn').onclick=()=>this.showChronicle();document.querySelector('#statsBtn').onclick=()=>this.showStats();document.querySelector('#menuBtn').onclick=()=>this.showMenu()}
 update(){const m=this.sim.meta();document.querySelector('#worldMeta').textContent=`dia ${m.day} · ${m.phase} · ${m.season}`;this.updateCritical();if(this.selected>=0&&!document.querySelector('#sidePanel').classList.contains('hidden'))this.inspect(this.selected,false)}
 updateCritical(){const n=this.sim.npcs;const bad=[];for(const i of n.living()){const hits=[];for(let k=0;k<NEED.COUNT;k++)if(n.need(i,k)>.84)hits.push(needNames[k]);if(n.hp[i]<.35)hits.push('ferido');if(hits.length)bad.push(`<span class="criticalChip" data-npc="${i}">${esc(n.names[i].split(' ')[0])}: ${hits.join(', ')}</span>`)}const el=document.querySelector('#criticalStrip');el.innerHTML=bad.slice(0,6).join('');el.querySelectorAll('[data-npc]').forEach(x=>x.onclick=()=>this.inspect(+x.dataset.npc))}
 inspect(i,open=true){const n=this.sim.npcs;if(!n.alive[i])return;this.selected=i;this.renderer.selected=i;const rels=Array.from(this.sim.memory.relations.get(i)||[]).sort((a,b)=>Math.abs(b[1].affection)-Math.abs(a[1].affection)).slice(0,8);const mem=(this.sim.memory.episodic.get(i)||[]).slice().sort((a,b)=>(b.importance||0)-(a.importance||0)).slice(0,9);const beliefs=this.sim.memory.beliefs.get(i)||[];const skills=SKILLS.map((name,k)=>[name,n.skill(i,k)]).sort((a,b)=>b[1]-a[1]).slice(0,6);document.querySelector('#panelTitle').textContent=n.names[i];document.querySelector('#panelSubtitle').textContent=`${n.age[i].toFixed(1)} anos · ${n.professionName(i)} · prestígio ${n.prestige[i].toFixed(0)}`;document.querySelector('#panelBody').innerHTML=`
 <section class="section"><h3>Estado</h3>${needNames.map((x,k)=>bar(x,n.need(i,k),n.need(i,k)>.75?'#cf6b5e':'#88a46e')).join('')}${bar('vida',n.hp[i],'#b47768')}</section>
 <section class="section"><h3>Decisão atual</h3><div class="memory"><b>${esc(n.action[i])}</b><br><small>Plano: ${n.plan[i].map(esc).join(' → ')||'nenhum'}</small></div>${(n.scores[i]||[]).slice(0,3).map(s=>`<div class="score"><span>${esc(s[0])}</span><b>${s[1].toFixed(3)}</b></div>`).join('')}</section>
 <section class="section"><h3>Temperamento / genética</h3>${traitNames.map(([name,g])=>bar(name,n.gene(i,g),'#d2b36b')).join('')}</section>
 <section class="section"><h3>Skills</h3>${skills.map(([name,v])=>bar(name,v,'#7e98ad')).join('')}</section>
 <section class="section"><h3>Crenças</h3>${beliefs.length?beliefs.map(b=>`<span class="tag">${esc(b.text)}</span>`).join(''):'<span class="muted">Nenhuma crença consolidada.</span>'}</section>
 <section class="section"><h3>Memórias importantes</h3>${mem.length?mem.map(m=>`<div class="memory">${esc(naturalMemory(m))}<br><small>dia ${Math.floor(m.tick/240)+1} · importância ${Math.round((m.importance||.5)*100)}%</small></div>`).join(''):'<span class="muted">Ainda sem memórias marcantes.</span>'}</section>
 <section class="section"><h3>Relações</h3>${rels.length?rels.map(([j,r])=>`<div class="relation"><b>${esc(n.names[j])}</b><span>A ${fmt(r.affection)}</span><span>C ${fmt(r.trust)}</span><span>M ${fmt(r.fear)}</span></div>`).join(''):'<span class="muted">Sem vínculos registrados.</span>'}</section>
 <section class="section"><h3>Linhagem</h3><div class="memory">Pais: ${n.parents[i].filter(x=>x>=0).map(x=>esc(n.names[x])).join(' + ')||'fundador'}<br>Filhos: ${n.children[i].map(x=>esc(n.names[x])).join(', ')||'nenhum'}</div></section>`;if(open)document.querySelector('#sidePanel').classList.remove('hidden')}
 showChronicle(){this.openDrawer('Crônica');const a=this.sim.chronicle.slice().reverse();document.querySelector('#drawerBody').innerHTML=a.length?a.map(e=>`<div class="event ${e.importance>.8?'important':''}"><time>D${e.day}</time><div><b>${esc(chronicleLabel(e.type))}</b><br>${esc(e.text)}</div></div>`).join(''):'<div class="muted">O mundo ainda está silencioso.</div>'}
 showStats(){this.openDrawer('Mundo');const s=this.sim,w=s.world,n=s.npcs,alive=n.living();const deaths=n.deathCause.filter(Boolean).length;const genes=[['agressividade',GENE.AGGRESSION],['cautela',GENE.CAUTION],['ambição',GENE.AMBITION],['empatia',GENE.EMPATHY]];const avg=g=>alive.length?alive.reduce((a,i)=>a+n.gene(i,g),0)/alive.length:0;document.querySelector('#drawerBody').innerHTML=`<div class="statGrid"><div class="statCard"><small>População</small><b>${alive.length}</b>vivos · ${deaths} mortos</div><div class="statCard"><small>Dungeon</small><b>${s.dungeon.deepest}/10</b>${s.dungeon.boss.alive?'chefe vivo':'chefe morto'}</div><div class="statCard"><small>Estruturas</small><b>${w.buildings.length}</b>na vila</div><div class="statCard"><small>Ameaça</small><b>${Math.round(s.dungeon.pressure*100)}%</b>${w.monsters.filter(m=>m.hp>0).length} monstros</div></div><section class="section"><h3>Estoque comunitário</h3>${RESOURCE.NAMES.map((x,k)=>bar(x,Math.min(1,w.stock[k]/80),'#9eaa73',w.stock[k].toFixed(1))).join('')}</section><section class="section"><h3>Média genética atual</h3>${genes.map(([x,g])=>bar(x,avg(g),'#d2b36b')).join('')}</section><section class="section"><h3>População ao longo do tempo</h3>${sparkline(s.populationHistory.map(x=>x.value))}</section>`}
 showGenealogy(){this.openDrawer('Linhagens');const n=this.sim.npcs;const founders=[...Array(n.count).keys()].filter(i=>n.parents[i][0]<0);document.querySelector('#drawerBody').innerHTML=founders.map(i=>tree(n,i,0)).join('')}
 showMenu(){this.openDrawer('Observatório');document.querySelector('#drawerBody').innerHTML=`<div class="section"><button id="mChron">Crônica</button> <button id="mStats">Mundo</button> <button id="mGene">Linhagens</button></div><div class="section"><h3>Princípio</h3><p class="muted">Você não dá ordens. Use estes painéis apenas para investigar o que a simulação fez sozinha.</p></div><div class="section"><button id="mSave">Salvar agora</button> <button id="mReload">Recarregar mundo</button></div>`;document.querySelector('#mChron').onclick=()=>this.showChronicle();document.querySelector('#mStats').onclick=()=>this.showStats();document.querySelector('#mGene').onclick=()=>this.showGenealogy();document.querySelector('#mSave').onclick=()=>dispatchEvent(new Event('agents-save'));document.querySelector('#mReload').onclick=()=>location.reload()}
 openDrawer(title){document.querySelector('#drawerTitle').textContent=title;document.querySelector('#drawer').classList.remove('hidden');document.querySelector('#sidePanel').classList.add('hidden')}
 closeDrawer(){document.querySelector('#drawer').classList.add('hidden')}
 toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1800)}
}
function bar(name,v,color,label=null){return`<div class="barRow"><span>${esc(name)}</span><div class="bar" style="color:${color}"><i style="width:${Math.round(Math.max(0,Math.min(1,v))*100)}%"></i></div><b>${label??Math.round(v*100)}</b></div>`}function fmt(v){return(v??0).toFixed(1)}
function sparkline(vals){if(vals.length<2)return'<div class="muted">Dados aparecem após alguns dias.</div>';const w=420,h=90,max=Math.max(...vals,1),min=Math.min(...vals);const pts=vals.map((v,i)=>`${i/(vals.length-1)*w},${h-(v-min)/(max-min||1)*(h-10)-5}`).join(' ');return`<svg class="miniChart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`}
function tree(n,i,depth){if(depth>5)return'';const dead=!n.alive[i];return`<div class="memory" style="padding-left:${depth*12}px"><b>${dead?'† ':''}${esc(n.names[i])}</b> · ${n.professionName(i)}${dead?` · ${esc(n.deathCause[i])}`:''}</div>${n.children[i].map(c=>tree(n,c,depth+1)).join('')}`}
