import {RESOURCE,GENE,DAY_TICKS,BUILDING} from '../core/constants.js';
import {isDusk,isDawn,isNight} from '../core/clock.js';
import {knownDungeons} from '../ai/perception.js';
import {BALANCE} from '../calibration/balance.js';
export class Dungeon{
 constructor(rng,world){this.bossSite=rng.int(0,world.dungeons.length-1);this.sites=world.dungeons.map((d,id)=>{const floors=2+rng.int(0,2);return{id,x:d.x,y:d.y,discovered:false,pressure:.08+rng.range(0,.12)+(id===this.bossSite?.18:0),floors:Array.from({length:floors},(_,f)=>({id:f,rooms:Array.from({length:4+rng.int(0,2)},(_,r)=>({id:r,danger:.24+f*.13+r*.035+rng.range(-.025,.025),cleared:false,loot:.5+rng.range(0,1)}))})),floor:0,room:0,cleared:false,raids:0,evidence:0,bossWarning:false}});this.boss={name:'Coração da Escuridão',hp:1,power:.88,alive:true};this.victoryTick=0}
 tick(sim){
  for(const s of this.sites)if(!s.cleared)s.pressure=Math.min(1,s.pressure+.000018*(s.id===this.bossSite?1.5:1));
  if(isDusk(sim.tick))for(const s of this.sites){if(s.cleared)continue;const chance=.12+s.pressure*.22+(s.id===this.bossSite?.16:0);if(sim.rng.chance(chance)){const count=1+Math.floor(s.pressure*2)+(s.id===this.bossSite&&sim.rng.chance(.35)?1:0);for(let k=0;k<count;k++)sim.world.monsters.push({id:`m${sim.tick}-${s.id}-${k}`,origin:s.id,x:s.x+sim.rng.range(-1.4,1.4),y:s.y+sim.rng.range(-1.4,1.4),hp:.28+s.pressure*.22+(s.id===this.bossSite?.08:0),power:.16+s.pressure*.2+(s.id===this.bossSite?.08:0),born:sim.tick});s.raids++;s.pressure=Math.min(1,s.pressure+.025)}}
  if(isNight(sim.tick))this.attractToFire(sim);
  if(isDawn(sim.tick))for(const m of sim.world.monsters)if(m.hp>0){const s=this.sites[m.origin];if(s){const d=Math.hypot(s.x-m.x,s.y-m.y);if(d>1){m.x+=(s.x-m.x)/(d||1)*.45;m.y+=(s.y-m.y)/(d||1)*.45}m.hp-=.035}}
  sim.world.monsters=sim.world.monsters.filter(m=>m.hp>0&&sim.tick-m.born<DAY_TICKS*4)
 }
 attractToFire(sim){const fires=sim.world.buildings.filter(b=>b.finished&&b.type===BUILDING.CAMPFIRE&&b.lit);if(!fires.length)return;for(const m of sim.world.monsters)if(m.hp>0){let best=null,bd=30;for(const f of fires){const d=Math.hypot(f.x-m.x,f.y-m.y);if(d<bd){bd=d;best=f}}if(best&&bd>.9){const pull=.018+Math.min(.022,(30-bd)*.001);m.x+=(best.x-m.x)/(bd||1)*pull;m.y+=(best.y-m.y)/(bd||1)*pull}}}
 pressureForKnown(sim,i){const known=knownDungeons(sim,i);let best=0;for(const k of known){const site=this.sites.find(s=>Math.hypot(s.x-k.x,s.y-k.y)<2);if(site)best=Math.max(best,site.pressure+site.evidence*.08)}return best}
 nearestKnownSite(sim,i){const ks=knownDungeons(sim,i);for(const k of ks){const s=this.sites.find(x=>Math.hypot(x.x-k.x,x.y-k.y)<2&&!x.cleared);if(s)return s}return null}
 currentRoom(site){const f=site.floors[site.floor];return f?.rooms[site.room]||null}
 attempt(sim,i,siteId){const site=this.sites[siteId];if(!site||site.cleared)return{done:true};const n=sim.npcs,allies=[];for(const j of n.living())if(j!==i&&n.age[j]>=16&&Math.hypot(n.x[j]-n.x[i],n.y[j]-n.y[i])<5){const r=sim.memory.relation(j,i),accept=n.skill(j,10)*.42+n.gene(j,GENE.AMBITION)*.22+(r.affection+r.trust)*.1+n.prestige[i]*.0015-n.gene(j,GENE.CAUTION)*.22;if(accept>.15&&allies.length<4)allies.push(j)}const power=k=>n.skill(k,10)*.48+n.derived(k).strength*.28+n.gene(k,GENE.AGGRESSION)*.1+(n.tool[k]===7?.14:0)+(n.armor[k]||0)*.05;const party=[i,...allies],strength=power(i)+allies.reduce((s,j)=>s+power(j)*.55,0)+sim.rng.range(-.08,.08);for(const j of allies)n.action[j]=`expedição com ${n.names[i]}`;const room=this.currentRoom(site);if(room){if(strength>room.danger){room.cleared=true;site.room++;if(site.room>=site.floors[site.floor].rooms.length){site.floor++;site.room=0}for(const j of party){n.prestige[j]+=1.5+site.floor;n.addSkill(j,10,.006);sim.world.stock[RESOURCE.IRON]+=room.loot/party.length;sim.memory.remember(j,{type:'dungeon',text:`Nossa expedição avançou na dungeon ${site.id+1}.`,tick:sim.tick,valence:3,importance:.72,reflectionKey:`dungeon:${site.id}`})}if(site.id===this.bossSite){site.evidence=Math.min(1,site.evidence+.16);for(const j of party)sim.memory.remember(j,{type:'indício',text:'Esta dungeon exala uma presença incomum; talvez a fonte da escuridão esteja mais fundo.',tick:sim.tick,valence:-2,importance:.9,reflectionKey:`dungeon:${site.id}`})}sim.log('dungeon',`${n.names[i]} liderou uma expedição que avançou na dungeon ${site.id+1}.`,.82,i);site.pressure=Math.max(.05,site.pressure-.025)}else{for(const j of party){n.wound[j]=Math.min(1,n.wound[j]+.07+room.danger*.05);n.hp[j]-=.025+room.danger*.025;sim.memory.remember(j,{type:'dungeon',text:`Fomos repelidos na dungeon ${site.id+1}.`,tick:sim.tick,valence:-7,importance:.86,reflectionKey:`dungeon:${site.id}`})}site.pressure=Math.min(1,site.pressure+.04)}return{done:true}}
  if(site.floor>=site.floors.length){if(site.id!==this.bossSite){site.cleared=true;sim.log('dungeon',`A dungeon ${site.id+1} foi esvaziada, mas não continha o chefe.`,.92,i);for(const j of party)sim.memory.remember(j,{type:'revelação',text:'Exploramos esta dungeon até o fim: o chefe não está aqui.',tick:sim.tick,valence:1,importance:1,reflectionKey:`dungeon:${site.id}`});return{done:true}}if(this.boss.alive){if(sim.tick<BALANCE.bossUnlockDay*DAY_TICKS){site.evidence=1;if(!site.bossWarning){site.bossWarning=true;sim.log('presságio',`Uma expedição alcançou o ${this.boss.name}, mas ainda não tem preparo para enfrentá-lo.`,.94,i)}for(const j of party)sim.memory.remember(j,{type:'presságio',text:`Chegamos ao ${this.boss.name}, mas recuamos: ainda não estamos preparados.`,tick:sim.tick,valence:-4,importance:.92,reflectionKey:`dungeon:${site.id}`});return{done:true}}if(strength>.72){this.boss.hp-=.055+party.length*.018;for(const j of party){n.addSkill(j,10,.009);n.prestige[j]+=2}if(this.boss.hp<=0){this.boss.alive=false;site.cleared=true;this.victoryTick=sim.tick;for(const j of party)n.prestige[j]+=40;sim.log('vitória',`${n.names[i]} e ${party.length-1} companheiro${party.length===2?'':'s'} destruíram o ${this.boss.name}.`,1,i)}}else for(const j of party){n.wound[j]=Math.min(1,n.wound[j]+.13);n.hp[j]-=.05;sim.memory.remember(j,{type:'dungeon',text:`O ${this.boss.name} esmagou nossa expedição.`,tick:sim.tick,valence:-10,importance:1,reflectionKey:`dungeon:${site.id}`})}}return{done:true}}return{done:true}}
 serialize(){return{bossSite:this.bossSite,sites:this.sites,boss:this.boss,victoryTick:this.victoryTick}}
 static hydrate(d,rng,world){if(!d?.sites)return new Dungeon(rng,world);const x=Object.create(Dungeon.prototype);x.bossSite=d.bossSite??0;x.sites=d.sites;x.boss=d.boss||{name:'Coração da Escuridão',hp:1,power:.88,alive:true};x.victoryTick=d.victoryTick||0;for(const s of x.sites)if(s.bossWarning==null)s.bossWarning=false;return x}
}
