import {GENE,RESOURCE} from '../core/constants.js';
export class Dungeon{
 constructor(rng){this.floors=[{id:0,rooms:Array.from({length:10},(_,i)=>({id:i,danger:.19+i*.032,cleared:false,loot:1.4+i*.45}))}];this.boss={name:'Guardião do Poço',hp:1,power:.72,alive:true};this.pressure=.08;this.raids=0;this.deepest=0}
 get rooms(){return this.floors[0].rooms}
 readiness(sim,i){const n=sim.npcs;return Math.min(1,.25+n.skill(i,10)*.42+n.hp[i]*.2+n.stamina[i]*.1+n.weapon[i]*.18+(n.inventory[i][RESOURCE.FOOD]>.15?.06:0)+(n.inventory[i][RESOURCE.WATER]>.15?.08:0))}
 tick(sim){if(!this.boss.alive){this.pressure=0;return}this.pressure=Math.min(1,this.pressure+.00012);if(sim.tick%960===0&&sim.rng.chance(.28+this.pressure*.22)){const count=1+Math.floor(this.pressure*3);for(let k=0;k<count;k++)sim.world.monsters.push({x:sim.world.dungeon.x+sim.rng.range(-2,2),y:sim.world.dungeon.y+sim.rng.range(-2,2),hp:.30+this.pressure*.15,power:.14+this.pressure*.18,born:sim.tick});this.raids++;sim.log('ameaça',`${count} criatura${count>1?'s':''} emergiu da dungeon.`,.9);this.pressure=Math.min(1,this.pressure+.08)}}
 attempt(sim,i){const n=sim.npcs,inv=n.inventory[i],w=sim.world;
  if(inv[RESOURCE.FOOD]<.16||inv[RESOURCE.WATER]<.16){const store=w.nearestBuilding(n.x[i],n.y[i],3);if(!store)return 'blocked';const d=Math.hypot(store.x-n.x[i],store.y-n.y[i]);if(d>.6){n.x[i]+=(store.x-n.x[i])/d*.34;n.y[i]+=(store.y-n.y[i])/d*.34;return 'in-progress'}if(inv[RESOURCE.FOOD]<.16&&w.stock[RESOURCE.FOOD]>.25){const q=Math.min(.28,w.stock[RESOURCE.FOOD]);w.stock[RESOURCE.FOOD]-=q;inv[RESOURCE.FOOD]+=q}if(inv[RESOURCE.WATER]<.16&&w.stock[RESOURCE.WATER]>.25){const q=Math.min(.32,w.stock[RESOURCE.WATER]);w.stock[RESOURCE.WATER]-=q;inv[RESOURCE.WATER]+=q}if(inv[RESOURCE.FOOD]<.16||inv[RESOURCE.WATER]<.16)return 'blocked'}
  if(Math.hypot(n.x[i]-w.dungeon.x,n.y[i]-w.dungeon.y)>1.2){const dx=w.dungeon.x-n.x[i],dy=w.dungeon.y-n.y[i],d=Math.hypot(dx,dy);n.x[i]+=dx/d*.34;n.y[i]+=dy/d*.34;return 'in-progress'}
 const allies=[];for(const j of n.living())if(j!==i&&n.age[j]>=16&&Math.hypot(n.x[j]-n.x[i],n.y[j]-n.y[i])<10){const r=sim.memory.relation(j,i),accept=n.skill(j,10)*.42+n.gene(j,GENE.AMBITION)*.25+(r.affection+r.trust)*.12+n.prestige[i]*.002+n.weapon[j]*.12-n.gene(j,GENE.CAUTION)*.26;if(accept>.13&&allies.length<4)allies.push(j)}
 const personal=k=>n.skill(k,10)*.48+n.derived(k).strength*.28+n.gene(k,GENE.AGGRESSION)*.13+n.weapon[k]*.18;let power=personal(i)+allies.reduce((sum,j)=>sum+personal(j)*.58,0)+sim.rng.range(-.08,.08);for(const j of allies)n.action[j]=`expedição com ${n.names[i]}`;
 const room=this.rooms.find(r=>!r.cleared);if(room){const party=[i,...allies];if(power>room.danger){room.cleared=true;this.deepest=Math.max(this.deepest,room.id+1);for(const j of party){n.prestige[j]+=3+room.id*.6;n.inventory[j][RESOURCE.IRON]+=room.loot/party.length;n.addSkill(j,10,.015);sim.memory.remember(j,{type:'dungeon',text:`Sobrevivi à sala ${room.id+1} da dungeon com ${party.length} aventureiro${party.length>1?'s':''}.`,tick:sim.tick,valence:5,importance:.9,reflectionKey:'dungeon'})}sim.log('dungeon',`${n.names[i]} liderou ${party.length>1?`um grupo de ${party.length}`:'uma incursão solitária'} e venceu a sala ${room.id+1}.`,.95,i);this.pressure=Math.max(.08,this.pressure-.07)}else for(const j of party){n.hp[j]-=.025+room.danger*.035;sim.memory.remember(j,{type:'dungeon',text:`A sala ${room.id+1} quase matou nosso grupo.`,tick:sim.tick,valence:-8,importance:1,reflectionKey:'dungeon'})}for(const j of party){n.x[j]=sim.world.dungeon.x-2+sim.rng.range(-1,1);n.y[j]=sim.world.dungeon.y+2+sim.rng.range(-1,1)}return 'complete'}
 if(this.boss.alive){const party=[i,...allies];if(power>.54){this.boss.hp-=.11+party.length*.035;for(const j of party){n.addSkill(j,10,.02);n.prestige[j]+=2}if(this.boss.hp<=0){this.boss.alive=false;this.pressure=0;for(const j of party)n.prestige[j]+=35;sim.log('vitória',`${n.names[i]} e ${party.length-1} companheiro${party.length===2?'':'s'} mataram o ${this.boss.name}. A escuridão ficou silenciosa.`,1,i)}}else for(const j of party){n.hp[j]-=.065;sim.memory.remember(j,{type:'dungeon',text:`O ${this.boss.name} derrotou nossa expedição.`,tick:sim.tick,valence:-10,importance:1,reflectionKey:'dungeon'})}return 'complete'}
  return 'complete'
 }
 serialize(){return{floors:this.floors,boss:this.boss,pressure:this.pressure,raids:this.raids,deepest:this.deepest}}
 static hydrate(d,rng){const x=new Dungeon(rng);if(d.floors)x.floors=d.floors;else if(d.rooms)x.floors=[{id:0,rooms:d.rooms}];x.boss=d.boss||x.boss;x.pressure=d.pressure??x.pressure;x.raids=d.raids||0;x.deepest=d.deepest||0;return x}
}
