import {GENE,RESOURCE} from '../core/constants.js';
export class Dungeon{
 constructor(rng){this.rooms=Array.from({length:10},(_,i)=>({id:i,danger:.22+i*.04,cleared:false,loot:2+i*.7}));this.boss={name:'Guardião do Poço',hp:1,power:.72,alive:true};this.pressure=.08;this.raids=0;this.deepest=0}
 readiness(sim,i){const n=sim.npcs;return Math.min(1,.25+n.skill(i,10)*.45+n.hp[i]*.2+n.stamina[i]*.1+(n.inventory[i][RESOURCE.FOOD]>.15?.1:0))}
 tick(sim){this.pressure=Math.min(1,this.pressure+.00012);if(sim.tick%960===0&&sim.rng.chance(.28+this.pressure*.22)){const count=1+Math.floor(this.pressure*3);for(let k=0;k<count;k++)sim.world.monsters.push({x:sim.world.dungeon.x+sim.rng.range(-2,2),y:sim.world.dungeon.y+sim.rng.range(-2,2),hp:.30+this.pressure*.15,power:.14+this.pressure*.18,born:sim.tick});this.raids++;sim.log('ameaça',`${count} criatura${count>1?'s':''} emergiu da dungeon.`,.9);this.pressure=Math.min(1,this.pressure+.08)}}
 attempt(sim,i){const n=sim.npcs;if(Math.hypot(n.x[i]-sim.world.dungeon.x,n.y[i]-sim.world.dungeon.y)>1.2){const dx=sim.world.dungeon.x-n.x[i],dy=sim.world.dungeon.y-n.y[i],d=Math.hypot(dx,dy);n.x[i]+=dx/d*.34;n.y[i]+=dy/d*.34;return}
 const allies=[];for(const j of n.living())if(j!==i&&n.age[j]>=16&&Math.hypot(n.x[j]-n.x[i],n.y[j]-n.y[i])<10){const r=sim.memory.relation(j,i),accept=n.skill(j,10)*.45+n.gene(j,GENE.AMBITION)*.25+(r.affection+r.trust)*.12+n.prestige[i]*.002-n.gene(j,GENE.CAUTION)*.28;if(accept>.16&&allies.length<4)allies.push(j)}
 const personal=k=>n.skill(k,10)*.5+n.derived(k).strength*.3+n.gene(k,GENE.AGGRESSION)*.15;let power=personal(i)+allies.reduce((sum,j)=>sum+personal(j)*.55,0)+sim.rng.range(-.1,.1);for(const j of allies)n.action[j]=`expedição com ${n.names[i]}`;
 const room=this.rooms.find(r=>!r.cleared);if(room){if(power>room.danger){room.cleared=true;this.deepest=Math.max(this.deepest,room.id+1);const party=[i,...allies];for(const j of party){n.prestige[j]+=3+room.id*.6;n.inventory[j][RESOURCE.IRON]+=room.loot/party.length;n.addSkill(j,10,.015);sim.memory.remember(j,{type:'dungeon',text:`Sobrevivi à sala ${room.id+1} da dungeon com ${party.length} aventureiro${party.length>1?'s':''}.`,tick:sim.tick,valence:5,importance:.9,reflectionKey:'dungeon'})}sim.log('dungeon',`${n.names[i]} liderou ${party.length>1?`um grupo de ${party.length}`:'uma incursão solitária'} e venceu a sala ${room.id+1}.`,.95,i);this.pressure=Math.max(.08,this.pressure-.08);for(const j of party){n.x[j]=sim.world.dungeon.x-2+sim.rng.range(-1,1);n.y[j]=sim.world.dungeon.y+2+sim.rng.range(-1,1)}}else{const party=[i,...allies];for(const j of party){n.hp[j]-=.06+room.danger*.07;sim.memory.remember(j,{type:'dungeon',text:`A sala ${room.id+1} quase matou nosso grupo.`,tick:sim.tick,valence:-8,importance:1,reflectionKey:'dungeon'});n.x[j]=sim.world.dungeon.x-3+sim.rng.range(-1,1);n.y[j]=sim.world.dungeon.y+3+sim.rng.range(-1,1)}}return}
 if(this.boss.alive){const party=[i,...allies];if(power>.58){this.boss.hp-=.12+party.length*.035;for(const j of party){n.addSkill(j,10,.02);n.prestige[j]+=2}if(this.boss.hp<=0){this.boss.alive=false;this.pressure=0;for(const j of party)n.prestige[j]+=35;sim.log('vitória',`${n.names[i]} e ${party.length-1} companheiro${party.length===2?'':'s'} mataram o ${this.boss.name}. A escuridão ficou silenciosa.`,1,i)}}else{for(const j of party){n.hp[j]-=.12;sim.memory.remember(j,{type:'dungeon',text:`O ${this.boss.name} derrotou nossa expedição.`,tick:sim.tick,valence:-10,importance:1,reflectionKey:'dungeon'})}}}
 }
 serialize(){return{rooms:this.rooms,boss:this.boss,pressure:this.pressure,raids:this.raids,deepest:this.deepest}}
 static hydrate(d,rng){const x=new Dungeon(rng);Object.assign(x,d);return x}
}
