import {MAP_W,MAP_H,TILE,TILE_TYPE,BUILDING,RESOURCE,GENE} from '../core/constants.js';
export class Renderer{
 constructor(canvas,sim,onPick){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.sim=sim;this.onPick=onPick;this.camera={x:36,y:36,zoom:2};this.drag=null;this.pinch=0;this.selected=-1;this.atlas=this.makeAtlas();this.terrain=this.makeTerrain();this.resize();addEventListener('resize',()=>this.resize());this.bind()}
 resize(){const dpr=Math.min(2,devicePixelRatio||1),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.floor(r.width*dpr);this.canvas.height=Math.floor(r.height*dpr);this.dpr=dpr;this.ctx.imageSmoothingEnabled=false}
 makeTerrain(){const c=document.createElement('canvas');c.width=MAP_W*TILE;c.height=MAP_H*TILE;const x=c.getContext('2d');x.imageSmoothingEnabled=false;for(let y=0;y<MAP_H;y++)for(let xx=0;xx<MAP_W;xx++){const t=this.sim.world.tile(xx,y),px=xx*TILE,py=y*TILE;const base=t===TILE_TYPE.WATER?'#294e55':t===TILE_TYPE.FOREST?'#243d28':t===TILE_TYPE.STONE?'#4a4b43':t===TILE_TYPE.ROAD?'#705b3b':t===TILE_TYPE.DUNGEON?'#2a1e29':'#405d36';x.fillStyle=base;x.fillRect(px,py,TILE,TILE);if(t===TILE_TYPE.GRASS&&((xx*13+y*7)%9===0)){x.fillStyle='#547247';x.fillRect(px+3,py+5,2,3)}if(t===TILE_TYPE.WATER){x.fillStyle='#3a6670';x.fillRect(px+2+(y%2)*4,py+5,8,1)}if(t===TILE_TYPE.STONE){x.fillStyle='#62635a';x.fillRect(px+4,py+3,7,6)}if(t===TILE_TYPE.FOREST){x.fillStyle='#315337';x.fillRect(px+3,py+2,10,10);x.fillStyle='#33291e';x.fillRect(px+7,py+10,2,5)}if(t===TILE_TYPE.DUNGEON){x.fillStyle='#111';x.fillRect(px+3,py+4,10,10);x.fillStyle='#735363';x.fillRect(px+5,py+2,6,3)}}return c}
 makeAtlas(){const c=document.createElement('canvas');c.width=96;c.height=32;const x=c.getContext('2d');x.imageSmoothingEnabled=false;for(let k=0;k<6;k++){const ox=k*16;x.fillStyle=['#d1b58c','#c89f78','#9e795d','#725342','#b87c5e','#8f684e'][k];x.fillRect(ox+5,3,6,6);x.fillStyle=['#543c25','#2f241f','#b58a4c','#1d1b18'][k%4];x.fillRect(ox+4,2,8,3);x.fillStyle=['#6c7f53','#75615c','#4d647e','#7c5946','#68666d','#776c3e'][k];x.fillRect(ox+4,9,8,8);x.fillStyle='#292722';x.fillRect(ox+4,17,3,6);x.fillRect(ox+9,17,3,6);x.fillStyle='#1b1815';x.fillRect(ox+4,23,4,2);x.fillRect(ox+9,23,4,2)}return c}
 screen(wx,wy){const z=this.camera.zoom*TILE,sw=this.canvas.width/this.dpr,sh=this.canvas.height/this.dpr;return{x:(wx-this.camera.x)*z+sw/2,y:(wy-this.camera.y)*z+sh/2,z}}
 world(sx,sy){const z=this.camera.zoom*TILE,sw=this.canvas.width/this.dpr,sh=this.canvas.height/this.dpr;return{x:(sx-sw/2)/z+this.camera.x,y:(sy-sh/2)/z+this.camera.y}}
 render(){const ctx=this.ctx,d=this.dpr;ctx.setTransform(d,0,0,d,0,0);const sw=this.canvas.width/d,sh=this.canvas.height/d;ctx.fillStyle='#0c120e';ctx.fillRect(0,0,sw,sh);const z=this.camera.zoom;const p=this.screen(0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(this.terrain,p.x,p.y,MAP_W*TILE*z,MAP_H*TILE*z);this.drawResources(ctx);this.drawBuildings(ctx);this.drawDungeon(ctx);this.drawMonsters(ctx);this.drawNPCs(ctx);this.drawNight(ctx,sw,sh)}
 drawResources(ctx){const z=this.camera.zoom;for(const r of this.sim.world.resources){if(r.amount<=.05)continue;const p=this.screen(r.x,r.y);if(p.x<-20||p.y<-20||p.x>innerWidth+20||p.y>innerHeight+20)continue;const s=Math.max(2,z*2);ctx.fillStyle=r.kind===RESOURCE.WOOD?'#1f3320':r.kind===RESOURCE.FOOD?'#87994e':r.kind===RESOURCE.WATER?'#71a1ac':r.kind===RESOURCE.IRON?'#7b6c64':'#888778';ctx.fillRect(Math.floor(p.x-s/2),Math.floor(p.y-s/2),s,s)} }
 drawBuildings(ctx){const colors=['#8a6747','#8e7a45','#514941','#6a543b'];for(const b of this.sim.world.buildings){const p=this.screen(b.x,b.y),s=14*this.camera.zoom;ctx.fillStyle=colors[b.type]||'#765';ctx.fillRect(p.x-s/2,p.y-s*.55,s,s*.8);ctx.fillStyle='#2d251d';ctx.fillRect(p.x-s*.12,p.y-s*.12,s*.24,s*.36);if(this.camera.zoom>1.8){ctx.fillStyle='#efe7c9';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText(BUILDING.NAMES[b.type],p.x,p.y-s*.65)}}}
 drawDungeon(ctx){const p=this.screen(this.sim.world.dungeon.x+.5,this.sim.world.dungeon.y+.5),s=13*this.camera.zoom;ctx.strokeStyle='#bd7ba0';ctx.lineWidth=2;ctx.strokeRect(p.x-s/2,p.y-s/2,s,s);ctx.fillStyle='#e0aac8';ctx.font=`${Math.max(9,6*this.camera.zoom)}px monospace`;ctx.textAlign='center';ctx.fillText('▼',p.x,p.y+3)}
 drawMonsters(ctx){for(const m of this.sim.world.monsters)if(m.hp>0){const p=this.screen(m.x,m.y),s=6*this.camera.zoom;ctx.fillStyle='#6e2f36';ctx.fillRect(p.x-s/2,p.y-s/2,s,s);ctx.fillStyle='#d8a271';ctx.fillRect(p.x-s*.2,p.y-s*.15,1.5*this.camera.zoom,1.5*this.camera.zoom)}}
 drawNPCs(ctx){const n=this.sim.npcs,z=this.camera.zoom;for(const i of n.living()){const p=this.screen(n.x[i],n.y[i]);if(p.x<-30||p.y<-30||p.x>innerWidth+30||p.y>innerHeight+30)continue;const frame=Math.min(5,Math.floor(n.gene(i,GENE.SKIN)*6));const s=16*z;ctx.drawImage(this.atlas,frame*16,0,16,26,p.x-s/2,p.y-s*.8,s,26*z);if(i===this.selected){ctx.strokeStyle='#efd47f';ctx.lineWidth=1.5;ctx.strokeRect(p.x-s*.55,p.y-s*.85,s*1.1,28*z)}if(n.hp[i]<.4){ctx.fillStyle='#6b2828';ctx.fillRect(p.x-s*.5,p.y-s*.95,s,2*z);ctx.fillStyle='#d76356';ctx.fillRect(p.x-s*.5,p.y-s*.95,s*n.hp[i],2*z)}if(z>=2.5){ctx.fillStyle='#eee7ca';ctx.font='8px monospace';ctx.textAlign='center';ctx.fillText(n.names[i].split(' ')[0],p.x,p.y-s*.95-4)}}}
 drawNight(ctx,w,h){const f=(this.sim.tick%240)/240;let a=0;if(f<.18)a=(.18-f)/.18*.48;else if(f>.78)a=(f-.78)/.22*.48;if(a){ctx.fillStyle=`rgba(5,8,18,${a})`;ctx.fillRect(0,0,w,h)}}
 bind(){const pos=e=>{const r=this.canvas.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:t.clientX-r.left,y:t.clientY-r.top}};this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture?.(e.pointerId);const p=pos(e);this.drag={x:p.x,y:p.y,cx:this.camera.x,cy:this.camera.y,moved:false}});this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=pos(e),dx=p.x-this.drag.x,dy=p.y-this.drag.y;if(Math.hypot(dx,dy)>5)this.drag.moved=true;this.camera.x=this.drag.cx-dx/(TILE*this.camera.zoom);this.camera.y=this.drag.cy-dy/(TILE*this.camera.zoom);this.clamp()});this.canvas.addEventListener('pointerup',e=>{if(this.drag&&!this.drag.moved){const p=pos(e),w=this.world(p.x,p.y);let best=-1,d=.7;for(const i of this.sim.npcs.living()){const dd=Math.hypot(this.sim.npcs.x[i]-w.x,this.sim.npcs.y[i]-w.y);if(dd<d){d=dd;best=i}}if(best>=0){this.selected=best;this.onPick(best)}}this.drag=null});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.camera.zoom=Math.max(.65,Math.min(4.5,this.camera.zoom*(e.deltaY>0?.9:1.1)));this.clamp()},{passive:false});let lastDist=0;this.canvas.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const a=e.touches[0],b=e.touches[1],dist=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(lastDist)this.camera.zoom=Math.max(.65,Math.min(4.5,this.camera.zoom*dist/lastDist));lastDist=dist}},{passive:false});this.canvas.addEventListener('touchend',()=>lastDist=0)}
 clamp(){this.camera.x=Math.max(0,Math.min(MAP_W,this.camera.x));this.camera.y=Math.max(0,Math.min(MAP_H,this.camera.y))}
}
