import {MAP_W,MAP_H,TILE,TILE_TYPE,BIOME,BUILDING,RESOURCE,GENE,TOOL,ARMOR,ANIMAL,MAX_BUBBLES} from '../core/constants.js';
import {dayFraction,isNight} from '../core/clock.js';
const thoughtIcon={
 'voltar para vila':'⌂','buscar água':'💧','beber':'💧','cortar madeira':'🪓','coletar pedra':'⛏','minerar ferro':'⛏','cultivar':'🌱','construir':'🔨','explorar':'?','explorar dungeon':'▼','caçar':'⌖','pescar':'≈','fugir':'!','lutar':'⚔','cozinhar':'♨','costurar':'◇','forjar':'⚒','tratar ferido':'✚','conversar':'…','dormir':'Z','aquecer-se':'♨'};
export class Renderer{
 constructor(canvas,sim,onPick){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.sim=sim;this.onPick=onPick;this.camera={x:sim.world.settlement.x,y:sim.world.settlement.y,zoom:2};this.drag=null;this.selected=-1;this.spriteCache=new Map();this.terrain=null;this.terrainTick=-999;this.resize();this.makeTerrain();addEventListener('resize',()=>this.resize());this.bind()}
 resize(){const dpr=Math.min(2,devicePixelRatio||1),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.floor(r.width*dpr);this.canvas.height=Math.floor(r.height*dpr);this.dpr=dpr;this.ctx.imageSmoothingEnabled=false}
 makeTerrain(){const c=document.createElement('canvas');c.width=MAP_W*TILE;c.height=MAP_H*TILE;const x=c.getContext('2d');x.imageSmoothingEnabled=false;for(let y=0;y<MAP_H;y++)for(let xx=0;xx<MAP_W;xx++){const id=this.sim.world.idx(xx,y),t=this.sim.world.tiles[id],b=this.sim.world.biomes[id],px=xx*TILE,py=y*TILE;const base=b===BIOME.WATER?'#315d69':b===BIOME.DENSE_FOREST?'#26442d':b===BIOME.OPEN_FOREST?'#35583a':b===BIOME.ROCK?'#555750':b===BIOME.MOUNTAIN?'#454843':b===BIOME.MARSH?'#3f5947':b===BIOME.BEACH?'#81795a':'#526d43';x.fillStyle=t===TILE_TYPE.TRAIL?'#6b5a3e':t===TILE_TYPE.ROAD?'#756247':t===TILE_TYPE.DUNGEON?'#302534':base;x.fillRect(px,py,TILE,TILE);const e=this.sim.world.elevation[id];if(t===TILE_TYPE.WATER){x.fillStyle='rgba(135,190,198,.28)';x.fillRect(px+2+(y%3),py+5,8,1)}else if(b===BIOME.DENSE_FOREST||b===BIOME.OPEN_FOREST){if((xx*13+y*7)%3===0){x.fillStyle=b===BIOME.DENSE_FOREST?'#1d3624':'#29492f';x.fillRect(px+4,py+2,8,8);x.fillStyle='#3a2d21';x.fillRect(px+7,py+9,2,4)}}else if(b===BIOME.ROCK||b===BIOME.MOUNTAIN){x.fillStyle=`rgba(220,220,205,${.08+e*.08})`;x.fillRect(px+3,py+3,8,3)}else if((xx*17+y*11)%11===0){x.fillStyle='rgba(190,210,145,.18)';x.fillRect(px+4,py+7,2,3)}}this.terrain=c;this.terrainTick=this.sim.tick}
 screen(wx,wy){const z=this.camera.zoom*TILE,sw=this.canvas.width/this.dpr,sh=this.canvas.height/this.dpr;return{x:(wx-this.camera.x)*z+sw/2,y:(wy-this.camera.y)*z+sh/2,z}}
 world(sx,sy){const z=this.camera.zoom*TILE,sw=this.canvas.width/this.dpr,sh=this.canvas.height/this.dpr;return{x:(sx-sw/2)/z+this.camera.x,y:(sy-sh/2)/z+this.camera.y}}
 render(alpha=1){this.sim.viewX=this.camera.x;this.sim.viewY=this.camera.y;if(this.sim.tick-this.terrainTick>180)this.makeTerrain();const ctx=this.ctx,d=this.dpr;ctx.setTransform(d,0,0,d,0,0);const sw=this.canvas.width/d,sh=this.canvas.height/d;ctx.fillStyle='#0b100d';ctx.fillRect(0,0,sw,sh);const p=this.screen(0,0),z=this.camera.zoom;ctx.imageSmoothingEnabled=false;ctx.drawImage(this.terrain,p.x,p.y,MAP_W*TILE*z,MAP_H*TILE*z);this.drawResources(ctx,sw,sh);this.drawBlueprints(ctx);this.drawBlocks(ctx);this.drawDungeons(ctx);this.drawAnimals(ctx,alpha);this.drawMonsters(ctx);this.drawNPCs(ctx,alpha);this.drawLighting(ctx,sw,sh);this.drawBubbles(ctx,sw,sh)}
 visible(p,margin=40){return p.x>-margin&&p.y>-margin&&p.x<this.canvas.width/this.dpr+margin&&p.y<this.canvas.height/this.dpr+margin}
 drawResources(ctx){for(const r of this.sim.world.resources){if(r.amount<=.05)continue;const p=this.screen(r.x,r.y);if(!this.visible(p,20))continue;const s=Math.max(2,this.camera.zoom*2.2);ctx.fillStyle=r.kind===RESOURCE.LOG?'#29452a':r.kind===RESOURCE.BERRY?'#8c9e4c':r.kind===RESOURCE.WATER?'#83b6c0':r.kind===RESOURCE.IRON?'#765f5c':r.kind===RESOURCE.FISH?'#b0c9c4':r.kind===RESOURCE.CLAY?'#8f6954':'#929183';ctx.fillRect(Math.floor(p.x-s/2),Math.floor(p.y-s/2),s,s)} }
 drawBlocks(ctx){const colors=['#806746','#6d523d','#493a2b','#745b40','#d28c45','#73716a'];for(const b of this.sim.world.blocks){const p=this.screen(b.x+.5,b.y+.5);if(!this.visible(p,25))continue;const s=14*this.camera.zoom;ctx.fillStyle=colors[b.type]||'#765';if(b.type===4){ctx.beginPath();ctx.arc(p.x,p.y,s*.25,0,Math.PI*2);ctx.fill()}else ctx.fillRect(p.x-s/2,p.y-s/2,s,s*.72)}}
 drawBlueprints(ctx){ctx.save();ctx.globalAlpha=.48;for(const bp of this.sim.world.blueprints)if(!bp.done)for(const q of bp.pieces)if(!q.done){const p=this.screen(q.x+.5,q.y+.5),s=12*this.camera.zoom;if(!this.visible(p))continue;ctx.strokeStyle='#d8c98c';ctx.setLineDash([3,2]);ctx.strokeRect(p.x-s/2,p.y-s/2,s,s*.7);if(q.reserved&&q.progress){ctx.fillStyle='#d8c98c';ctx.fillRect(p.x-s/2,p.y+s*.42,s*q.progress,2)}}ctx.restore()}
 drawDungeons(ctx){for(const d of this.sim.world.dungeons){const p=this.screen(d.x,d.y),s=13*this.camera.zoom;if(!this.visible(p))continue;ctx.fillStyle='#17131a';ctx.fillRect(p.x-s/2,p.y-s/2,s,s);ctx.strokeStyle='#a06a8b';ctx.lineWidth=2;ctx.strokeRect(p.x-s/2,p.y-s/2,s,s);ctx.fillStyle='#d79cbc';ctx.font=`${Math.max(9,5*this.camera.zoom)}px monospace`;ctx.textAlign='center';ctx.fillText('▼',p.x,p.y+3)}}
 drawAnimals(ctx,alpha){for(const a of this.sim.animals.items)if(a.alive){const x=a.prevX+(a.x-a.prevX)*alpha,y=a.prevY+(a.y-a.prevY)*alpha,p=this.screen(x,y);if(!this.visible(p,20))continue;const s=(a.species===ANIMAL.BEAR?9:a.species===ANIMAL.WOLF?7:a.species===ANIMAL.DEER?7:5)*this.camera.zoom;ctx.fillStyle='rgba(0,0,0,.24)';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.35,s*.55,s*.2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=a.domestic?'#c0ad7b':a.predator?'#62584f':a.species===ANIMAL.BOAR?'#70523c':'#9a8668';ctx.fillRect(p.x-s*.48,p.y-s*.28,s,s*.55);ctx.fillRect(p.x+s*.25,p.y-s*.42,s*.35,s*.3);if(this.camera.zoom>2.7){ctx.fillStyle='#eee4c7';ctx.font='8px monospace';ctx.textAlign='center';ctx.fillText(ANIMAL.NAMES[a.species],p.x,p.y-s*.7)}}}
 drawMonsters(ctx){for(const m of this.sim.world.monsters)if(m.hp>0){const p=this.screen(m.x,m.y);if(!this.visible(p))continue;const s=7*this.camera.zoom;ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.4,s*.6,s*.2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6d3040';ctx.fillRect(p.x-s/2,p.y-s/2,s,s);ctx.fillStyle='#d69a72';ctx.fillRect(p.x-s*.2,p.y-s*.15,1.5*this.camera.zoom,1.5*this.camera.zoom)}}
 drawNPCs(ctx,alpha){const n=this.sim.npcs;for(const i of n.living()){const wx=n.prevX[i]+(n.x[i]-n.prevX[i])*alpha,wy=n.prevY[i]+(n.y[i]-n.prevY[i])*alpha,p=this.screen(wx,wy);if(!this.visible(p,35))continue;const childScale=n.age[i]<16?.58+n.age[i]/40:1,scale=this.camera.zoom*childScale,sprite=this.sprite(i,n.facing[i],n.moving[i]?Math.floor(this.sim.tick/5)%2:0);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(p.x,p.y+7*scale,6*scale,2.3*scale,0,0,Math.PI*2);ctx.fill();ctx.drawImage(sprite,p.x-12*scale,p.y-25*scale,24*scale,32*scale);if(i===this.selected){ctx.strokeStyle='#efd47f';ctx.lineWidth=1.5;ctx.strokeRect(p.x-13*scale,p.y-26*scale,26*scale,34*scale)}if(n.intent[i]&&n.progress[i]>0){ctx.fillStyle='rgba(12,12,10,.8)';ctx.fillRect(p.x-10*scale,p.y-31*scale,20*scale,2.2*scale);ctx.fillStyle='#e1c36c';ctx.fillRect(p.x-10*scale,p.y-31*scale,20*scale*n.progress[i],2.2*scale)}const icon=thoughtIcon[n.action[i]];if(icon&&this.camera.zoom>1.25){ctx.fillStyle='rgba(239,235,214,.92)';ctx.beginPath();ctx.arc(p.x+10*scale,p.y-25*scale,6*scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#27251f';ctx.font=`${Math.max(7,7*scale)}px sans-serif`;ctx.textAlign='center';ctx.fillText(icon,p.x+10*scale,p.y-22.5*scale)}if(this.camera.zoom>2.5){ctx.fillStyle='#f1ead0';ctx.font='8px monospace';ctx.textAlign='center';ctx.fillText(n.names[i].split(' ')[0],p.x,p.y-34*scale)}}}
 sprite(i,dir,frame){const n=this.sim.npcs,key=`${Math.floor(n.gene(i,GENE.SKIN)*6)}:${Math.floor(n.gene(i,GENE.HAIR)*5)}:${n.tool[i]}:${n.armor[i]}:${dir}:${frame}`;if(this.spriteCache.has(key))return this.spriteCache.get(key);const c=document.createElement('canvas');c.width=24;c.height=32;const x=c.getContext('2d');x.imageSmoothingEnabled=false;const skin=['#d7bb92','#c89c73','#ab815f','#805e49','#b97c59','#93694e'][Math.floor(n.gene(i,GENE.SKIN)*6)%6],hair=['#33261d','#5b3b26','#1f1c1a','#8b653a','#4c3a2d'][Math.floor(n.gene(i,GENE.HAIR)*5)%5],armor=['#6f7851','#7e776b','#6f553e','#676b70'][n.armor[i]||0];x.fillStyle='rgba(0,0,0,.14)';if(frame)x.fillRect(7,25,4,6),x.fillRect(14,24,4,7);else x.fillRect(8,24,4,7),x.fillRect(13,24,4,7);x.fillStyle=armor;x.fillRect(6,11,12,13);x.fillStyle=skin;x.fillRect(8,4,8,8);x.fillStyle=hair;x.fillRect(7,3,10,4);x.fillStyle='#181713';if(dir===0)x.fillRect(10,7,1,1),x.fillRect(14,7,1,1);else if(dir===1)x.fillRect(15,7,1,1);else if(dir===3)x.fillRect(8,7,1,1);const tool=n.tool[i];if(tool){x.fillStyle=tool===TOOL.SWORD?'#b8bbc0':tool===TOOL.AXE?'#9da19d':tool===TOOL.PICK?'#8e8f91':'#99744d';if(dir===3)x.fillRect(3,13,2,12);else x.fillRect(19,13,2,12);x.fillStyle='#5a3e29';if(dir===3)x.fillRect(4,18,1,8);else x.fillRect(19,18,1,8)}this.spriteCache.set(key,c);if(this.spriteCache.size>180)this.spriteCache.delete(this.spriteCache.keys().next().value);return c}
 drawLighting(ctx,w,h){const f=dayFraction(this.sim.tick);let tint=null,a=0;if(isNight(this.sim.tick)){tint='#13213b';a=.46}else if(f>.68&&f<.82){tint='#8a4f38';a=.13}else if(f>.16&&f<.26){tint='#b4774f';a=.1}if(tint){ctx.fillStyle=tint;ctx.globalAlpha=a;ctx.fillRect(0,0,w,h);ctx.globalAlpha=1}if(isNight(this.sim.tick)){ctx.save();ctx.globalCompositeOperation='lighter';for(const b of this.sim.world.buildings)if(b.finished&&(b.type===BUILDING.CAMPFIRE||b.type===BUILDING.SHELTER)){const p=this.screen(b.x,b.y);if(!this.visible(p,100))continue;const r=55*this.camera.zoom,g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,'rgba(255,188,98,.22)');g.addColorStop(1,'rgba(255,170,80,0)');ctx.fillStyle=g;ctx.fillRect(p.x-r,p.y-r,r*2,r*2)}ctx.restore()}}
 drawBubbles(ctx,w,h){const candidates=this.sim.bubbles.filter(b=>b.until>this.sim.tick&&this.sim.npcs.alive[b.npc]).map(b=>({...b,p:this.screen(this.sim.npcs.x[b.npc],this.sim.npcs.y[b.npc])})).filter(b=>this.visible(b.p,80)).sort((a,b)=>b.importance-a.importance).slice(0,MAX_BUBBLES);let offset=0;for(const b of candidates){const text=String(b.text),short=text.length>46?text.slice(0,43)+'…':text,x=b.p.x,y=b.p.y-42*this.camera.zoom-offset;ctx.font='9px monospace';const width=Math.min(190,ctx.measureText(short).width+14);ctx.fillStyle=b.type==='fala'?'rgba(241,236,215,.94)':'rgba(218,224,220,.9)';roundRect(ctx,x-width/2,y-15,width,20,6);ctx.fill();ctx.fillStyle='#25251f';ctx.textAlign='center';ctx.fillText(short,x,y-2);offset=(offset+7)%22}}
 bind(){const pos=e=>{const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture?.(e.pointerId);const p=pos(e);this.drag={x:p.x,y:p.y,cx:this.camera.x,cy:this.camera.y,moved:false}});this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=pos(e),dx=p.x-this.drag.x,dy=p.y-this.drag.y;if(Math.hypot(dx,dy)>5)this.drag.moved=true;this.camera.x=this.drag.cx-dx/(TILE*this.camera.zoom);this.camera.y=this.drag.cy-dy/(TILE*this.camera.zoom);this.clamp()});this.canvas.addEventListener('pointerup',e=>{if(this.drag&&!this.drag.moved){const p=pos(e),q=this.world(p.x,p.y);let best=-1,bd=.8;for(const i of this.sim.npcs.living()){const d=Math.hypot(this.sim.npcs.x[i]-q.x,this.sim.npcs.y[i]-q.y);if(d<bd){bd=d;best=i}}if(best>=0){this.selected=best;this.onPick(best)}}this.drag=null});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.camera.zoom=Math.max(.55,Math.min(5,this.camera.zoom*(e.deltaY>0?.9:1.1)));this.clamp()},{passive:false});let lastDist=0;this.canvas.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const a=e.touches[0],b=e.touches[1],dist=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(lastDist)this.camera.zoom=Math.max(.55,Math.min(5,this.camera.zoom*dist/lastDist));lastDist=dist}},{passive:false});this.canvas.addEventListener('touchend',()=>lastDist=0)}
 clamp(){this.camera.x=Math.max(0,Math.min(MAP_W,this.camera.x));this.camera.y=Math.max(0,Math.min(MAP_H,this.camera.y))}
}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
