import {MAP_W,MAP_H,TILE_TYPE} from '../core/constants.js';
const N=MAP_W*MAP_H,dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,1.414],[1,-1,1.414],[-1,1,1.414],[-1,-1,1.414]];
export class Pathfinder{
 constructor(world){this.world=world;this.cache=new Map();this.came=new Int32Array(N);this.g=new Float32Array(N);this.f=new Float32Array(N);this.heap=new Int32Array(N);this.heapSize=0;this.open=new Uint8Array(N)}
 clear(){this.cache.clear()}
 cost(x,y){if(x<0||y<0||x>=MAP_W||y>=MAP_H)return Infinity;const t=this.world.tile(x,y);if(t===TILE_TYPE.WATER||t===TILE_TYPE.MOUNTAIN)return Infinity;if(t===TILE_TYPE.MARSH)return 2.2;if(t===TILE_TYPE.STONE)return 1.45;if(t===TILE_TYPE.FOREST)return 1.35;if(t===TILE_TYPE.TRAIL)return .82;if(t===TILE_TYPE.ROAD)return .65;return 1}
 find(sx,sy,tx,ty){sx=Math.floor(sx);sy=Math.floor(sy);tx=Math.floor(tx);ty=Math.floor(ty);const ck=`${sx},${sy}:${tx},${ty}`,cached=this.cache.get(ck);if(cached)return cached.map(p=>[p[0],p[1]]);const start=sy*MAP_W+sx,goal=ty*MAP_W+tx;if(start===goal)return[];this.came.fill(-1);this.g.fill(Infinity);this.f.fill(Infinity);this.open.fill(0);this.heapSize=0;this.g[start]=0;this.f[start]=Math.hypot(tx-sx,ty-sy);this.push(start);this.open[start]=1;let loops=0,found=false;while(this.heapSize&&loops++<N*2){const cur=this.pop();this.open[cur]=2;if(cur===goal){found=true;break}const cx=cur%MAP_W,cy=(cur/MAP_W)|0;for(const[dx,dy,mul]of dirs){const nx=cx+dx,ny=cy+dy,c=this.cost(nx,ny);if(!Number.isFinite(c))continue;const ni=ny*MAP_W+nx;if(this.open[ni]===2)continue;const ng=this.g[cur]+c*mul;if(ng>=this.g[ni])continue;this.came[ni]=cur;this.g[ni]=ng;this.f[ni]=ng+Math.hypot(tx-nx,ty-ny);if(this.open[ni]!==1){this.push(ni);this.open[ni]=1}else this.reheap(ni)}}if(!found)return[];const path=[];let cur=goal,guard=0;while(cur!==start&&cur>=0&&guard++<N){path.push([cur%MAP_W+.5,((cur/MAP_W)|0)+.5]);cur=this.came[cur]}path.reverse();if(this.cache.size>140)this.cache.delete(this.cache.keys().next().value);this.cache.set(ck,path);return path.map(p=>[p[0],p[1]])}
 push(v){let i=this.heapSize++;this.heap[i]=v;while(i>0){const p=(i-1)>>1;if(this.f[this.heap[p]]<=this.f[v])break;this.heap[i]=this.heap[p];i=p;this.heap[i]=v}}
 pop(){const root=this.heap[0],last=this.heap[--this.heapSize];if(this.heapSize>0){let i=0;this.heap[0]=last;while(true){let l=i*2+1,r=l+1,b=i;if(l<this.heapSize&&this.f[this.heap[l]]<this.f[this.heap[b]])b=l;if(r<this.heapSize&&this.f[this.heap[r]]<this.f[this.heap[b]])b=r;if(b===i)break;const t=this.heap[i];this.heap[i]=this.heap[b];this.heap[b]=t;i=b}}return root}
 reheap(v){for(let i=0;i<this.heapSize;i++)if(this.heap[i]===v){while(i>0){const p=(i-1)>>1;if(this.f[this.heap[p]]<=this.f[v])break;this.heap[i]=this.heap[p];i=p;this.heap[i]=v}return}}
}
