import {MAP_W,MAP_H,TILE_TYPE,BIOME} from '../core/constants.js';
const N=MAP_W*MAP_H,dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,1.414],[1,-1,1.414],[-1,1,1.414],[-1,-1,1.414]];
export class Pathfinder{
 constructor(world){this.world=world;this.cache=new Map();this.cacheLimit=192;this.came=new Int32Array(N);this.g=new Float32Array(N);this.f=new Float32Array(N);this.heap=new Int32Array(N);this.heapSize=0;this.open=new Uint8Array(N);this.pending=new Map();this.ready=new Map();this.queue=[];this.searchBudget=0}
 clear(){this.cache.clear();this.pending.clear();this.ready.clear();this.queue.length=0}
 beginTick(limit=3){this.searchBudget=Math.max(0,limit|0);while(this.searchBudget>0&&this.queue.length){const owner=this.queue.shift(),req=this.pending.get(owner);if(!req)continue;this.pending.delete(owner);this.searchBudget--;this.ready.set(owner,{key:req.key,path:this._compute(req.sx,req.sy,req.tx,req.ty,req.key)})}}
 cancel(owner){this.pending.delete(owner);this.ready.delete(owner)}
 cost(x,y){if(x<0||y<0||x>=MAP_W||y>=MAP_H)return Infinity;const id=Math.floor(y)*MAP_W+Math.floor(x),t=this.world.tiles[id],b=this.world.biomes[id];if(t===TILE_TYPE.WATER||b===BIOME.MOUNTAIN)return Infinity;let c=t===TILE_TYPE.ROAD?.68:t===TILE_TYPE.PATH?.78:t===TILE_TYPE.TRAIL?.88:t===TILE_TYPE.MARSH?2:t===TILE_TYPE.STONE?1.45:t===TILE_TYPE.FOREST?1.28:1;c*=1+Math.min(1.1,(this.world.slope?.[id]||0)/180);return c}
 request(owner,sx,sy,tx,ty){sx=Math.floor(sx);sy=Math.floor(sy);tx=Math.floor(tx);ty=Math.floor(ty);const key=this.key(sx,sy,tx,ty);if(sx===tx&&sy===ty)return new Int16Array(0);const cached=this.cached(key);if(cached)return cached.slice();const direct=this.straightPath(sx,sy,tx,ty);if(direct){this.store(key,direct);return direct.slice()}const ready=this.ready.get(owner);if(ready?.key===key){this.ready.delete(owner);return ready.path.slice()}if(ready)this.ready.delete(owner);const pending=this.pending.get(owner);if(pending?.key===key)return null;if(pending)this.pending.delete(owner);const req={sx,sy,tx,ty,key};if(this.searchBudget>0){this.searchBudget--;return this._compute(sx,sy,tx,ty,key).slice()}this.pending.set(owner,req);this.queue.push(owner);return null}
 find(sx,sy,tx,ty){sx=Math.floor(sx);sy=Math.floor(sy);tx=Math.floor(tx);ty=Math.floor(ty);const key=this.key(sx,sy,tx,ty),path=this.cached(key)||this.straightPath(sx,sy,tx,ty)||this._compute(sx,sy,tx,ty,key),out=[];for(let k=0;k<path.length;k+=2)out.push([path[k]+.5,path[k+1]+.5]);return out}
 estimateDistance(sx,sy,tx,ty){sx=Math.floor(sx);sy=Math.floor(sy);tx=Math.floor(tx);ty=Math.floor(ty);const key=this.key(sx,sy,tx,ty),path=this.cached(key);if(path){let px=sx+.5,py=sy+.5,total=0;for(let k=0;k<path.length;k+=2){const x=path[k]+.5,y=path[k+1]+.5;total+=Math.hypot(x-px,y-py);px=x;py=y}return total}return Math.hypot(tx-sx,ty-sy)*(this.straightPath(sx,sy,tx,ty)?1:1.35)}
 key(sx,sy,tx,ty){return`${sx},${sy}:${tx},${ty}`}
 cached(key){const v=this.cache.get(key);if(!v)return null;this.cache.delete(key);this.cache.set(key,v);return v}
 store(key,path){if(this.cache.has(key))this.cache.delete(key);this.cache.set(key,path.slice());while(this.cache.size>this.cacheLimit)this.cache.delete(this.cache.keys().next().value)}
 straightPath(sx,sy,tx,ty){const dx=tx-sx,dy=ty-sy,steps=Math.max(Math.abs(dx),Math.abs(dy));if(!steps)return new Int16Array(0);for(let s=1;s<=steps;s++){const x=Math.round(sx+dx*s/steps),y=Math.round(sy+dy*s/steps);if(!Number.isFinite(this.cost(x,y)))return null}return Int16Array.from([tx,ty])}
 _compute(sx,sy,tx,ty,key=this.key(sx,sy,tx,ty)){const start=sy*MAP_W+sx,goal=ty*MAP_W+tx;if(start===goal)return new Int16Array(0);if(!Number.isFinite(this.cost(tx,ty)))return new Int16Array(0);this.came.fill(-1);this.g.fill(Infinity);this.f.fill(Infinity);this.open.fill(0);this.heapSize=0;this.g[start]=0;this.f[start]=Math.hypot(tx-sx,ty-sy);this.push(start);this.open[start]=1;let loops=0,found=false;while(this.heapSize&&loops++<N*2){const cur=this.pop();this.open[cur]=2;if(cur===goal){found=true;break}const cx=cur%MAP_W,cy=(cur/MAP_W)|0;for(const[dx,dy,mul]of dirs){const nx=cx+dx,ny=cy+dy,c=this.cost(nx,ny);if(!Number.isFinite(c))continue;const ni=ny*MAP_W+nx;if(this.open[ni]===2)continue;const ng=this.g[cur]+c*mul;if(ng>=this.g[ni])continue;this.came[ni]=cur;this.g[ni]=ng;this.f[ni]=ng+Math.hypot(tx-nx,ty-ny);if(this.open[ni]!==1){this.push(ni);this.open[ni]=1}else this.reheap(ni)}}if(!found)return new Int16Array(0);const rev=[];let cur=goal,guard=0;while(cur!==start&&cur>=0&&guard++<N){rev.push(cur%MAP_W,((cur/MAP_W)|0));cur=this.came[cur]}const path=new Int16Array(rev.length);for(let src=rev.length-2,dst=0;src>=0;src-=2,dst+=2){path[dst]=rev[src];path[dst+1]=rev[src+1]}this.store(key,path);return path}
 push(v){let i=this.heapSize++;this.heap[i]=v;while(i>0){const p=(i-1)>>1;if(this.f[this.heap[p]]<=this.f[v])break;this.heap[i]=this.heap[p];i=p;this.heap[i]=v}}
 pop(){const root=this.heap[0],last=this.heap[--this.heapSize];if(this.heapSize>0){let i=0;this.heap[0]=last;while(true){let l=i*2+1,r=l+1,b=i;if(l<this.heapSize&&this.f[this.heap[l]]<this.f[this.heap[b]])b=l;if(r<this.heapSize&&this.f[this.heap[r]]<this.f[this.heap[b]])b=r;if(b===i)break;const t=this.heap[i];this.heap[i]=this.heap[b];this.heap[b]=t;i=b}}return root}
 reheap(v){for(let i=0;i<this.heapSize;i++)if(this.heap[i]===v){while(i>0){const p=(i-1)>>1;if(this.f[this.heap[p]]<=this.f[v])break;this.heap[i]=this.heap[p];i=p;this.heap[i]=v}return}}
}
