import {MAP_W,MAP_H,TILE_TYPE,BIOME,RESOURCE,BUILDING,BLOCK,TOOL,DUNGEON_COUNT,FOOD_KINDS} from '../core/constants.js';
import {noiseHash} from '../core/rng.js';
import {Pathfinder} from './pathfinding.js';
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function smooth(t){return t*t*(3-2*t)}
function valueNoise(x,y,scale,seed){const fx=x/scale,fy=y/scale,x0=Math.floor(fx),y0=Math.floor(fy),tx=smooth(fx-x0),ty=smooth(fy-y0);const a=noiseHash(x0,y0,seed),b=noiseHash(x0+1,y0,seed),c=noiseHash(x0,y0+1,seed),d=noiseHash(x0+1,y0+1,seed);const ab=a+(b-a)*tx,cd=c+(d-c)*tx;return ab+(cd-ab)*ty}
function fbm(x,y,seed){return valueNoise(x,y,28,seed)*.5+valueNoise(x,y,14,seed+31)*.3+valueNoise(x,y,7,seed+73)*.2}
export class World{
 constructor(rng,seed=1){this.rng=rng;this.seed=seed>>>0;const N=MAP_W*MAP_H;this.tiles=new Uint8Array(N);this.biomes=new Uint8Array(N);this.elevation=new Float32Array(N);this.moisture=new Float32Array(N);this.traffic=new Float32Array(N);this.resources=[];this.resourceMask=new Uint32Array(N);this.buildings=[];this.blocks=[];this.blueprints=[];this.stock=new Float32Array(RESOURCE.COUNT);this.tools=new Uint16Array(8);this.foodBatches=[];this.monsters=[];this.dungeons=[];this.settlement={x:MAP_W/2,y:MAP_H/2,score:0};this.pathfinder=new Pathfinder(this);this.generate()}
 idx(x,y){return Math.floor(y)*MAP_W+Math.floor(x)}
 inside(x,y){return x>=0&&y>=0&&x<MAP_W&&y<MAP_H}
 tile(x,y){if(!this.inside(x,y))return TILE_TYPE.MOUNTAIN;return this.tiles[this.idx(x,y)]}
 biome(x,y){if(!this.inside(x,y))return BIOME.MOUNTAIN;return this.biomes[this.idx(x,y)]}
 generate(){this.generateElevation();this.generateWater();this.generateMoistureBiomes();this.placeResources();this.chooseSettlement();this.placeDungeons();this.makeStarterCamp();}
 generateElevation(){for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++){const edge=Math.min(x,y,MAP_W-1-x,MAP_H-1-y)/(MAP_W*.22);let e=fbm(x,y,this.seed);e=.15+e*.85;const ridge=Math.abs(valueNoise(x+17,y-9,20,this.seed+911)-.5)*.22;e+=ridge;if(edge<1)e-=Math.pow(1-edge,2)*.28;this.elevation[this.idx(x,y)]=clamp(e)}}
 generateWater(){const N=MAP_W*MAP_H;for(let i=0;i<N;i++)this.tiles[i]=this.elevation[i]<.18?TILE_TYPE.WATER:TILE_TYPE.GRASS;const peaks=[];for(let y=6;y<MAP_H-6;y++)for(let x=6;x<MAP_W-6;x++){const e=this.elevation[this.idx(x,y)];if(e>.68&&noiseHash(x,y,this.seed+1201)>.985)peaks.push([x,y,e])}peaks.sort((a,b)=>b[2]-a[2]);for(const src of peaks.slice(0,5))this.carveRiver(src[0],src[1]);}
 carveRiver(x,y){const visited=new Set();for(let step=0;step<MAP_W*2;step++){const id=this.idx(x,y);if(visited.has(id))break;visited.add(id);this.tiles[id]=TILE_TYPE.WATER;for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(this.inside(x+dx,y+dy)&&this.rng.chance(.22))this.tiles[this.idx(x+dx,y+dy)]=TILE_TYPE.WATER;if(this.elevation[id]<.2)break;let best=null,be=Infinity;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(!this.inside(nx,ny))continue;let e=this.elevation[this.idx(nx,ny)]+noiseHash(nx,ny,this.seed+step)*.025;if(e<be&&!visited.has(this.idx(nx,ny))){be=e;best=[nx,ny]}}if(!best){for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(this.inside(xx,yy))this.tiles[this.idx(xx,yy)]=TILE_TYPE.WATER;break}x=best[0];y=best[1]}}
 generateMoistureBiomes(){const waters=[];for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++)if(this.tiles[this.idx(x,y)]===TILE_TYPE.WATER)waters.push([x,y]);for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++){const id=this.idx(x,y),e=this.elevation[id];if(this.tiles[id]===TILE_TYPE.WATER){this.biomes[id]=BIOME.WATER;this.moisture[id]=1;continue}let md=20;for(let k=0;k<waters.length;k+=Math.max(1,Math.floor(waters.length/180))){const[wX,wY]=waters[k];md=Math.min(md,Math.hypot(x-wX,y-wY));}let m=clamp(1-md/18+valueNoise(x,y,11,this.seed+501)*.32);this.moisture[id]=m;let b=BIOME.FIELD;if(e>.79)b=BIOME.MOUNTAIN;else if(e>.66)b=BIOME.ROCK;else if(m>.78&&e<.46)b=BIOME.MARSH;else if(m>.64)b=BIOME.DENSE_FOREST;else if(m>.48)b=BIOME.OPEN_FOREST;else if(e<.25)b=BIOME.BEACH;this.biomes[id]=b;if(b===BIOME.MOUNTAIN)this.tiles[id]=TILE_TYPE.MOUNTAIN;else if(b===BIOME.ROCK)this.tiles[id]=TILE_TYPE.STONE;else if(b===BIOME.MARSH)this.tiles[id]=TILE_TYPE.MARSH;else if(b===BIOME.DENSE_FOREST||b===BIOME.OPEN_FOREST)this.tiles[id]=TILE_TYPE.FOREST;else if(b===BIOME.BEACH)this.tiles[id]=TILE_TYPE.BEACH;else this.tiles[id]=TILE_TYPE.GRASS}}
 placeResources(){for(let y=2;y<MAP_H-2;y++)for(let x=2;x<MAP_W-2;x++){const id=this.idx(x,y),b=this.biomes[id],r=noiseHash(x,y,this.seed+3001);if((b===BIOME.DENSE_FOREST&&r>.48)||(b===BIOME.OPEN_FOREST&&r>.72))this.addResource(RESOURCE.LOG,x+.5,y+.5,3+noiseHash(x,y,this.seed+1)*6,.00008,3.5);if((b===BIOME.FIELD||b===BIOME.OPEN_FOREST)&&r<.11)this.addResource(RESOURCE.BERRY,x+.5,y+.5,.8+noiseHash(x,y,this.seed+2)*2,.0006,1.4);if((b===BIOME.ROCK||b===BIOME.MOUNTAIN)&&r>.72)this.addResource(RESOURCE.STONE,x+.5,y+.5,5+noiseHash(x,y,this.seed+3)*10,0,4);if(b===BIOME.ROCK&&r<.12)this.addResource(RESOURCE.IRON,x+.5,y+.5,4+noiseHash(x,y,this.seed+4)*7,0,5);if(b===BIOME.BEACH&&r<.25)this.addResource(RESOURCE.CLAY,x+.5,y+.5,2+noiseHash(x,y,this.seed+5)*6,.0002,2);if(this.tiles[id]===TILE_TYPE.WATER&&r<.32){this.addResource(RESOURCE.WATER,x+.5,y+.5,999,1,1);if(r<.16)this.addResource(RESOURCE.FISH,x+.5,y+.5,2+noiseHash(x,y,this.seed+6)*5,.0012,2)}}}
 chooseSettlement(){let best={x:MAP_W/2,y:MAP_H/2,score:-1e9};for(let y=8;y<MAP_H-8;y+=2)for(let x=8;x<MAP_W-8;x+=2){const id=this.idx(x,y);if(this.tiles[id]!==TILE_TYPE.GRASS&&this.tiles[id]!==TILE_TYPE.BEACH)continue;let water=99,wood=0,stone=0,rough=0;for(let yy=y-8;yy<=y+8;yy+=2)for(let xx=x-8;xx<=x+8;xx+=2){if(!this.inside(xx,yy))continue;const d=Math.hypot(xx-x,yy-y),t=this.tile(xx,yy);if(t===TILE_TYPE.WATER)water=Math.min(water,d);if(t===TILE_TYPE.FOREST)wood++;if(t===TILE_TYPE.STONE)stone++;rough+=Math.abs(this.elevation[this.idx(xx,yy)]-this.elevation[id])}const score=(12-Math.min(12,water))*2+Math.min(12,wood)*.5+Math.min(8,stone)*.4-rough*.05;if(score>best.score)best={x,y,score}}this.settlement=best}
 placeDungeons(){const candidates=[];for(let y=5;y<MAP_H-5;y++)for(let x=5;x<MAP_W-5;x++){const b=this.biome(x,y),d=Math.hypot(x-this.settlement.x,y-this.settlement.y);if(d>12&&(b===BIOME.ROCK||b===BIOME.MOUNTAIN)&&noiseHash(x,y,this.seed+8011)>.965)candidates.push([x,y,d])}candidates.sort((a,b)=>b[2]-a[2]);for(const c of candidates){if(this.dungeons.length>=DUNGEON_COUNT)break;if(this.dungeons.some(d=>Math.hypot(d.x-c[0],d.y-c[1])<11))continue;this.tiles[this.idx(c[0],c[1])]=TILE_TYPE.DUNGEON;this.dungeons.push({id:this.dungeons.length,x:c[0]+.5,y:c[1]+.5})}while(this.dungeons.length<DUNGEON_COUNT){const a=this.rng.range(0,Math.PI*2),rad=this.rng.range(14,28),x=Math.max(5,Math.min(MAP_W-6,Math.round(this.settlement.x+Math.cos(a)*rad))),y=Math.max(5,Math.min(MAP_H-6,Math.round(this.settlement.y+Math.sin(a)*rad)));if(this.tile(x,y)===TILE_TYPE.WATER)continue;this.tiles[this.idx(x,y)]=TILE_TYPE.DUNGEON;this.dungeons.push({id:this.dungeons.length,x:x+.5,y:y+.5})}}
 makeStarterCamp(){const{x,y}=this.settlement;this.addBuilding(BUILDING.SHELTER,x-2,y-1,true);this.addBuilding(BUILDING.STORAGE,x+2,y,true);this.addBuilding(BUILDING.WELL,x,y+2,true);this.addBuilding(BUILDING.CAMPFIRE,x,y-1,true);this.addResource(RESOURCE.WATER,x+.5,y+2.5,999,1,1);for(const[dx,dy]of[[-4,-2],[4,-2],[-4,3],[4,3]])this.addResource(RESOURCE.BERRY,x+dx+.5,y+dy+.5,5,.001,1.4);this.stock[RESOURCE.LOG]=22;this.stock[RESOURCE.STONE]=12;this.stock[RESOURCE.IRON]=2;this.stock[RESOURCE.GRAIN]=0;this.stock[RESOURCE.WATER]=28;this.stock[RESOURCE.SEED]=14;this.addFoodBatch(RESOURCE.GRAIN,18,0);this.addFoodBatch(RESOURCE.BERRY,22,0);this.tools[TOOL.AXE]=2;this.tools[TOOL.PICK]=2;this.tools[TOOL.HAMMER]=2;this.tools[TOOL.KNIFE]=2;this.tools[TOOL.ROD]=1}
 addResource(kind,x,y,amount,regen=0,durability=1){const r={id:this.resources.length,kind,x,y,amount,max:amount,regen,durability,maxDurability:durability};this.resources.push(r);if(this.inside(x,y))this.resourceMask[this.idx(x,y)]|=1<<kind;return r}
 resourceAtTile(x,y){return this.inside(x,y)?this.resourceMask[this.idx(x,y)]:0}
 findResourceAt(x,y,kind,rad=.8){let best=null,bd=rad;for(const r of this.resources)if(r.kind===kind&&r.amount>.01){const d=Math.hypot(r.x-x,r.y-y);if(d<bd){bd=d;best=r}}return best}
 harvest(ref,amount){if(!ref||ref.amount<=0)return 0;const got=Math.min(ref.amount,amount);ref.amount-=got;if(ref.amount<=.01){ref.durability=0;if(!ref.regen&&this.inside(ref.x,ref.y))this.resourceMask[this.idx(ref.x,ref.y)]&=~(1<<ref.kind)}return got}
 addBuilding(type,x,y,finished=false){const b={id:this.buildings.length,type,x,y,hp:1,finished,lit:type===BUILDING.CAMPFIRE};this.buildings.push(b);if(finished)this.buildStructureBlocks(b);return b}
 buildStructureBlocks(b){const pattern=b.type===BUILDING.CAMPFIRE?[[0,0,BLOCK.FIRE]]:b.type===BUILDING.WELL?[[0,0,BLOCK.WELL]]:[[-1,-1,BLOCK.WALL],[0,-1,BLOCK.WALL],[1,-1,BLOCK.WALL],[-1,0,BLOCK.WALL],[1,0,BLOCK.WALL],[-1,1,BLOCK.WALL],[0,1,BLOCK.DOOR],[1,1,BLOCK.WALL],[0,0,BLOCK.FLOOR]];for(const[dx,dy,type]of pattern)this.blocks.push({x:b.x+dx,y:b.y+dy,type,hp:1,buildingId:b.id})}
 nearBuilding(x,y,type,rad=3){return this.buildings.some(b=>b.finished&&(type==null||b.type===type)&&Math.hypot(b.x-x,b.y-y)<=rad)}
 nearestBuildingLocal(x,y,type,rad=14){let best=null,bd=rad;for(const b of this.buildings)if(b.finished&&(type==null||b.type===type)){const d=Math.hypot(b.x-x,b.y-y);if(d<bd){bd=d;best={...b,d,ref:b}}}return best}
 temperatureAt(x,y,tick,ambient){let temp=ambient;if(this.nearBuilding(x,y,BUILDING.CAMPFIRE,4))temp+=8;if(this.nearBuilding(x,y,BUILDING.SHELTER,2.5))temp+=5;return temp}
 walkTile(x,y,amount=.02){if(!this.inside(x,y))return;const id=this.idx(x,y);if(this.tiles[id]===TILE_TYPE.WATER||this.tiles[id]===TILE_TYPE.MOUNTAIN)return;this.traffic[id]=Math.min(100,this.traffic[id]+amount);if(this.traffic[id]>18&&this.tiles[id]===TILE_TYPE.GRASS)this.tiles[id]=TILE_TYPE.TRAIL;if(this.traffic[id]>48&&this.tiles[id]===TILE_TYPE.TRAIL)this.tiles[id]=TILE_TYPE.ROAD}
 moveFactor(x,y){const t=this.tile(x,y);return t===TILE_TYPE.ROAD?1.35:t===TILE_TYPE.TRAIL?1.18:t===TILE_TYPE.MARSH?.58:t===TILE_TYPE.STONE?.72:t===TILE_TYPE.FOREST?.78:1}
 addFoodBatch(kind,amount,tick){if(!FOOD_KINDS.has(kind)||amount<=0)return;const life=kind===RESOURCE.BERRY?840*5:kind===RESOURCE.MEAT?840*3:kind===RESOURCE.FISH?840*2:kind===RESOURCE.EGG?840*6:kind===RESOURCE.MILK?840*2:kind===RESOURCE.GRAIN?840*35:840*120;this.foodBatches.push({kind,amount,born:tick,expires:tick+life});this.stock[kind]+=amount}
 consumeFood(tick){this.expireFood(tick);this.foodBatches.sort((a,b)=>a.expires-b.expires);for(const b of this.foodBatches)if(b.amount>.08){const n=Math.min(.14,b.amount);b.amount-=n;this.stock[b.kind]=Math.max(0,this.stock[b.kind]-n);return{kind:b.kind,amount:n}}return null}
 expireFood(tick){for(const b of this.foodBatches)if(b.amount>0&&tick>=b.expires){this.stock[b.kind]=Math.max(0,this.stock[b.kind]-b.amount);b.amount=0}if(this.foodBatches.length>180)this.foodBatches=this.foodBatches.filter(b=>b.amount>.01)}
 tick(tick){for(const r of this.resources)if(r.regen&&r.amount<r.max){const was=r.amount;r.amount=Math.min(r.max,r.amount+r.regen);if(r.amount>.05){r.durability=Math.max(r.durability,r.maxDurability*.3);if(was<=.01&&this.inside(r.x,r.y))this.resourceMask[this.idx(r.x,r.y)]|=1<<r.kind}}this.expireFood(tick);for(let i=0;i<this.traffic.length;i++)this.traffic[i]*=.99998}
 createBlueprint(type,cx,cy){if(this.blueprints.some(b=>!b.done&&b.type===type))return null;const pieces=[];const pattern=type===BUILDING.CAMPFIRE?[[0,0,BLOCK.FIRE,RESOURCE.STONE,.8]]:type===BUILDING.WELL?[[0,0,BLOCK.WELL,RESOURCE.STONE,2.5]]:[[-1,-1,BLOCK.WALL,RESOURCE.LOG,1],[0,-1,BLOCK.WALL,RESOURCE.LOG,1],[1,-1,BLOCK.WALL,RESOURCE.LOG,1],[-1,0,BLOCK.WALL,RESOURCE.LOG,1],[1,0,BLOCK.WALL,RESOURCE.LOG,1],[-1,1,BLOCK.WALL,RESOURCE.LOG,1],[0,1,BLOCK.DOOR,RESOURCE.LOG,.7],[1,1,BLOCK.WALL,RESOURCE.LOG,1],[0,0,BLOCK.FLOOR,RESOURCE.LOG,.6]];for(const[dx,dy,block,material,cost]of pattern)pieces.push({x:cx+dx,y:cy+dy,block,material,cost,progress:0,done:false});const bp={id:this.blueprints.length,type,cx,cy,pieces,done:false};this.blueprints.push(bp);return bp}
 nextBlueprintPiece(){for(const bp of this.blueprints)if(!bp.done){const p=bp.pieces.find(x=>!x.done);if(p)return{bp,piece:p}}return null}
 completePiece(bp,p){p.done=true;p.progress=1;this.blocks.push({x:p.x,y:p.y,type:p.block,hp:1,buildingId:-1});if(bp.pieces.every(x=>x.done)){bp.done=true;const b=this.addBuilding(bp.type,bp.cx,bp.cy,false);b.finished=true;for(const block of this.blocks)if(block.buildingId===-1&&Math.hypot(block.x-bp.cx,block.y-bp.cy)<3)block.buildingId=b.id;return b}return null}
 serialize(){const trafficSparse=[];for(let i=0;i<this.traffic.length;i++)if(this.traffic[i]>.1)trafficSparse.push([i,+this.traffic[i].toFixed(3)]);return{seed:this.seed,trafficSparse,resources:this.resources,buildings:this.buildings,blocks:this.blocks,blueprints:this.blueprints,stock:Array.from(this.stock),tools:Array.from(this.tools),foodBatches:this.foodBatches,monsters:this.monsters,dungeons:this.dungeons,settlement:this.settlement}}
 static hydrate(d,rng,seed=1){const w=new World(rng,d.seed??seed);if(d.biomes)w.biomes.set(d.biomes);if(d.elevation)w.elevation.set(d.elevation);if(d.moisture)w.moisture.set(d.moisture);if(d.traffic)w.traffic.set(d.traffic);if(d.trafficSparse)for(const[i,v]of d.trafficSparse)if(i>=0&&i<w.traffic.length)w.traffic[i]=v;w.resources=d.resources||w.resources;w.resourceMask.fill(0);for(const r of w.resources)if(r.amount>.01&&w.inside(r.x,r.y))w.resourceMask[w.idx(r.x,r.y)]|=1<<r.kind;w.buildings=d.buildings||w.buildings;w.blocks=d.blocks||w.blocks;w.blueprints=d.blueprints||[];if(d.stock){w.stock.fill(0);w.stock.set(d.stock.slice(0,RESOURCE.COUNT))}if(d.tools)w.tools.set(d.tools.slice(0,w.tools.length));w.foodBatches=d.foodBatches||[];w.monsters=d.monsters||[];w.dungeons=d.dungeons?.length?d.dungeons:w.dungeons;w.settlement=d.settlement||w.settlement;for(let i=0;i<w.traffic.length;i++){if(w.traffic[i]>48&&w.tiles[i]===TILE_TYPE.GRASS)w.tiles[i]=TILE_TYPE.ROAD;else if(w.traffic[i]>18&&w.tiles[i]===TILE_TYPE.GRASS)w.tiles[i]=TILE_TYPE.TRAIL}w.pathfinder=new Pathfinder(w);return w}
}
