import {MAP_W,MAP_H,GENE} from '../core/constants.js';
const DECAY=.998;
const EMPTY=-1;
function makeSpatial(capacity){const tiles=new Int16Array(capacity);tiles.fill(EMPTY);return{capacity,count:0,cursor:0,tiles,seen:new Uint32Array(capacity),resource:new Uint32Array(capacity),flags:new Uint16Array(capacity)}}
export class MemorySystem{
 constructor(){this.episodic=new Map();this.semantic=new Map();this.beliefs=new Map();this.relations=new Map();this.spatial=new Map()}
 ensure(i,capacity=200){if(!this.episodic.has(i))this.episodic.set(i,[]);if(!this.semantic.has(i))this.semantic.set(i,[]);if(!this.beliefs.has(i))this.beliefs.set(i,[]);if(!this.relations.has(i))this.relations.set(i,new Map());if(!this.spatial.has(i))this.spatial.set(i,makeSpatial(capacity))}
 spatialCapacity(npcs,i){return npcs?.derived?Math.max(128,npcs.derived(i).memory):200}
 remember(i,event,capacity=200){this.ensure(i,capacity);const a=this.episodic.get(i);a.push({...event,accesses:0});if(a.length>capacity){a.sort((x,y)=>this.keep(y)-this.keep(x));a.length=capacity}}
 keep(m){return(m.importance||.5)*Math.pow(DECAY,Math.max(0,m.age||0))*(1+(m.accesses||0)*.05)}
 recall(i,context,k=5,tick=0){this.ensure(i);const words=new Set(String(context).toLowerCase().split(/\W+/));const a=this.episodic.get(i);const scored=a.map(m=>{const text=(m.text+' '+(m.type||'')).toLowerCase();let rel=.2;for(const w of words)if(w&&text.includes(w))rel+=.2;const rec=Math.exp(-(tick-m.tick)/3500);return[m,rel*rec*(m.importance||.5)]}).sort((a,b)=>b[1]-a[1]).slice(0,k);for(const[m]of scored)m.accesses=(m.accesses||0)+1;return scored.map(x=>x[0])}
 relation(i,j){this.ensure(i);const m=this.relations.get(i);if(!m.has(j))m.set(j,{trust:0,affection:0,fear:0,respect:0,anger:0,debt:0});return m.get(j)}
 adjust(i,j,delta){const r=this.relation(i,j);for(const[k,v]of Object.entries(delta))r[k]=Math.max(-1,Math.min(1,(r[k]||0)+v))}
 learn(i,fact){this.ensure(i);const a=this.semantic.get(i),old=a.find(x=>x.key===fact.key);if(old){old.confidence=Math.min(1,(old.confidence||.5)+.08);old.tick=fact.tick;old.text=fact.text||old.text}else a.push({...fact,confidence:fact.confidence||.55})}
 observe(i,tileIndex,tick,resourceMask=0,flags=0,capacity=200){this.ensure(i,capacity);let s=this.spatial.get(i);if(s.capacity!==capacity&&s.count===0){s=makeSpatial(capacity);this.spatial.set(i,s)}let slot=-1;for(let k=0;k<s.count;k++)if(s.tiles[k]===tileIndex){slot=k;break}if(slot<0){if(s.count<s.capacity)slot=s.count++;else{slot=-1;let oldest=Infinity;for(let q=0;q<s.count;q++)if(!s.resource[q]&&!s.flags[q]&&s.seen[q]<oldest){oldest=s.seen[q];slot=q}if(slot<0){if(!(resourceMask||flags))return;oldest=Infinity;for(let q=0;q<s.count;q++)if(!(s.flags[q]&1)&&s.seen[q]<oldest){oldest=s.seen[q];slot=q}}if(slot<0)return}}s.tiles[slot]=tileIndex;s.seen[slot]=tick;s.resource[slot]=resourceMask;s.flags[slot]=flags}
 recallNearest(i,x,y,kind,tick,maxAge=DAY_MEMORY){const s=this.spatial.get(i);if(!s)return null;const bit=1<<kind;let best=null,bd=1e9;for(let k=0;k<s.count;k++){if(s.tiles[k]<0||tick-s.seen[k]>maxAge||!(s.resource[k]&bit))continue;const tx=s.tiles[k]%MAP_W,ty=Math.floor(s.tiles[k]/MAP_W),d=Math.hypot(tx+.5-x,ty+.5-y);if(d<bd){bd=d;best={x:tx+.5,y:ty+.5,d,tile:s.tiles[k],seen:s.seen[k],confidence:Math.max(.2,1-(tick-s.seen[k])/maxAge)}}}return best}
 recallFlag(i,x,y,flag,tick,maxAge=DAY_MEMORY*3){const s=this.spatial.get(i);if(!s)return[];const out=[];for(let k=0;k<s.count;k++){if(s.tiles[k]<0||tick-s.seen[k]>maxAge||!(s.flags[k]&flag))continue;const tx=s.tiles[k]%MAP_W,ty=Math.floor(s.tiles[k]/MAP_W);out.push({x:tx+.5,y:ty+.5,d:Math.hypot(tx+.5-x,ty+.5-y),tile:s.tiles[k],seen:s.seen[k]})}return out.sort((a,b)=>a.d-b.d)}
 shareSpatial(from,to,rng,tick,capacity=200){const s=this.spatial.get(from);if(!s||!s.count)return null;const candidates=[];for(let k=0;k<s.count;k++)if(s.tiles[k]>=0&&(s.resource[k]||s.flags[k]))candidates.push(k);if(!candidates.length)return null;const k=rng.pick(candidates);this.observe(to,s.tiles[k],Math.min(tick,s.seen[k]),s.resource[k],s.flags[k],capacity);return{tile:s.tiles[k],resource:s.resource[k],flags:s.flags[k]}}
 reflect(i,tick){this.ensure(i);const recent=this.episodic.get(i).filter(m=>tick-m.tick<5000);const groups=new Map();for(const m of recent){const k=m.reflectionKey||m.type;if(!k)continue;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m)}for(const[k,a]of groups)if(a.length>=3){const val=a.reduce((s,m)=>s+(m.valence||0),0)/a.length;const text=val>=0?`Experiências repetidas com ${k} parecem confiáveis.`:`Experiências repetidas com ${k} parecem perigosas.`;const b=this.beliefs.get(i);const old=b.find(x=>x.key===k);if(old){old.valence=(old.valence+val)*.5;old.tick=tick;old.text=text}else{b.push({key:k,text,valence:val,tick});this.remember(i,{type:'reflexão',text:`Concluí: ${text}`,tick,valence:val,importance:.9})}}}
 dangerModifier(i,tag){this.ensure(i);const b=this.beliefs.get(i).find(x=>x.key===tag&&x.valence<0);return b?Math.max(.22,1+b.valence/12):1}
 compactDead(i){this.ensure(i);const top=(this.episodic.get(i)||[]).slice().sort((a,b)=>(b.importance||0)-(a.importance||0)).slice(0,5);this.episodic.set(i,top);this.semantic.set(i,[]);this.beliefs.set(i,(this.beliefs.get(i)||[]).slice(-3));this.relations.set(i,new Map());this.spatial.delete(i)}
 serialize(){const mapToArr=m=>Array.from(m,([k,v])=>[k,v instanceof Map?Array.from(v):v]);const spatial=Array.from(this.spatial,([i,s])=>[i,{capacity:s.capacity,count:s.count,cursor:s.cursor,tiles:Array.from(s.tiles.slice(0,s.count)),seen:Array.from(s.seen.slice(0,s.count)),resource:Array.from(s.resource.slice(0,s.count)),flags:Array.from(s.flags.slice(0,s.count))}]);return{episodic:mapToArr(this.episodic),semantic:mapToArr(this.semantic),beliefs:mapToArr(this.beliefs),relations:mapToArr(this.relations),spatial}}
 static hydrate(d){const s=new MemorySystem();for(const k of ['episodic','semantic','beliefs'])s[k]=new Map(d?.[k]||[]);s.relations=new Map((d?.relations||[]).map(([i,a])=>[i,new Map(a)]));for(const[i,x]of d?.spatial||[]){const q=makeSpatial(x.capacity||200);q.count=Math.min(x.count||x.tiles?.length||0,q.capacity);q.cursor=x.cursor||0;q.tiles.set((x.tiles||[]).slice(0,q.count));q.seen.set((x.seen||[]).slice(0,q.count));q.resource.set((x.resource||[]).slice(0,q.count));q.flags.set((x.flags||[]).slice(0,q.count));s.spatial.set(i,q)}return s}
}
export const SPATIAL_FLAG={DUNGEON:1,BUILDING:2,WATER:4,THREAT:8};
const DAY_MEMORY=840*45;
