import {MAP_W,MAP_H,GENE} from '../core/constants.js';
const DECAY=.998,EMPTY=-1,CHUNK=16,CW=Math.ceil(MAP_W/CHUNK),CH=Math.ceil(MAP_H/CHUNK),DAY_MEMORY=840*45;
function makeSpatial(capacity){const tiles=new Int32Array(capacity);tiles.fill(EMPTY);const source=new Int32Array(capacity);source.fill(-1);return{capacity,count:0,tiles,seen:new Uint32Array(capacity),resource:new Uint32Array(capacity),flags:new Uint16Array(capacity),quantity:new Float32Array(capacity),confidence:new Float32Array(capacity),source,coverage:new Uint8Array(CW*CH)}}
export class MemorySystem{
 constructor(){this.episodic=new Map();this.semantic=new Map();this.beliefs=new Map();this.relations=new Map();this.spatial=new Map()}
 ensure(i,capacity=200){if(!this.episodic.has(i))this.episodic.set(i,[]);if(!this.semantic.has(i))this.semantic.set(i,[]);if(!this.beliefs.has(i))this.beliefs.set(i,[]);if(!this.relations.has(i))this.relations.set(i,new Map());if(!this.spatial.has(i))this.spatial.set(i,makeSpatial(capacity))}
 spatialCapacity(npcs,i){if(npcs?.derived)return Math.max(150,Math.min(400,npcs.derived(i).memory));const g=npcs?.gene?.(i,GENE.MEMORY)??.5;return Math.round(150+g*250)}
 remember(i,event,capacity=200){this.ensure(i,capacity);const a=this.episodic.get(i);a.push({...event,accesses:0});if(a.length>capacity){a.sort((x,y)=>this.keep(y)-this.keep(x));a.length=capacity}}
 keep(m){return(m.importance||.5)*Math.pow(DECAY,Math.max(0,m.age||0))*(1+(m.accesses||0)*.05)}
 recall(i,context,k=5,tick=0){this.ensure(i);const words=new Set(String(context).toLowerCase().split(/\W+/)),a=this.episodic.get(i),scored=a.map(m=>{const text=(m.text+' '+(m.type||'')).toLowerCase();let rel=.2;for(const w of words)if(w&&text.includes(w))rel+=.2;const rec=Math.exp(-(tick-m.tick)/3500);return[m,rel*rec*(m.importance||.5)]}).sort((a,b)=>b[1]-a[1]).slice(0,k);for(const[m]of scored)m.accesses=(m.accesses||0)+1;return scored.map(x=>x[0])}
 relation(i,j){this.ensure(i);const m=this.relations.get(i);if(!m.has(j))m.set(j,{trust:0,affection:0,fear:0,respect:0,anger:0,debt:0,knowledgeDebt:0});return m.get(j)}
 adjust(i,j,delta){const r=this.relation(i,j);for(const[k,v]of Object.entries(delta))r[k]=Math.max(-1,Math.min(1,(r[k]||0)+v))}
 learn(i,fact){this.ensure(i);const a=this.semantic.get(i),old=a.find(x=>x.key===fact.key);if(old){old.confidence=Math.min(1,(old.confidence||.5)+.08);old.tick=fact.tick;old.text=fact.text||old.text;old.source=fact.source??old.source}else a.push({...fact,confidence:fact.confidence??.55})}
 markVisited(i,x,y,amount=16){this.ensure(i);const s=this.spatial.get(i),cx=Math.max(0,Math.min(CW-1,Math.floor(x/CHUNK))),cy=Math.max(0,Math.min(CH-1,Math.floor(y/CHUNK))),p=cy*CW+cx;s.coverage[p]=Math.min(255,s.coverage[p]+amount)}
 coverageRatio(i){const s=this.spatial.get(i);if(!s)return 0;let known=0;for(const v of s.coverage)if(v)known++;return known/s.coverage.length}
 frontierChunks(i){const s=this.spatial.get(i);if(!s)return[];const out=[];for(let cy=0;cy<CH;cy++)for(let cx=0;cx<CW;cx++){const p=cy*CW+cx;if(s.coverage[p])continue;let adj=0,fam=0;for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx<0||ny<0||nx>=CW||ny>=CH)continue;const v=s.coverage[ny*CW+nx];if(v){adj++;fam+=v}}if(adj)out.push({cx,cy,x:cx*CHUNK+CHUNK/2,y:cy*CHUNK+CHUNK/2,familiarity:fam/adj})}return out}
 observe(i,tileIndex,tick,resourceMask=0,flags=0,capacity=200,quantity=1,sourceUid=-1){this.ensure(i,capacity);let s=this.spatial.get(i);if(s.capacity!==capacity&&s.count===0){s=makeSpatial(capacity);this.spatial.set(i,s)}const tx=tileIndex%MAP_W,ty=Math.floor(tileIndex/MAP_W);this.markVisited(i,tx,ty,resourceMask||flags?7:2);if(!(resourceMask||flags))return;let slot=-1;for(let k=0;k<s.count;k++)if(s.tiles[k]===tileIndex&&s.resource[k]===resourceMask&&s.flags[k]===flags){slot=k;break}if(slot<0){if(s.count<s.capacity)slot=s.count++;else slot=this.evictSlot(s,tick)}if(slot<0)return;s.tiles[slot]=tileIndex;s.seen[slot]=tick;s.resource[slot]=resourceMask;s.flags[slot]=flags;s.quantity[slot]=Math.max(s.quantity[slot]*.4,quantity||1);s.confidence[slot]=1;s.source[slot]=sourceUid}
 evictSlot(s,tick){let slot=-1,worst=Infinity;for(let k=0;k<s.count;k++){const age=Math.max(0,tick-s.seen[k]),rec=Math.exp(-age/DAY_MEMORY),rel=1+(s.resource[k]?1.2:0)+(s.flags[k]?1.5:0),score=(s.confidence[k]||.2)*rel*rec;if(score<worst){worst=score;slot=k}}return slot}
 effectiveConfidence(s,k,tick,maxAge=DAY_MEMORY){const age=Math.max(0,tick-s.seen[k]);if(age>maxAge)return 0;return Math.max(.03,(s.confidence[k]||.4)*Math.exp(-age/maxAge*.9))}
 recallNearest(i,x,y,kind,tick,maxAge=DAY_MEMORY){const s=this.spatial.get(i);if(!s)return null;const bit=1<<kind;let best=null,score=-Infinity;for(let k=0;k<s.count;k++){if(s.tiles[k]<0||!(s.resource[k]&bit))continue;const conf=this.effectiveConfidence(s,k,tick,maxAge);if(conf<=0)continue;const tx=s.tiles[k]%MAP_W,ty=Math.floor(s.tiles[k]/MAP_W),d=Math.hypot(tx+.5-x,ty+.5-y),q=conf/(1+d*.05);if(q>score){score=q;best={x:tx+.5,y:ty+.5,d,tile:s.tiles[k],seen:s.seen[k],confidence:conf,quantity:s.quantity[k],sourceUid:s.source[k],slot:k}}}return best}
 recallFlag(i,x,y,flag,tick,maxAge=DAY_MEMORY*3){const s=this.spatial.get(i);if(!s)return[];const out=[];for(let k=0;k<s.count;k++){if(s.tiles[k]<0||!(s.flags[k]&flag))continue;const confidence=this.effectiveConfidence(s,k,tick,maxAge);if(!confidence)continue;const tx=s.tiles[k]%MAP_W,ty=Math.floor(s.tiles[k]/MAP_W);out.push({x:tx+.5,y:ty+.5,d:Math.hypot(tx+.5-x,ty+.5-y),tile:s.tiles[k],seen:s.seen[k],confidence,sourceUid:s.source[k],slot:k})}return out.sort((a,b)=>a.d-b.d)}
 invalidate(i,slot,tick,sourceIndex=-1){const s=this.spatial.get(i);if(!s||slot<0||slot>=s.count)return;s.confidence[slot]*=.18;s.seen[slot]=tick;if(sourceIndex>=0){this.adjust(i,sourceIndex,{trust:-.08,respect:-.025});this.remember(i,{type:'informação errada',text:'Segui uma informação, mas o lugar já não correspondia ao que me disseram.',tick,valence:-3,importance:.65,reflectionKey:`pessoa:${sourceIndex}`})}else this.remember(i,{type:'erro de memória',text:'Minha lembrança deste lugar estava errada ou desatualizada.',tick,valence:-2,importance:.5,reflectionKey:'memória espacial'})}
 shareSpatial(from,to,rng,tick,capacity=200){const s=this.spatial.get(from);if(!s||!s.count)return null;const candidates=[];for(let k=0;k<s.count;k++)if(s.tiles[k]>=0&&(s.resource[k]||s.flags[k])&&this.effectiveConfidence(s,k,tick)>.18)candidates.push(k);if(!candidates.length)return null;const k=rng.pick(candidates);this.observe(to,s.tiles[k],Math.min(tick,s.seen[k]),s.resource[k],s.flags[k],capacity,s.quantity[k],from);return{tile:s.tiles[k],resource:s.resource[k],flags:s.flags[k],source:from}}
 reflect(i,tick){this.ensure(i);const recent=this.episodic.get(i).filter(m=>tick-m.tick<5000),groups=new Map();for(const m of recent){const k=m.reflectionKey||m.type;if(!k)continue;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m)}for(const[k,a]of groups)if(a.length>=3){const val=a.reduce((s,m)=>s+(m.valence||0),0)/a.length,text=val>=0?`Experiências repetidas com ${k} parecem confiáveis.`:`Experiências repetidas com ${k} parecem perigosas.`,b=this.beliefs.get(i),old=b.find(x=>x.key===k);if(old){old.valence=(old.valence+val)*.5;old.tick=tick;old.text=text}else{b.push({key:k,text,valence:val,tick});this.remember(i,{type:'reflexão',text:`Concluí: ${text}`,tick,valence:val,importance:.9})}}}
 dangerModifier(i,tag){this.ensure(i);const b=this.beliefs.get(i).find(x=>x.key===tag&&x.valence<0);return b?Math.max(.22,1+b.valence/12):1}
 compactDead(i){this.ensure(i);const top=(this.episodic.get(i)||[]).slice().sort((a,b)=>(b.importance||0)-(a.importance||0)).slice(0,5);this.episodic.set(i,top);this.semantic.set(i,[]);this.beliefs.set(i,(this.beliefs.get(i)||[]).slice(-3));this.relations.set(i,new Map());this.spatial.delete(i)}
 serialize(){const mapToArr=m=>Array.from(m,([k,v])=>[k,v instanceof Map?Array.from(v):v]),spatial=Array.from(this.spatial,([i,s])=>[i,{capacity:s.capacity,count:s.count,tiles:Array.from(s.tiles.slice(0,s.count)),seen:Array.from(s.seen.slice(0,s.count)),resource:Array.from(s.resource.slice(0,s.count)),flags:Array.from(s.flags.slice(0,s.count)),quantity:Array.from(s.quantity.slice(0,s.count)),confidence:Array.from(s.confidence.slice(0,s.count)),source:Array.from(s.source.slice(0,s.count)),coverage:Array.from(s.coverage)}]);return{episodic:mapToArr(this.episodic),semantic:mapToArr(this.semantic),beliefs:mapToArr(this.beliefs),relations:mapToArr(this.relations),spatial}}
 static hydrate(d){const s=new MemorySystem();for(const k of['episodic','semantic','beliefs'])s[k]=new Map(d?.[k]||[]);s.relations=new Map((d?.relations||[]).map(([i,a])=>[i,new Map(a)]));for(const[i,x]of d?.spatial||[]){const q=makeSpatial(x.capacity||200);q.count=Math.min(x.count||x.tiles?.length||0,q.capacity);q.tiles.set((x.tiles||[]).slice(0,q.count));q.seen.set((x.seen||[]).slice(0,q.count));q.resource.set((x.resource||[]).slice(0,q.count));q.flags.set((x.flags||[]).slice(0,q.count));q.quantity.set((x.quantity||[]).slice(0,q.count));q.confidence.set((x.confidence||Array(q.count).fill(.7)).slice(0,q.count));q.source.set((x.source||Array(q.count).fill(-1)).slice(0,q.count));q.coverage.set((x.coverage||[]).slice(0,q.coverage.length));s.spatial.set(i,q)}return s}
}
export const SPATIAL_FLAG={DUNGEON:1,BUILDING:2,WATER:4,THREAT:8,SMOKE:16,HUMAN:32,FIRE:64};
