import {ACTION,RESOURCE,BUILDING,TOOL,TRAVEL_ACTIONS,TILE_TYPE} from '../core/constants.js';
import {knownResource,knownDungeons} from '../ai/perception.js';
const skillFor={ [ACTION.WOOD]:1,[ACTION.STONE]:0,[ACTION.IRON]:0,[ACTION.FARM]:2,[ACTION.HUNT]:3,[ACTION.FISH]:4,[ACTION.COOK]:5,[ACTION.BUILD]:6,[ACTION.FORGE]:7,[ACTION.TAILOR]:9,[ACTION.FIGHT]:10,[ACTION.DUNGEON]:10,[ACTION.CARE]:12,[ACTION.SOCIAL]:13 };
const toolFor={ [ACTION.WOOD]:TOOL.AXE,[ACTION.STONE]:TOOL.PICK,[ACTION.IRON]:TOOL.PICK,[ACTION.BUILD]:TOOL.HAMMER,[ACTION.FISH]:TOOL.ROD,[ACTION.HUNT]:TOOL.BOW,[ACTION.FIGHT]:TOOL.SWORD,[ACTION.COOK]:TOOL.KNIFE };
export function prepareAction(sim,i,action,perception){const n=sim.npcs,w=sim.world;equip(sim,i,toolFor[action]);const intent={action,started:sim.tick,targetX:n.x[i],targetY:n.y[i],sourceX:n.x[i],sourceY:n.y[i],targetId:-1,targetKind:null,required:1,meta:{}};n.action[i]=action;n.progress[i]=0;n.route[i]=[];n.routeIndex[i]=0;
 if(action===ACTION.RETURN){intent.targetX=w.settlement.x;intent.targetY=w.settlement.y;intent.required=.1}
 else if([ACTION.FORAGE,ACTION.WATER,ACTION.WOOD,ACTION.STONE,ACTION.IRON,ACTION.FISH].includes(action)){const kind=action===ACTION.FORAGE?RESOURCE.BERRY:action===ACTION.WATER?RESOURCE.WATER:action===ACTION.WOOD?RESOURCE.LOG:action===ACTION.STONE?RESOURCE.STONE:action===ACTION.IRON?RESOURCE.IRON:RESOURCE.FISH;const k=knownResource(sim,i,kind);if(!k)return false;intent.sourceX=k.x;intent.sourceY=k.y;intent.targetKind=kind;const a=approach(w,k.x,k.y);intent.targetX=a.x;intent.targetY=a.y;intent.required=action===ACTION.WATER?.18:action===ACTION.FISH?1.2:action===ACTION.WOOD?1.45:1.15}
 else if(action===ACTION.HUNT){const prey=sim.animals.nearestPrey(n.x[i],n.y[i],perception.radius);if(!prey)return false;intent.targetId=prey.id;intent.targetX=prey.x;intent.targetY=prey.y;intent.required=.75}
 else if(action===ACTION.SOCIAL){const j=sim.nearestVisibleNPC(i,perception.radius);if(j<0)return false;intent.targetId=j;intent.targetX=n.x[j];intent.targetY=n.y[j];intent.required=.55}
 else if(action===ACTION.CARE){const j=sim.nearestWounded(i,perception.radius);if(j<0)return false;intent.targetId=j;intent.targetX=n.x[j];intent.targetY=n.y[j];intent.required=.8}
 else if(action===ACTION.FIGHT){if(!perception.target)return false;intent.meta.targetType=perception.target.kind;intent.targetId=perception.target.kind==='animal'?perception.target.ref.id:perception.target.ref.id;intent.targetX=perception.target.x;intent.targetY=perception.target.y;intent.required=.25}
 else if(action===ACTION.FLEE){const t=perception.target;if(!t)return false;const dx=n.x[i]-t.x,dy=n.y[i]-t.y,d=Math.hypot(dx,dy)||1;const q=passablePoint(w,n.x[i]+dx/d*7,n.y[i]+dy/d*7);intent.targetX=q.x;intent.targetY=q.y;intent.required=.1}
 else if(action===ACTION.SLEEP){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.SHELTER,14);if(b){intent.targetX=b.x;intent.targetY=b.y}intent.required=1}
 else if(action===ACTION.WARM){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.CAMPFIRE,14)||w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.SHELTER,14);if(b){intent.targetX=b.x;intent.targetY=b.y}intent.required=.7}
 else if(action===ACTION.FARM){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.FARM,14);if(!b)return false;intent.targetX=b.x;intent.targetY=b.y;intent.targetId=b.id;intent.required=1.4}
 else if(action===ACTION.FORGE){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.FORGE,14);if(!b)return false;intent.targetX=b.x;intent.targetY=b.y;intent.required=1.2}
 else if(action===ACTION.COOK){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.CAMPFIRE,14);if(!b)return false;intent.targetX=b.x;intent.targetY=b.y;intent.required=.9}
 else if(action===ACTION.TAILOR){const b=w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.WORKSHOP,14)||w.nearestBuildingLocal(n.x[i],n.y[i],BUILDING.STORAGE,14);if(b){intent.targetX=b.x;intent.targetY=b.y}intent.required=1.1}
 else if(action===ACTION.BUILD){let x=w.nextBlueprintPiece();if(!x){const type=nextBuildingType(sim);const pos=buildSpot(sim);w.createBlueprint(type,pos.x,pos.y);x=w.nextBlueprintPiece()}if(!x)return false;intent.meta.blueprint=x.bp.id;intent.meta.pieceIndex=x.bp.pieces.indexOf(x.piece);intent.targetX=x.piece.x;intent.targetY=x.piece.y;intent.required=1.1}
 else if(action===ACTION.EXPLORE){const q=exploreTarget(sim,i);intent.targetX=q.x;intent.targetY=q.y;intent.required=.1}
 else if(action===ACTION.DUNGEON){const site=sim.dungeon.nearestKnownSite(sim,i);if(!site||w.stock[RESOURCE.WATER]<.35)return false;intent.targetId=site.id;const q=approach(w,site.x,site.y);intent.targetX=q.x;intent.targetY=q.y;intent.sourceX=site.x;intent.sourceY=site.y;intent.required=1.6;w.stock[RESOURCE.WATER]-=.35;n.inventory[i][RESOURCE.WATER]+=.35;for(let qn=0;qn<2;qn++){const food=w.consumeFood(sim.tick);if(food)n.inventory[i][food.kind]+=food.amount}}
 else if(action===ACTION.EAT||action===ACTION.DRINK||action===ACTION.IDLE){intent.required=.05}
 n.intent[i]=intent;if(TRAVEL_ACTIONS.has(action))sim.travel.started++,sim.travel.byAction[action]=(sim.travel.byAction[action]||0)+1;sim.actionHistogram[action]=(sim.actionHistogram[action]||0)+1;return true}
export function finishIntent(sim,i,success=true){const n=sim.npcs,int=n.intent[i];if(int&&TRAVEL_ACTIONS.has(int.action)){if(success){sim.travel.completed++;sim.travel.completedByAction[int.action]=(sim.travel.completedByAction[int.action]||0)+1}else{sim.travel.abandoned++;sim.travel.abandonedByAction[int.action]=(sim.travel.abandonedByAction[int.action]||0)+1}}n.intent[i]=null;n.progress[i]=0;n.route[i]=[];n.routeIndex[i]=0;if(n.alive[i])n.action[i]='observar'}
export function abortIntent(sim,i,reason='interrompido'){const int=sim.npcs.intent[i];if(int){sim.memory.remember(i,{type:'interrupção',text:`Interrompi ${int.action}: ${reason}.`,tick:sim.tick,valence:-1,importance:.28,reflectionKey:'interrupção'});finishIntent(sim,i,false)}}
export function actionSkill(action){return skillFor[action]}
function equip(sim,i,tool){if(!tool)return;const n=sim.npcs,w=sim.world;if(n.tool[i]===tool)return;if(w.tools[tool]>0){if(n.tool[i])w.tools[n.tool[i]]++;w.tools[tool]--;n.tool[i]=tool}}
function passablePoint(w,x,y){x=Math.max(1,Math.min(78,x));y=Math.max(1,Math.min(78,y));if(w.tile(x,y)!==TILE_TYPE.WATER&&w.tile(x,y)!==TILE_TYPE.MOUNTAIN)return{x,y};for(let r=1;r<5;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const nx=Math.floor(x)+dx+.5,ny=Math.floor(y)+dy+.5,t=w.tile(nx,ny);if(t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN)return{x:nx,y:ny}}return{x:w.settlement.x,y:w.settlement.y}}
function approach(w,x,y){const t=w.tile(x,y);if(t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN)return{x,y};for(let r=1;r<=2;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const nx=Math.floor(x)+dx+.5,ny=Math.floor(y)+dy+.5,tt=w.tile(nx,ny);if(tt!==TILE_TYPE.WATER&&tt!==TILE_TYPE.MOUNTAIN)return{x:nx,y:ny}}return{x:w.settlement.x,y:w.settlement.y}}
function exploreTarget(sim,i){const n=sim.npcs,w=sim.world,m=sim.memory,s=m.spatial.get(i);for(let tries=0;tries<24;tries++){const a=sim.rng.range(0,Math.PI*2),d=sim.rng.range(7,16),x=n.x[i]+Math.cos(a)*d,y=n.y[i]+Math.sin(a)*d;if(!w.inside(x,y))continue;const t=w.idx(x,y);let known=false;if(s)for(let k=0;k<s.count;k++)if(s.tiles[k]===t){known=true;break}if(!known)return passablePoint(w,x,y)}const a=sim.rng.range(0,Math.PI*2);return passablePoint(w,n.x[i]+Math.cos(a)*10,n.y[i]+Math.sin(a)*10)}
function nextBuildingType(sim){const w=sim.world;if(!w.buildings.some(b=>b.type===BUILDING.FARM))return BUILDING.FARM;if(!w.buildings.some(b=>b.type===BUILDING.FORGE))return BUILDING.FORGE;if(!w.buildings.some(b=>b.type===BUILDING.WORKSHOP))return BUILDING.WORKSHOP;if(!w.buildings.some(b=>b.type===BUILDING.COOP))return BUILDING.COOP;return BUILDING.SHELTER}
function buildSpot(sim){const w=sim.world;for(let k=0;k<30;k++){const a=sim.rng.range(0,Math.PI*2),d=sim.rng.range(5,12),x=Math.round(w.settlement.x+Math.cos(a)*d),y=Math.round(w.settlement.y+Math.sin(a)*d);if(w.tile(x,y)===TILE_TYPE.GRASS||w.tile(x,y)===TILE_TYPE.TRAIL)return{x,y}}return{x:Math.round(w.settlement.x+6),y:Math.round(w.settlement.y+6)}}
