import {ACTION,RESOURCE,NEED,BUILDING,GENE} from '../core/constants.js';
const skillFor={ [ACTION.WOOD]:1,[ACTION.STONE]:0,[ACTION.IRON]:0,[ACTION.FARM]:2,[ACTION.BUILD]:6,[ACTION.FIGHT]:10,[ACTION.DUNGEON]:10 };
function moveToward(n,i,x,y,speed=.34){const dx=x-n.x[i],dy=y-n.y[i],d=Math.hypot(dx,dy);if(d<.45)return true;n.x[i]+=dx/d*Math.min(speed,d);n.y[i]+=dy/d*Math.min(speed,d);return false}
function remember(sim,i,type,text,valence=0,importance=.45,key=type){sim.memory.remember(i,{type,text,valence,importance,reflectionKey:key,tick:sim.tick})}
export function executeAction(sim,i,action){const n=sim.npcs,w=sim.world,inv=n.inventory[i],skill=skillFor[action];n.action[i]=action;if(skill!=null)n.addSkill(i,skill,.0008);
 if(action===ACTION.EAT){if(inv[RESOURCE.FOOD]>.1||w.stock[RESOURCE.FOOD]>.12){if(inv[RESOURCE.FOOD]>.1)inv[RESOURCE.FOOD]-=.12;else w.stock[RESOURCE.FOOD]-=.12;n.setNeed(i,NEED.HUNGER,n.need(i,NEED.HUNGER)-.42);n.hp[i]=Math.min(1,n.hp[i]+.01)}else n.action[i]=ACTION.FORAGE;return}
 if(action===ACTION.DRINK){if(inv[RESOURCE.WATER]>.08||w.stock[RESOURCE.WATER]>.1){if(inv[RESOURCE.WATER]>.08)inv[RESOURCE.WATER]-=.1;else w.stock[RESOURCE.WATER]-=.1;n.setNeed(i,NEED.THIRST,n.need(i,NEED.THIRST)-.6)}else n.action[i]=ACTION.WATER;return}
 if(action===ACTION.WARM){const b=w.nearestBuilding(n.x[i],n.y[i],BUILDING.SHELTER);if(b&&moveToward(n,i,b.x,b.y,.34))n.setNeed(i,NEED.TEMP,n.need(i,NEED.TEMP)-.09);return}
 if(action===ACTION.SLEEP){n.setNeed(i,NEED.SLEEP,n.need(i,NEED.SLEEP)-.07);n.stamina[i]=Math.min(1,n.stamina[i]+.04);if(n.need(i,NEED.HUNGER)<.7&&n.need(i,NEED.THIRST)<.7)n.hp[i]=Math.min(1,n.hp[i]+.006);return}
 if(action===ACTION.SOCIAL){return socialize(sim,i)}
 if(action===ACTION.BUILD){return build(sim,i)}
 if(action===ACTION.EXPLORE){const a=sim.rng.range(0,Math.PI*2);n.x[i]=Math.max(2,Math.min(69,n.x[i]+Math.cos(a)*.45));n.y[i]=Math.max(2,Math.min(69,n.y[i]+Math.sin(a)*.45));if(sim.rng.chance(.01))remember(sim,i,'descoberta','Encontrei um caminho que ainda não conhecia.',2,.55,'exploração');return}
 if(action===ACTION.FIGHT){return fightNearby(sim,i)}
 if(action===ACTION.DUNGEON){return sim.dungeon.attempt(sim,i)}
 const kind=action===ACTION.FORAGE?RESOURCE.FOOD:action===ACTION.WATER?RESOURCE.WATER:action===ACTION.WOOD?RESOURCE.WOOD:action===ACTION.STONE?RESOURCE.STONE:action===ACTION.IRON?RESOURCE.IRON:action===ACTION.FARM?RESOURCE.WHEAT:null;
 if(kind!=null){let target=w.nearestResource(n.x[i],n.y[i],kind);if(action===ACTION.FARM&&!target){const farm=w.buildings.find(b=>b.type===BUILDING.FARM);if(farm)target={x:farm.x,y:farm.y,d:Math.hypot(farm.x-n.x[i],farm.y-n.y[i]),ref:null}}if(!target){n.action[i]='procurando recurso';return}if(moveToward(n,i,target.x,target.y,.25+n.gene(i,GENE.SPEED)*.12)){
   let amount=.05+n.skill(i,skill??0)*.1;if(kind===RESOURCE.WATER)amount=.2;const got=target.ref?w.harvest(target.ref,amount):amount;const out=kind===RESOURCE.WHEAT?RESOURCE.FOOD:kind;inv[out]+=got;if(out===RESOURCE.FOOD&&inv[out]>.7){const deposit=inv[out]-.45;w.stock[out]+=deposit;inv[out]-=deposit}if(out===RESOURCE.WATER&&inv[out]>.7){w.stock[out]+=inv[out]-.45;inv[out]=.45}if(sim.rng.chance(.006))remember(sim,i,'trabalho',`Trabalhei com ${action} e fiquei melhor nisso.`,1,.35,action)
  }return}
}
function socialize(sim,i){const n=sim.npcs,j=sim.nearestNPC(i);if(j<0)return;if(!moveToward(n,i,n.x[j],n.y[j],.3))return;n.setNeed(i,NEED.SOCIAL,n.need(i,NEED.SOCIAL)-.35);n.setNeed(j,NEED.SOCIAL,n.need(j,NEED.SOCIAL)-.18);const warmth=.01+n.gene(i,GENE.EMPATHY)*.015;sim.memory.adjust(i,j,{affection:warmth,trust:warmth*.6});sim.memory.adjust(j,i,{affection:warmth*.7,trust:warmth*.4});const facts=sim.memory.semantic.get(i)||[];if(facts.length&&sim.rng.chance(.2))sim.memory.learn(j,{...sim.rng.pick(facts),tick:sim.tick});for(let sk=0;sk<14;sk++)if(n.skill(i,sk)-n.skill(j,sk)>.12&&sim.rng.chance(.06))n.addSkill(j,sk,.0015);if(sim.rng.chance(.04)){remember(sim,i,'conversa',`Conversei com ${n.names[j]}.`,2,.4,`pessoa:${j}`);remember(sim,j,'conversa',`${n.names[i]} veio conversar comigo.`,2,.4,`pessoa:${i}`)}}
function build(sim,i){const n=sim.npcs,w=sim.world;if(w.stock[RESOURCE.WOOD]<4||w.stock[RESOURCE.STONE]<2){n.action[i]='faltam materiais para construir';return}let type=BUILDING.SHELTER;if(!w.buildings.some(b=>b.type===BUILDING.FARM))type=BUILDING.FARM;else if(!w.buildings.some(b=>b.type===BUILDING.FORGE)&&w.stock[RESOURCE.IRON]>=2)type=BUILDING.FORGE;else if(!w.buildings.some(b=>b.type===BUILDING.STORAGE))type=BUILDING.STORAGE;const cx=36,cy=36,x=Math.round(cx+sim.rng.range(-7,7)),y=Math.round(cy+sim.rng.range(-7,7));w.stock[RESOURCE.WOOD]-=4;w.stock[RESOURCE.STONE]-=2;if(type===BUILDING.FORGE)w.stock[RESOURCE.IRON]-=2;w.buildings.push({type,x,y,hp:1});sim.log('construção',`${n.names[i]} concluiu ${['um abrigo','uma fazenda','uma forja','um armazém'][type]}.`,.75,i);remember(sim,i,'construção','Construí algo útil para a comunidade.',4,.75,'comunidade')}
function fightNearby(sim,i){const n=sim.npcs,w=sim.world;let target=null,d=99;for(const m of w.monsters)if(m.hp>0){const dd=Math.hypot(m.x-n.x[i],m.y-n.y[i]);if(dd<d){d=dd;target=m}}if(!target){n.action[i]='patrulhando';return}if(!moveToward(n,i,target.x,target.y,.35))return;const damage=.06+n.derived(i).strength*.07+n.skill(i,10)*.08;target.hp-=damage;if(target.hp<=0){n.prestige[i]+=3;n.addSkill(i,10,.02);sim.log('combate',`${n.names[i]} matou uma criatura que ameaçava a vila.`,.85,i);remember(sim,i,'combate','Matei uma criatura em combate.',5,.8,'monstros')}else if(sim.rng.chance(.22)){const hit=.012+target.power*.018;n.hp[i]-=hit;remember(sim,i,'ferimento','Fui ferido por uma criatura.',-5,.75,'monstros')}}
