import {ANIMAL,ANIMAL_INFO,ANIMAL_STATE,MAX_ANIMALS,BIOME,RESOURCE,MAP_W,MAP_H,TILE_TYPE,BUILDING,ACTION,DAY_TICKS} from '../core/constants.js';
import {isNight,isDusk,season} from '../core/clock.js';
import {technologyFor} from './technology.js';
import {infect} from './disease.js';

const REGION=16,RW=Math.ceil(MAP_W/REGION),RH=Math.ceil(MAP_H/REGION),SPECIES=ANIMAL.NAMES.length;
const WILD_TARGET={
 [ANIMAL.RABBIT]:125,[ANIMAL.HARE]:70,[ANIMAL.BIRD]:115,[ANIMAL.DEER]:85,[ANIMAL.BOAR]:50,[ANIMAL.MOOSE]:22,
 [ANIMAL.WOLF]:28,[ANIMAL.BEAR]:10,[ANIMAL.FELINE]:14,[ANIMAL.CHICKEN]:28,[ANIMAL.GOAT]:24,[ANIMAL.SHEEP]:20,[ANIMAL.PIG]:20,[ANIMAL.CATTLE]:10
};
const STATE_BY_NAME=new Map([['pastar',ANIMAL_STATE.GRAZE],['beber',ANIMAL_STATE.DRINK],['vigiar',ANIMAL_STATE.WATCH],['fugir',ANIMAL_STATE.FLEE],['caçar',ANIMAL_STATE.HUNT],['caçar humano',ANIMAL_STATE.HUNT],['descansar',ANIMAL_STATE.REST],['acasalar',ANIMAL_STATE.MATE]]);
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));

export class AnimalSystem{
 constructor(rng,world,{skipSpawn=false}={}){
  this.rng=rng;this.world=world;this.capacity=MAX_ANIMALS;this.count=0;this.nextId=1;this._views=[];
  const n=this.capacity;
  this.id=new Int32Array(n);this.species=new Uint8Array(n);this.x=new Float32Array(n);this.y=new Float32Array(n);this.prevX=new Float32Array(n);this.prevY=new Float32Array(n);
  this.state=new Uint8Array(n);this.target=new Int32Array(n);this.target.fill(-1);this.age=new Float32Array(n);this.hp=new Float32Array(n);this.fear=new Float32Array(n);this.satiety=new Float32Array(n);
  this.herd=new Int32Array(n);this.tameness=new Float32Array(n);this.sex=new Uint8Array(n);this.alive=new Uint8Array(n);this.domestic=new Uint8Array(n);this.captive=new Uint8Array(n);
  this.power=new Float32Array(n);this.hunger=new Float32Array(n);this.mateCooldown=new Int32Array(n);this.productCooldown=new Int32Array(n);this.birthTick=new Uint32Array(n);
  this.regionPop=new Float32Array(RW*RH*SPECIES);this.birthCredit=new Float32Array(this.regionPop.length);this.refugeCredit=new Float32Array(this.regionPop.length);
  this.traps=[];this.metrics={births:0,naturalDeaths:0,predationDeaths:0,hunted:0,domesticated:0,zoonosisExposures:0,trapCatches:0,nightAttacks:0};
  this.lastViewX=world.settlement?.x??MAP_W/2;this.lastViewY=world.settlement?.y??MAP_H/2;
  if(!skipSpawn)this.spawnInitial(world);
 }
 get items(){const out=[];for(let i=0;i<this.count;i++)if(this.alive[i])out.push(this.view(i));return out}
 view(i){if(!this._views[i])this._views[i]=makeView(this,i);return this._views[i]}
 livingIndices(){const out=[];for(let i=0;i<this.count;i++)if(this.alive[i])out.push(i);return out}
 liveCount(){let n=0;for(let i=0;i<this.count;i++)n+=this.alive[i];return n}
 spawnInitial(w){for(const [key,target] of Object.entries(WILD_TARGET)){const s=Number(key);for(let k=0;k<target&&this.liveCount()<MAX_ANIMALS;k++){const p=this.suitablePoint(s,w);if(p)this.spawn(s,p.x,p.y,false,{herd:this.herdFor(s,p.x,p.y),tameness:this.rng.range(.02,.24)})}}this.recountRegional()}
 suitablePoint(species,w,rx=null,ry=null){const info=ANIMAL_INFO[species];for(let tries=0;tries<80;tries++){const x=rx==null?this.rng.range(2,MAP_W-2):this.rng.range(rx*REGION+1,Math.min(MAP_W-1,(rx+1)*REGION-1)),y=ry==null?this.rng.range(2,MAP_H-2):this.rng.range(ry*REGION+1,Math.min(MAP_H-1,(ry+1)*REGION-1)),b=w.biome(x,y),t=w.tile(x,y);if(t===TILE_TYPE.WATER||t===TILE_TYPE.MOUNTAIN)continue;if(info.biomes?.includes(b))return{x,y}}return null}
 spawn(species,x,y,domestic=false,opts={}){if(this.liveCount()>=MAX_ANIMALS)return null;let i=-1;for(let q=0;q<this.count;q++)if(!this.alive[q]){i=q;break}if(i<0){if(this.count>=this.capacity)return null;i=this.count++}const info=ANIMAL_INFO[species]||ANIMAL_INFO[ANIMAL.RABBIT];this.id[i]=opts.id??this.nextId++;this.species[i]=species;this.x[i]=this.prevX[i]=x;this.y[i]=this.prevY[i]=y;this.state[i]=ANIMAL_STATE.GRAZE;this.target[i]=-1;this.age[i]=opts.age??this.rng.range(.4,6);this.hp[i]=opts.hp??info.hp;this.fear[i]=opts.fear??0;this.satiety[i]=opts.satiety??this.rng.range(.45,.9);this.herd[i]=opts.herd??this.herdFor(species,x,y);this.tameness[i]=clamp(opts.tameness??(domestic?.75:this.rng.range(.02,.2)));this.sex[i]=opts.sex??this.rng.int(0,1);this.alive[i]=1;this.domestic[i]=domestic?1:0;this.captive[i]=opts.captive?1:0;this.power[i]=opts.power??info.power??.05;this.hunger[i]=opts.hunger??this.rng.range(0,.35);this.mateCooldown[i]=opts.mateCooldown??this.rng.int(0,DAY_TICKS*4);this.productCooldown[i]=opts.productCooldown??this.rng.int(0,DAY_TICKS);this.birthTick[i]=opts.birthTick??0;return this.view(i)}
 herdFor(species,x,y){return ((Math.floor(y/REGION)*RW+Math.floor(x/REGION))*SPECIES+species)+1}
 byId(id){for(let i=0;i<this.count;i++)if(this.alive[i]&&this.id[i]===id)return this.view(i);return null}
 indexById(id){for(let i=0;i<this.count;i++)if(this.alive[i]&&this.id[i]===id)return i;return-1}
 nearestPrey(x,y,rad=8,opts={}){let best=-1,bd=rad;for(let i=0;i<this.count;i++){if(!this.alive[i]||this.domestic[i]||ANIMAL_INFO[this.species[i]]?.predator)continue;const info=ANIMAL_INFO[this.species[i]],d=Math.hypot(this.x[i]-x,this.y[i]-y);if(opts.smallOnly&&!info.small)continue;if(d<bd){bd=d;best=i}}return best>=0?this.view(best):null}
 step(sim){this.lastViewX=sim.viewX??this.lastViewX;this.lastViewY=sim.viewY??this.lastViewY;if(sim.tick%60===0)this.fireTick(sim);if(sim.tick%120===0){this.trapTick(sim);this.zoonosisTick(sim)}if(sim.tick%DAY_TICKS===0)this.regionalTick(sim);for(let i=0;i<this.count;i++){if(!this.alive[i])continue;const dcam=Math.hypot(this.x[i]-this.lastViewX,this.y[i]-this.lastViewY),stride=dcam<24?1:dcam<72?8:32;if(sim.tick%stride!==i%stride)continue;this.individualTick(sim,i,stride)}}
 individualTick(sim,i,dt){const info=ANIMAL_INFO[this.species[i]];if(!info)return;this.prevX[i]=this.x[i];this.prevY[i]=this.y[i];this.age[i]+=dt/(DAY_TICKS*120);this.hunger[i]=clamp(this.hunger[i]+.00016*dt);this.satiety[i]=clamp(this.satiety[i]-.00014*dt);this.mateCooldown[i]=Math.max(0,this.mateCooldown[i]-dt);this.productCooldown[i]=Math.max(0,this.productCooldown[i]-dt);
  const human=this.detectHuman(sim,i),night=isNight(sim.tick),fire=this.nearLitFire(sim.world,this.x[i],this.y[i],info.predator?7:3.5);
  if(this.domestic[i]||this.captive[i]){this.state[i]=night?ANIMAL_STATE.REST:ANIMAL_STATE.GRAZE;const pen=this.nearestPen(sim.world,this.x[i],this.y[i]);if(pen&&Math.hypot(this.x[i]-pen.x,this.y[i]-pen.y)>4)this.moveToward(i,pen.x,pen.y,(info.speed||.1)*.28*dt,sim.world);else if(this.rng.chance(.02*dt))this.wander(i,sim.world,(info.speed||.1)*.2*dt);this.satiety[i]=clamp(this.satiety[i]+.0003*dt);return}
  if(info.predator){if(fire){this.state[i]=ANIMAL_STATE.FLEE;const dx=this.x[i]-fire.x,dy=this.y[i]-fire.y,d=Math.hypot(dx,dy)||1;this.moveToward(i,this.x[i]+dx/d*6,this.y[i]+dy/d*6,info.speed*1.05*dt,sim.world);return}const prey=this.nearestAnimalPrey(i,night?12:9);if(prey>=0&&this.hunger[i]>.28){this.state[i]=ANIMAL_STATE.HUNT;this.moveToward(i,this.x[prey],this.y[prey],info.speed*.78*dt,sim.world);this.target[i]=this.id[prey]}else if(human>=0&&night&&this.hunger[i]>.58){const hd=Math.hypot(sim.npcs.x[human]-this.x[i],sim.npcs.y[human]-this.y[i]),isolated=this.humansNear(sim,human,3)<=2;if(isolated){this.state[i]=ANIMAL_STATE.HUNT;this.moveToward(i,sim.npcs.x[human],sim.npcs.y[human],info.speed*.72*dt,sim.world);if(hd<.85&&this.rng.chance(.018*dt))this.attackHuman(sim,i,human)}}else{this.state[i]=night?ANIMAL_STATE.WATCH:ANIMAL_STATE.REST;if(this.rng.chance(.018*dt))this.wander(i,sim.world,info.speed*.28*dt)}}else{const predator=this.nearestPredator(i,7);if(predator>=0||human>=0){this.state[i]=ANIMAL_STATE.FLEE;const tx=predator>=0?this.x[predator]:sim.npcs.x[human],ty=predator>=0?this.y[predator]:sim.npcs.y[human],dx=this.x[i]-tx,dy=this.y[i]-ty,d=Math.hypot(dx,dy)||1;this.fear[i]=clamp(this.fear[i]+.08*dt);this.moveToward(i,this.x[i]+dx/d*6,this.y[i]+dy/d*6,info.speed*1.05*dt,sim.world);if(human>=0&&info.dangerous&&this.hp[i]<info.hp*.7&&Math.hypot(tx-this.x[i],ty-this.y[i])<1.1&&this.rng.chance(.02*dt))this.attackHuman(sim,i,human)}else{this.fear[i]=Math.max(0,this.fear[i]-.005*dt);this.state[i]=this.hunger[i]>.7?ANIMAL_STATE.GRAZE:ANIMAL_STATE.WATCH;if(this.rng.chance(.022*dt))this.wander(i,sim.world,info.speed*.25*dt);this.hunger[i]=Math.max(0,this.hunger[i]-.00035*dt);this.satiety[i]=clamp(this.satiety[i]+.0003*dt)}}if(this.hp[i]<=0)this.killIndex(i,'ferimento')}
 detectHuman(sim,i){const n=sim.npcs,info=ANIMAL_INFO[this.species[i]],wind=sim.world.wind||{dx:1,dy:0};let best=-1,bd=Infinity;for(const j of n.living()){const dx=this.x[i]-n.x[j],dy=this.y[i]-n.y[j],d=Math.hypot(dx,dy);if(d>14)continue;const downwind=d?Math.max(0,(dx*wind.dx+dy*wind.dy)/d):1,noise=n.moving[j]?.9:[ACTION.WOOD,ACTION.FIGHT,ACTION.SOCIAL].includes(n.action[j])?.8:.15,range=2.4+(info.hearing||.5)*4*noise+(info.smell||.5)*6*downwind;if(d<=range&&d<bd){bd=d;best=j}}return best}
 nearestAnimalPrey(i,rad){let best=-1,bd=rad;for(let j=0;j<this.count;j++){if(j===i||!this.alive[j]||this.domestic[j]||ANIMAL_INFO[this.species[j]]?.predator)continue;const d=Math.hypot(this.x[i]-this.x[j],this.y[i]-this.y[j]);if(d<bd){bd=d;best=j}}return best}
 nearestPredator(i,rad){let best=-1,bd=rad;for(let j=0;j<this.count;j++){if(j===i||!this.alive[j]||!ANIMAL_INFO[this.species[j]]?.predator)continue;const d=Math.hypot(this.x[i]-this.x[j],this.y[i]-this.y[j]);if(d<bd){bd=d;best=j}}return best}
 humansNear(sim,i,rad){let c=0;for(const j of sim.npcs.living())if(Math.hypot(sim.npcs.x[j]-sim.npcs.x[i],sim.npcs.y[j]-sim.npcs.y[i])<=rad)c++;return c}
 attackHuman(sim,i,human){const n=sim.npcs,info=ANIMAL_INFO[this.species[i]],p=this.power[i]||info.power||.1;n.wound[human]=Math.min(1,n.wound[human]+.025+p*.055);n.pain[human]=Math.min(1,n.pain[human]+.04+p*.04);n.hp[human]-=.002+p*.009;this.metrics.nightAttacks+=isNight(sim.tick)?1:0;sim.memory.remember(human,{type:'animal',text:`Fui atacado por ${ANIMAL.NAMES[this.species[i]]}.`,tick:sim.tick,valence:-7,importance:.82,reflectionKey:'predadores'});sim.senses?.emitSound?.(n.x[human],n.y[human],18,'grito',human,sim.tick)}
 nearLitFire(w,x,y,rad=7){let best=null,bd=rad;for(const b of w.buildings)if(b.finished&&b.type===BUILDING.CAMPFIRE&&b.lit){const d=Math.hypot(b.x-x,b.y-y);if(d<bd){bd=d;best=b}}return best}
 nearestPen(w,x,y){return w.nearestBuildingLocal?.(x,y,BUILDING.COOP,10)?.ref||w.nearestBuildingLocal?.(x,y,BUILDING.SHELTER,8)?.ref||null}
 moveToward(i,x,y,speed,w){const dx=x-this.x[i],dy=y-this.y[i],d=Math.hypot(dx,dy);if(d<.05)return;const step=Math.min(Math.max(.01,speed),Math.max(.02,d)),nx=this.x[i]+dx/d*step,ny=this.y[i]+dy/d*step,t=w.tile(nx,ny);if(w.inside(nx,ny)&&t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN){this.x[i]=nx;this.y[i]=ny}}
 wander(i,w,speed){const ang=this.rng.range(0,Math.PI*2),nx=this.x[i]+Math.cos(ang)*speed,ny=this.y[i]+Math.sin(ang)*speed,t=w.tile(nx,ny);if(w.inside(nx,ny)&&t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN){this.x[i]=nx;this.y[i]=ny}}
 fireTick(sim){const w=sim.world,n=sim.npcs,active=isNight(sim.tick)||isDusk(sim.tick);for(const b of w.buildings){if(!b.finished||b.type!==BUILDING.CAMPFIRE)continue;b.fuel=Math.max(0,(b.fuel||0)-60);if(!active){b.lit=false;continue}if(b.fuel<=0){let fueled=false,owner=n.indexByUid?.(b.owner)??-1;if(owner>=0&&n.inventory[owner][RESOURCE.LOG]>=.15){n.inventory[owner][RESOURCE.LOG]-=.15;fueled=true}else if(w.stock[RESOURCE.LOG]>=.15){w.stock[RESOURCE.LOG]-=.15;fueled=true}if(fueled)b.fuel=180}b.lit=b.fuel>0;if(b.lit)sim.senses?.emitSmell?.(b.x,b.y,30,'fumaça',b.owner??-1,sim.tick,180)}}
 trapTick(sim){const n=sim.npcs,tech=technologyFor(sim);for(const t of this.traps){if(!t.active||sim.tick<t.checkAt)continue;const owner=n.indexByUid(t.ownerUid);if(owner<0||!n.alive[owner]){t.active=false;continue}let prey=-1,bd=6;for(let i=0;i<this.count;i++){if(!this.alive[i]||this.domestic[i]||ANIMAL_INFO[this.species[i]]?.predator)continue;const info=ANIMAL_INFO[this.species[i]],d=Math.hypot(this.x[i]-t.x,this.y[i]-t.y);if(info.small&&d<bd){bd=d;prey=i}}if(prey>=0&&this.rng.chance(.45)){const info=ANIMAL_INFO[this.species[prey]];if(info.domesticable&&this.age[prey]<2.5&&tech.knows(n,owner,17)){this.captive[prey]=1;this.tameness[prey]=Math.max(this.tameness[prey],.34);this.metrics.trapCatches++;sim.log('captura',`${n.names[owner]} capturou ${ANIMAL.NAMES[this.species[prey]]} jovem.`,.64,owner)}else{this.killForLoot(sim,this.view(prey),owner,{trap:true});this.metrics.trapCatches++}}t.checkAt=sim.tick+Math.round(DAY_TICKS*.65);if(sim.tick>t.expires)t.active=false}
  if(this.traps.length>180)this.traps=this.traps.filter(t=>t.active);for(const i of n.living()){if(n.age[i]<16||n.action[i]!==ACTION.HUNT||!tech.knows(n,i,13)||this.rng.chance(.94))continue;if(this.traps.some(t=>t.active&&t.ownerUid===n.uid[i]&&Math.hypot(t.x-n.x[i],t.y-n.y[i])<6))continue;if(n.inventory[i][RESOURCE.LOG]<.05)continue;n.inventory[i][RESOURCE.LOG]-=.05;this.traps.push({x:n.x[i],y:n.y[i],ownerUid:n.uid[i],armedAt:sim.tick,checkAt:sim.tick+Math.round(DAY_TICKS*.55),expires:sim.tick+DAY_TICKS*8,active:true})}}
 zoonosisTick(sim){const n=sim.npcs;for(const i of n.living()){let exposure=0;for(let a=0;a<this.count;a++)if(this.alive[a]&&(this.domestic[a]||this.captive[a])&&Math.hypot(this.x[a]-n.x[i],this.y[a]-n.y[i])<3.2)exposure++;if(exposure&&this.rng.chance(Math.min(.025,exposure*.0013))){this.metrics.zoonosisExposures++;infect(sim,i,4,-1)}}}
 regionalTick(sim){this.recountRegional();this.updateFish(sim);this.domesticationTick(sim);this.domesticReproduction(sim);this.domesticProducts(sim);const seas=season(sim.tick),birthSeason=seas==='primavera'?1.65:seas==='verão'?1.15:seas==='outono'?.72:.28,winterDeath=seas==='inverno'?.006:.0015;
  for(let ry=0;ry<RH;ry++)for(let rx=0;rx<RW;rx++){let herbTotal=0,predTotal=0;for(let s=0;s<SPECIES;s++){const info=ANIMAL_INFO[s];if(!info)continue;const idx=this.regionSpeciesIndex(rx,ry,s),pop=this.regionPop[idx];if(info.predator)predTotal+=pop;else herbTotal+=pop;const K=this.capacityFor(s,rx,ry,sim.world,seas);if(info.predator)continue;const growth=info.repro*birthSeason*pop*Math.max(0,1-pop/Math.max(1,K));this.birthCredit[idx]+=growth;if(pop<K*.18)this.refugeCredit[idx]+=.025*Math.max(0,K-pop);while(this.birthCredit[idx]>=1&&this.liveCount()<MAX_ANIMALS){this.birthCredit[idx]-=1;this.spawnInRegion(s,rx,ry,false);this.metrics.births++}while(this.refugeCredit[idx]>=1&&pop<K*.35&&this.liveCount()<MAX_ANIMALS){this.refugeCredit[idx]-=1;this.spawnInRegion(s,rx,ry,false);this.metrics.births++}const deathRate=winterDeath+(pop>K*1.25?.008:0);if(pop>2&&this.rng.chance(Math.min(.25,pop*deathRate)))if(this.cullInRegion(rx,ry,s,'natural'))this.metrics.naturalDeaths++}
   for(let s=0;s<SPECIES;s++){const info=ANIMAL_INFO[s];if(!info?.predator)continue;const idx=this.regionSpeciesIndex(rx,ry,s),pop=this.regionPop[idx],K=this.capacityFor(s,rx,ry,sim.world,seas)*clamp(herbTotal/10,.18,1.2),growth=info.repro*birthSeason*pop*Math.max(0,1-pop/Math.max(.5,K));this.birthCredit[idx]+=growth;while(this.birthCredit[idx]>=1&&this.liveCount()<MAX_ANIMALS){this.birthCredit[idx]-=1;this.spawnInRegion(s,rx,ry,false);this.metrics.births++}if(pop>0&&herbTotal<Math.max(2,pop*1.5)&&this.rng.chance(.03*pop))if(this.cullInRegion(rx,ry,s,'fome'))this.metrics.naturalDeaths++;if(pop>0&&herbTotal>0&&this.rng.chance(Math.min(.35,pop*(seas==='inverno'?.045:.03)))){const prey=this.randomPreyInRegion(rx,ry);if(prey>=0){this.killIndex(prey,'predação');this.metrics.predationDeaths++}}}
   if(herbTotal>18&&this.rng.chance(.12))this.migrateOne(rx,ry,false);if(predTotal>4&&this.rng.chance(.08))this.migrateOne(rx,ry,true)}this.recountRegional()}
 stepEcologyDay(sim){const oldTick=sim.tick;sim.tick+=DAY_TICKS;this.regionalTick(sim);sim.tick=oldTick}
 recountRegional(){this.regionPop.fill(0);for(let i=0;i<this.count;i++)if(this.alive[i]&&!this.domestic[i]&&!this.captive[i])this.regionPop[this.regionSpeciesIndex(Math.floor(this.x[i]/REGION),Math.floor(this.y[i]/REGION),this.species[i])]++}
 regionSpeciesIndex(rx,ry,s){rx=Math.max(0,Math.min(RW-1,rx|0));ry=Math.max(0,Math.min(RH-1,ry|0));return(ry*RW+rx)*SPECIES+s}
 capacityFor(s,rx,ry,w,seas){const info=ANIMAL_INFO[s];let suitability=0,samples=0;for(const [ox,oy] of[[4,4],[12,4],[4,12],[12,12]]){const x=Math.min(MAP_W-1,rx*REGION+ox),y=Math.min(MAP_H-1,ry*REGION+oy),b=w.biome(x,y);samples++;if(info.biomes?.includes(b))suitability+=1;else if(info.predator&&b!==BIOME.WATER&&b!==BIOME.MOUNTAIN)suitability+=.25}suitability/=Math.max(1,samples);const seasonal=seas==='inverno'?(info.predator?1.05:.55):seas==='primavera'?1.2:1;return Math.max(info.predator?.35:.8,(info.baseK||2)*suitability*seasonal)}
 spawnInRegion(s,rx,ry,domestic=false,opts={}){const p=this.suitablePoint(s,this.world,rx,ry);return p?this.spawn(s,p.x,p.y,domestic,{...opts,herd:this.herdFor(s,p.x,p.y)}):null}
 cullInRegion(rx,ry,s,cause){const candidates=[];for(let i=0;i<this.count;i++)if(this.alive[i]&&!this.domestic[i]&&!this.captive[i]&&this.species[i]===s&&Math.floor(this.x[i]/REGION)===rx&&Math.floor(this.y[i]/REGION)===ry)candidates.push(i);if(!candidates.length)return false;this.killIndex(this.rng.pick(candidates),cause);return true}
 randomPreyInRegion(rx,ry){const a=[];for(let i=0;i<this.count;i++)if(this.alive[i]&&!this.domestic[i]&&!ANIMAL_INFO[this.species[i]]?.predator&&Math.floor(this.x[i]/REGION)===rx&&Math.floor(this.y[i]/REGION)===ry)a.push(i);return a.length?this.rng.pick(a):-1}
 migrateOne(rx,ry,predator){const a=[];for(let i=0;i<this.count;i++){if(!this.alive[i]||this.domestic[i]||this.captive[i]||!!ANIMAL_INFO[this.species[i]]?.predator!==predator)continue;if(Math.floor(this.x[i]/REGION)===rx&&Math.floor(this.y[i]/REGION)===ry)a.push(i)}if(!a.length)return;const i=this.rng.pick(a),dirs=[[1,0],[-1,0],[0,1],[0,-1]],d=this.rng.pick(dirs),nr=Math.max(0,Math.min(RW-1,rx+d[0])),ny=Math.max(0,Math.min(RH-1,ry+d[1])),p=this.suitablePoint(this.species[i],this.world,nr,ny);if(p){this.x[i]=this.prevX[i]=p.x;this.y[i]=this.prevY[i]=p.y;this.herd[i]=this.herdFor(this.species[i],p.x,p.y)}}
 updateFish(sim){const seas=season(sim.tick),mult=seas==='primavera'?1.3:seas==='verão'?1.05:seas==='outono'?.9:.48;for(const r of sim.world.resources)if(r.kind===RESOURCE.FISH){const flow=sim.world.flow?.[sim.world.idx(r.x,r.y)]||1,capacity=(1.2+Math.log2(2+flow)*.58)*mult;r.max=Math.max(.6,capacity);r.regen=Math.max(.00004,r.max*.00008);if(r.amount>r.max)r.amount=r.max}}
 domesticationTick(sim){const n=sim.npcs,tech=technologyFor(sim);for(let a=0;a<this.count;a++){if(!this.alive[a]||!ANIMAL_INFO[this.species[a]]?.domesticable)continue;let caretaker=-1,bd=this.captive[a]||this.domestic[a]?7:2.8;for(const i of n.living()){if(n.age[i]<16||!tech.knows(n,i,17))continue;const d=Math.hypot(n.x[i]-this.x[a],n.y[i]-this.y[a]);if(d<bd){bd=d;caretaker=i}}if(caretaker<0)continue;const food=n.inventory[caretaker][RESOURCE.GRAIN]>.02?RESOURCE.GRAIN:n.inventory[caretaker][RESOURCE.BERRY]>.02?RESOURCE.BERRY:-1;if(food<0)continue;n.inventory[caretaker][food]-=.012;const juvenile=this.age[a]<2.7;if(!this.captive[a]&&!this.domestic[a]&&juvenile&&this.tameness[a]>.28)this.captive[a]=1;if(this.captive[a]||this.domestic[a])this.tameness[a]=clamp(this.tameness[a]+.018+.012*n.skill(caretaker,2));if(this.captive[a]&&!this.domestic[a]&&this.tameness[a]>=.72){this.domestic[a]=1;this.metrics.domesticated++;sim.memory.remember(caretaker,{type:'domesticação',text:`Um ${ANIMAL.NAMES[this.species[a]]} criado em cativeiro passou a tolerar nossa presença.`,tick:sim.tick,valence:4,importance:.78,reflectionKey:'domesticação'});sim.log('domesticação',`${n.names[caretaker]} estabeleceu criação de ${ANIMAL.NAMES[this.species[a]]}.`,.8,caretaker)}}}
 domesticReproduction(sim){for(let i=0;i<this.count;i++){if(!this.alive[i]||!this.domestic[i]||this.sex[i]!==0||this.mateCooldown[i]>0||this.age[i]<1.2)continue;const info=ANIMAL_INFO[this.species[i]];if(!this.rng.chance((info.repro||.01)*1.5))continue;let mate=-1;for(let j=0;j<this.count;j++)if(this.alive[j]&&this.domestic[j]&&this.species[j]===this.species[i]&&this.sex[j]!==this.sex[i]&&this.mateCooldown[j]<=0&&Math.hypot(this.x[i]-this.x[j],this.y[i]-this.y[j])<5){mate=j;break}if(mate<0)continue;const tame=clamp((this.tameness[i]+this.tameness[mate])*.5+this.rng.range(-.035,.055));const child=this.spawn(this.species[i],(this.x[i]+this.x[mate])*.5,(this.y[i]+this.y[mate])*.5,true,{age:0,tameness:tame,captive:true,birthTick:sim.tick});if(child){this.mateCooldown[i]=this.mateCooldown[mate]=DAY_TICKS*6;this.metrics.births++}}}
 domesticProducts(sim){const n=sim.npcs;for(let a=0;a<this.count;a++){if(!this.alive[a]||!this.domestic[a]||this.productCooldown[a]>0)continue;const product=ANIMAL_INFO[this.species[a]]?.product;if(!product)continue;let keeper=-1,bd=8;for(const i of n.living()){const d=Math.hypot(n.x[i]-this.x[a],n.y[i]-this.y[a]);if(d<bd){bd=d;keeper=i}}if(keeper<0)continue;const kind=product==='egg'?RESOURCE.EGG:product==='milk'?RESOURCE.MILK:RESOURCE.WOOL,amount=product==='wool'?.18:product==='milk'?.14:.09;n.inventory[keeper][kind]+=amount;n.addSkill(keeper,2,.0012);this.productCooldown[a]=product==='wool'?DAY_TICKS*8:DAY_TICKS;sim.actionHistogram[`pecuária:${product}`]=(sim.actionHistogram[`pecuária:${product}`]||0)+1}}
 killIndex(i,cause='morte'){if(i<0||!this.alive[i])return false;this.alive[i]=0;this.hp[i]=0;this.state[i]=ANIMAL_STATE.REST;return true}
 killForLoot(sim,a,hunter,{trap=false}={}){const i=a?this.indexById(a.id):-1;if(i<0||!this.alive[i])return false;const info=ANIMAL_INFO[this.species[i]],n=sim.npcs,party=[hunter];if(info.dangerous&&!trap)for(const j of n.living())if(j!==hunter&&n.age[j]>=16&&n.action[j]===ACTION.HUNT&&Math.hypot(n.x[j]-n.x[hunter],n.y[j]-n.y[hunter])<5&&party.length<5)party.push(j);if(info.dangerous&&party.length===1&&this.rng.chance(.35)){n.wound[hunter]=Math.min(1,n.wound[hunter]+.08+(info.power||.2)*.08);n.pain[hunter]=Math.min(1,n.pain[hunter]+.12);n.hp[hunter]-=.018+(info.power||.2)*.025}this.killIndex(i,'caça');this.metrics.hunted++;const share=1/party.length;for(const j of party){const inv=n.inventory[j];inv[RESOURCE.MEAT]+=(info.meat||.2)*share;inv[RESOURCE.LEATHER]+=(info.leather||0)*share;if(RESOURCE.BONE!=null)inv[RESOURCE.BONE]+=(info.meat||.2)*.16*share;if(RESOURCE.TENDON!=null)inv[RESOURCE.TENDON]+=(info.meat||.2)*.07*share;if(RESOURCE.FAT!=null)inv[RESOURCE.FAT]+=(info.meat||.2)*.12*share;n.addSkill(j,3,trap?.008:.018);if(party.length>1){n.prestige[j]+=.6+info.meat*.15;for(const k of party)if(k!==j)sim.memory.adjust(j,k,{trust:.018,respect:.025,affection:.01})}}sim.log('caça',`${n.names[hunter]}${party.length>1?` e ${party.length-1} companheiro${party.length>2?'s':''}`:''} abateu ${ANIMAL.NAMES[this.species[i]]}.`,info.dangerous?.82:.65,hunter);return true}
 populationBySpecies(){const out={};for(let s=0;s<SPECIES;s++)out[ANIMAL.NAMES[s]]=0;for(let i=0;i<this.count;i++)if(this.alive[i])out[ANIMAL.NAMES[this.species[i]]]++;return out}
 domesticationStats(){const wild=[],domestic=[];for(let i=0;i<this.count;i++)if(this.alive[i]&&ANIMAL_INFO[this.species[i]]?.domesticable)(this.domestic[i]?domestic:wild).push(this.tameness[i]);const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;return{domestic:domestic.length,wild:wild.length,domesticTameness:avg(domestic),wildTameness:avg(wild)}}
 ecologyMetrics(){return{population:this.liveCount(),bySpecies:this.populationBySpecies(),domestication:this.domesticationStats(),traps:this.traps.filter(t=>t.active).length,...this.metrics}}
 serialize(){const rows=[];for(let i=0;i<this.count;i++)if(this.alive[i])rows.push([this.id[i],this.species[i],this.x[i],this.y[i],this.prevX[i],this.prevY[i],this.state[i],this.target[i],this.age[i],this.hp[i],this.fear[i],this.satiety[i],this.herd[i],this.tameness[i],this.sex[i],this.domestic[i],this.captive[i],this.power[i],this.hunger[i],this.mateCooldown[i],this.productCooldown[i],this.birthTick[i]]);this.recountRegional();return{v:2,nextId:this.nextId,rows,regionPop:Array.from(this.regionPop),birthCredit:Array.from(this.birthCredit),refugeCredit:Array.from(this.refugeCredit),traps:this.traps,metrics:this.metrics,lastViewX:this.lastViewX,lastViewY:this.lastViewY}}
 static hydrate(d,rng,world){if(!d)return new AnimalSystem(rng,world);if(d.items){const s=new AnimalSystem(rng,world,{skipSpawn:true});for(const a of d.items||[])if(a.alive!==false)s.spawn(a.species,a.x,a.y,!!a.domestic,{id:a.id,age:a.age,hp:a.hp,tameness:a.tameness??(a.domestic?.78:.15),captive:a.captive,sex:a.sex,power:a.power,hunger:a.hunger,mateCooldown:a.mateCooldown,productCooldown:a.productCooldown});s.nextId=d.nextId||s.nextId;s.recountRegional();return s}const s=new AnimalSystem(rng,world,{skipSpawn:true});for(const r of d.rows||[])s.spawn(r[1],r[2],r[3],!!r[15],{id:r[0],age:r[8],hp:r[9],fear:r[10],satiety:r[11],herd:r[12],tameness:r[13],sex:r[14],captive:!!r[16],power:r[17],hunger:r[18],mateCooldown:r[19],productCooldown:r[20],birthTick:r[21]});for(let q=0;q<(d.rows||[]).length;q++){const r=d.rows[q],i=s.indexById(r[0]);if(i>=0){s.prevX[i]=r[4];s.prevY[i]=r[5];s.state[i]=r[6];s.target[i]=r[7]}}s.nextId=d.nextId||s.nextId;if(d.regionPop)s.regionPop.set(d.regionPop.slice(0,s.regionPop.length));if(d.birthCredit)s.birthCredit.set(d.birthCredit.slice(0,s.birthCredit.length));if(d.refugeCredit)s.refugeCredit.set(d.refugeCredit.slice(0,s.refugeCredit.length));s.traps=d.traps||[];s.metrics={...s.metrics,...(d.metrics||{})};s.lastViewX=d.lastViewX??world.settlement?.x??MAP_W/2;s.lastViewY=d.lastViewY??world.settlement?.y??MAP_H/2;return s}
}

function makeView(store,i){const v={_i:i};const def=(name,get,set)=>Object.defineProperty(v,name,{enumerable:true,get,set});def('id',()=>store.id[i]);def('species',()=>store.species[i],x=>store.species[i]=x);def('x',()=>store.x[i],x=>store.x[i]=x);def('y',()=>store.y[i],x=>store.y[i]=x);def('prevX',()=>store.prevX[i],x=>store.prevX[i]=x);def('prevY',()=>store.prevY[i],x=>store.prevY[i]=x);def('hp',()=>store.hp[i],x=>store.hp[i]=x);def('alive',()=>!!store.alive[i],x=>store.alive[i]=x?1:0);def('age',()=>store.age[i],x=>store.age[i]=x);def('fear',()=>store.fear[i],x=>store.fear[i]=x);def('satiety',()=>store.satiety[i],x=>store.satiety[i]=x);def('herd',()=>store.herd[i],x=>store.herd[i]=x);def('tameness',()=>store.tameness[i],x=>store.tameness[i]=x);def('sex',()=>store.sex[i],x=>store.sex[i]=x);def('domestic',()=>!!store.domestic[i],x=>store.domestic[i]=x?1:0);def('captive',()=>!!store.captive[i],x=>store.captive[i]=x?1:0);def('predator',()=>!!ANIMAL_INFO[store.species[i]]?.predator);def('power',()=>store.power[i],x=>store.power[i]=x);def('state',()=>ANIMAL_STATE.NAMES[store.state[i]]||'pastar',x=>store.state[i]=typeof x==='number'?x:(STATE_BY_NAME.get(x)??ANIMAL_STATE.GRAZE));return v}
