import {ANIMAL,ANIMAL_INFO,MAX_ANIMALS,BIOME,RESOURCE,MAP_W,MAP_H,TILE_TYPE} from '../core/constants.js';
import {isNight} from '../core/clock.js';
const herb=[ANIMAL.DEER,ANIMAL.RABBIT,ANIMAL.BOAR],pred=[ANIMAL.WOLF,ANIMAL.BEAR];
export class AnimalSystem{
 constructor(rng,world){this.rng=rng;this.items=[];this.nextId=1;this.spawnInitial(world)}
 spawnInitial(w){const cells=[];for(let y=3;y<MAP_H-3;y+=4)for(let x=3;x<MAP_W-3;x+=4){const b=w.biome(x,y);if(b!==BIOME.WATER&&b!==BIOME.MOUNTAIN&&b!==BIOME.MARSH)cells.push([x+.5,y+.5,b])}const herbCount=Math.min(260,Math.round(MAP_W*MAP_H/180)),predCount=Math.max(12,Math.round(herbCount*.09));for(let k=0;k<herbCount;k++){const c=this.rng.pick(cells);if(!c)break;let s=this.rng.pick(herb);if(c[2]===BIOME.DENSE_FOREST&&this.rng.chance(.14))s=ANIMAL.BOAR;this.spawn(s,c[0],c[1])}for(let k=0;k<predCount;k++){const c=this.rng.pick(cells);if(c)this.spawn(this.rng.pick(pred),c[0],c[1])}}
 spawn(species,x,y,domestic=false){if(this.items.filter(a=>a.alive).length>=MAX_ANIMALS)return null;const info=ANIMAL_INFO[species],a={id:this.nextId++,species,x,y,prevX:x,prevY:y,hp:info.hp,alive:true,state:'pastar',sex:this.rng.int(0,1),age:this.rng.range(1,6),hunger:this.rng.range(0,.4),mateCooldown:this.rng.int(0,2600),productCooldown:this.rng.int(0,1200),domestic:domestic||!!info.domestic,predator:!!info.predator,power:species===ANIMAL.BEAR?.65:species===ANIMAL.WOLF?.34:species===ANIMAL.BOAR?.22:.08};this.items.push(a);return a}
 nearestPrey(x,y,rad=8){let best=null,bd=rad;for(const a of this.items)if(a.alive&&!a.predator&&!a.domestic){const d=Math.hypot(a.x-x,a.y-y);if(d<bd){bd=d;best=a}}return best}
 byId(id){return this.items.find(a=>a.id===id&&a.alive)||null}
 step(sim){const w=sim.world,n=sim.npcs,night=isNight(sim.tick);for(const a of this.items)if(a.alive){a.prevX=a.x;a.prevY=a.y;a.hunger=Math.min(1,a.hunger+.00018);if(a.mateCooldown>0)a.mateCooldown--;if(a.productCooldown>0)a.productCooldown--;const info=ANIMAL_INFO[a.species];let human=-1,hd=8;for(const i of n.living()){const d=Math.hypot(n.x[i]-a.x,n.y[i]-a.y);if(d<hd){hd=d;human=i}}if(a.domestic){if(human>=0&&hd>5)this.moveToward(a,n.x[human],n.y[human],info.speed*.35,w);else if(this.rng.chance(.012))this.wander(a,w,info.speed*.35);continue}if(a.predator){let prey=null,pd=11;for(const b of this.items)if(b.alive&&!b.predator&&!b.domestic&&b.id!==a.id){const d=Math.hypot(b.x-a.x,b.y-a.y);if(d<pd){pd=d;prey=b}}if(prey){a.state='caçar';this.moveToward(a,prey.x,prey.y,info.speed,w);if(pd<.65&&this.rng.chance(.08)){prey.hp-=.08+a.power*.2;if(prey.hp<=0){prey.alive=false;a.hunger=Math.max(0,a.hunger-.55)}}}else if(human>=0&&hd<3.3&&night&&a.hunger>.78){let nearby=0;for(const q of n.living())if(Math.hypot(n.x[q]-n.x[human],n.y[q]-n.y[human])<3)nearby++;if(nearby<=2){a.state='caçar humano';this.moveToward(a,n.x[human],n.y[human],info.speed*.85,w);if(hd<.7&&this.rng.chance(.012)){n.wound[human]=Math.min(1,n.wound[human]+.018+a.power*.025);n.hp[human]-=.001+a.power*.004;sim.memory.remember(human,{type:'animal',text:`Fui atacado por ${a.species===ANIMAL.WOLF?'um lobo':'um urso'}.`,tick:sim.tick,valence:-7,importance:.82,reflectionKey:'predadores'})}}else this.wander(a,w,info.speed*.45)}else this.wander(a,w,info.speed*.5)}else{if(human>=0&&hd<3){a.state='fugir';const dx=a.x-n.x[human],dy=a.y-n.y[human],d=Math.hypot(dx,dy)||1;this.moveToward(a,a.x+dx/d*4,a.y+dy/d*4,info.speed*1.2,w)}else{a.state='pastar';if(this.rng.chance(.025))this.wander(a,w,info.speed*.45);a.hunger=Math.max(0,a.hunger-.0005)}}if(a.mateCooldown<=0&&this.rng.chance(.00018)){const mate=this.items.find(b=>b.alive&&b.species===a.species&&b.sex!==a.sex&&b.mateCooldown<=0&&Math.hypot(b.x-a.x,b.y-a.y)<2);if(mate&&this.items.length<MAX_ANIMALS){this.spawn(a.species,(a.x+mate.x)/2,(a.y+mate.y)/2,false);a.mateCooldown=mate.mateCooldown=840*8}}if(a.hp<=0)a.alive=false}if(sim.tick%8400===0)this.items=this.items.filter(a=>a.alive||sim.tick%16800!==0)}
 moveToward(a,x,y,speed,w){const dx=x-a.x,dy=y-a.y,d=Math.hypot(dx,dy);if(d<.05)return;const nx=a.x+dx/d*speed,ny=a.y+dy/d*speed,t=w.tile(nx,ny);if(t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN){a.x=nx;a.y=ny}}
 wander(a,w,speed){const ang=this.rng.range(0,Math.PI*2),nx=a.x+Math.cos(ang)*speed,ny=a.y+Math.sin(ang)*speed,t=w.tile(nx,ny);if(w.inside(nx,ny)&&t!==TILE_TYPE.WATER&&t!==TILE_TYPE.MOUNTAIN){a.x=nx;a.y=ny}}
 killForLoot(sim,a,hunter){if(!a||!a.alive)return;a.alive=false;const info=ANIMAL_INFO[a.species],inv=sim.npcs.inventory[hunter];inv[RESOURCE.MEAT]+=info.meat||.2;inv[RESOURCE.LEATHER]+=info.leather||0;sim.npcs.addSkill(hunter,3,.018);sim.log('caça',`${sim.npcs.names[hunter]} abateu um ${ANIMAL.NAMES[a.species]}.`,.65,hunter)}
 serialize(){return{items:this.items,nextId:this.nextId}}
 static hydrate(d,rng,world){const s=Object.create(AnimalSystem.prototype);s.rng=rng;s.items=d?.items||[];s.nextId=d?.nextId||1;return s}
}
