import {World} from '../world/world.js';
import {MAP_W,MAP_H,RESOURCE,BUILDING,BLOCK,TOOL,TILE_TYPE,BIOME,FOOD_KINDS,DAY_TICKS,GENE} from '../core/constants.js';
import {noiseHash} from '../core/rng.js';
import {technologyFor} from './technology.js';

const N=MAP_W*MAP_H,ROOM_LIMIT=128,REGION=16,RW=Math.ceil(MAP_W/REGION),RH=Math.ceil(MAP_H/REGION);
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));

export const MATERIAL={WOOD:0,STONE:1,MUD:2,THATCH:3,METAL:4,NAMES:['madeira','pedra','taipa','palha','metal']};
export const PIECE={
 FLOOR:0,WALL:1,DOOR:2,WINDOW:3,ROOF:4,PILLAR:5,FENCE:6,GATE:7,FIRE:8,OVEN:9,FORGE:10,DRYER:11,BED:12,CHEST:13,BENCH:14,LOOM:15,PEN:16,GARDEN:17,WELL:18,BRANCH_SHELTER:19,
 NAMES:['piso','parede','porta','janela','telhado','pilar','cerca','portão','fogueira','forno','forja','secador','cama','baú','bancada','tear','curral','canteiro','poço','abrigo de galhos']
};

export const PIECE_CATALOG={
 [PIECE.FLOOR]:{material:RESOURCE.LOG,cost:.12,tool:TOOL.NONE,tech:1,work:18,durability:1.0,layer:'ground'},
 [PIECE.WALL]:{material:RESOURCE.LOG,cost:.24,tool:TOOL.NONE,tech:1,work:34,durability:1.0,blocking:true,layer:'ground'},
 [PIECE.DOOR]:{material:RESOURCE.LOG,cost:.22,tool:TOOL.NONE,tech:1,work:38,durability:.9,door:true,layer:'ground'},
 [PIECE.WINDOW]:{material:RESOURCE.LOG,cost:.18,tool:TOOL.HAMMER,tech:8,work:34,durability:.72,blocking:true,layer:'ground'},
 [PIECE.ROOF]:{material:RESOURCE.LOG,cost:.16,tool:TOOL.NONE,tech:1,work:24,durability:.82,roof:true,layer:'roof'},
 [PIECE.PILLAR]:{material:RESOURCE.LOG,cost:.2,tool:TOOL.NONE,tech:1,work:30,durability:1.05,blocking:true,layer:'ground'},
 [PIECE.FENCE]:{material:RESOURCE.LOG,cost:.1,tool:TOOL.NONE,tech:1,work:16,durability:.72,blocking:true,layer:'ground'},
 [PIECE.GATE]:{material:RESOURCE.LOG,cost:.16,tool:TOOL.NONE,tech:1,work:22,durability:.68,door:true,layer:'ground'},
 [PIECE.FIRE]:{material:RESOURCE.STONE,cost:.34,tool:TOOL.NONE,tech:3,work:24,durability:1.2,functional:true,layer:'fixture'},
 [PIECE.OVEN]:{material:RESOURCE.CLAY,cost:.7,tool:TOOL.HAMMER,tech:18,work:70,durability:1.25,functional:true,layer:'fixture'},
 [PIECE.FORGE]:{material:RESOURCE.STONE,cost:.9,tool:TOOL.HAMMER,tech:24,work:90,durability:1.5,functional:true,layer:'fixture'},
 [PIECE.DRYER]:{material:RESOURCE.LOG,cost:.35,tool:TOOL.NONE,tech:36,work:38,durability:.7,functional:true,layer:'fixture'},
 [PIECE.BED]:{material:RESOURCE.WOOL,cost:.35,tool:TOOL.NONE,tech:20,work:28,durability:.6,functional:true,layer:'fixture'},
 [PIECE.CHEST]:{material:RESOURCE.LOG,cost:.42,tool:TOOL.HAMMER,tech:8,work:48,durability:.9,functional:true,container:true,layer:'fixture'},
 [PIECE.BENCH]:{material:RESOURCE.LOG,cost:.35,tool:TOOL.HAMMER,tech:8,work:42,durability:.9,functional:true,layer:'fixture'},
 [PIECE.LOOM]:{material:RESOURCE.LOG,cost:.38,tool:TOOL.HAMMER,tech:20,work:56,durability:.75,functional:true,layer:'fixture'},
 [PIECE.PEN]:{material:RESOURCE.LOG,cost:.2,tool:TOOL.NONE,tech:17,work:24,durability:.72,functional:true,layer:'fixture'},
 [PIECE.GARDEN]:{material:RESOURCE.SEED,cost:.08,tool:TOOL.NONE,tech:16,work:20,durability:.5,functional:true,layer:'fixture'},
 [PIECE.WELL]:{material:RESOURCE.STONE,cost:.9,tool:TOOL.HAMMER,tech:14,work:80,durability:1.4,functional:true,layer:'fixture'},
 [PIECE.BRANCH_SHELTER]:{material:RESOURCE.LOG,cost:.28,tool:TOOL.NONE,tech:1,work:28,durability:.38,blocking:true,provisional:true,layer:'ground'}
};

export function ensureConstruction(target){
 const sim=target?.world?target:null,w=sim?sim.world:target;if(!w)return null;
 if(!w.structure){w.structure=new Uint16Array(N);w.structureOwner=new Int16Array(N);w.structureOwner.fill(-1);w.pieceStore=[null];w.nextPieceId=1;w.roomCache=new Map();w.roomAtTile=new Int32Array(N);w.roomAtTile.fill(-1);w.territoryOwner=new Int16Array(N);w.territoryOwner.fill(-1);w.territoryStrength=new Uint8Array(N);w.constructionMetrics={placed:0,repaired:0,collapsed:0,fires:0,thefts:0,gifts:0,frontierContacts:0,roomRebuilds:0,pathInvalidations:0};w.phaseGVersion=1;w._territoryDirty=true;w._roomDirty=true;migrateLegacy(w)}
 if(sim){w._constructionSim=sim;attachGroups(sim);}
 return w;
}

export function groupForNpc(sim,i){const n=sim.npcs,seeds=sim.world.spawnSeeds||[];if(!seeds.length)return 0;const x=n.homeX[i]||n.x[i],y=n.homeY[i]||n.y[i];let best=0,bd=Infinity;for(let k=0;k<seeds.length;k++){const d=Math.hypot(x-seeds[k].x,y-seeds[k].y);if(d<bd){bd=d;best=k}}return best}
export function territoryAt(sim,x,y){const w=ensureConstruction(sim);if(w._territoryDirty)rebuildTerritory(sim);if(!w.inside(x,y))return-1;return w.territoryOwner[w.idx(x,y)]}
export function territoryAccessFactor(sim,i,x,y){const g=territoryAt(sim,x,y);if(g<0||g===groupForNpc(sim,i))return 1;const n=sim.npcs,ag=n.gene(i,GENE.AGGRESSION),ca=n.gene(i,GENE.CAUTION);return clamp(.3+ag*.55-ca*.28,.18,.86)}

export function constructionNeedScore(sim,i,perception={}){
 const w=ensureConstruction(sim),n=sim.npcs,g=groupForNpc(sim,i),own=n.uid[i];
 const active=w.blueprints.some(bp=>!bp.done&&(bp.owner===own||bp.group===g));
 const room=roomAt(w,n.x[i],n.y[i]),hasShelter=w.buildings.some(b=>b.finished&&b.type===BUILDING.SHELTER&&(b.owner===own||b.group===g));
 const hasChest=w.pieceStore.some?.(p=>p?.type===PIECE.CHEST&&p.durability>0&&(p.ownerUid===own||p.group===g));
 const damaged=w.pieceStore.some?.(p=>p&&p.group===g&&p.durability/p.maxDurability<.68);
 const herd=sim.animals?.items?.some(a=>a.alive&&a.domestic&&Math.hypot(a.x-n.x[i],a.y-n.y[i])<12),hasFence=w.pieceStore.some?.(p=>p?.group===g&&(p.type===PIECE.FENCE||p.type===PIECE.GATE));
 let unmet=0;if(!hasShelter&&!room)unmet+=.46+n.need(i,3)*.4+n.need(i,4)*.26;if(!hasChest)unmet+=inventoryLoad(n.inventory[i])>.45?.26:.06;if(herd&&!hasFence)unmet+=.22;if(damaged)unmet+=.28;
 if(active)unmet=Math.max(unmet,.32);return clamp(unmet,0,1.25);
}

export function roomAt(world,x,y){ensureConstruction(world);if(!world.inside(x,y))return null;const rid=world.roomAtTile[world.idx(x,y)];return rid>=0?world.roomCache.get(rid)||null:null}
export function roomInsulation(world,x,y){const r=roomAt(world,x,y);return r?clamp(.18+r.seal*.42+r.coverage*.22,0,.7):0}
export function constructionStats(sim){const w=ensureConstruction(sim),pieces=w.pieceStore.filter(Boolean),rooms=[...w.roomCache.values()],materials={};for(const p of pieces)materials[MATERIAL.NAMES[p.materialStyle]||'outro']=(materials[MATERIAL.NAMES[p.materialStyle]||'outro']||0)+1;return{pieces:pieces.length,rooms:rooms.length,blueprints:w.blueprints.filter(b=>!b.done).length,materials,metrics:{...w.constructionMetrics},territories:new Set(Array.from(w.territoryOwner).filter(x=>x>=0)).size}}

function install(){if(World.prototype.__phaseGInstalled)return;
 const baseSerialize=World.prototype.serialize,baseHydrate=World.hydrate,baseTick=World.prototype.tick,baseTemp=World.prototype.temperatureAt,baseNearest=World.prototype.nearestBuildingLocal,baseAddBuilding=World.prototype.addBuilding;
 World.prototype.serialize=function(){ensureConstruction(this);const out=baseSerialize.call(this);out.phaseG=serializeConstruction(this);return out};
 World.hydrate=function(d,rng,seed=1){const w=baseHydrate.call(World,d,rng,seed);hydrateConstruction(w,d?.phaseG);return w};
 World.prototype.tick=function(tick){ensureConstruction(this);baseTick.call(this,tick);if(this._constructionSim)constructionTick(this._constructionSim)};
 World.prototype.temperatureAt=function(x,y,tick,ambient){let v=baseTemp.call(this,x,y,tick,ambient),r=roomAt(this,x,y);if(r){v+=r.insulation*5.5;if(r.hasFire)v+=4.5}return v};
 World.prototype.nearestBuildingLocal=function(x,y,type,rad=14,owner=null){if(type===BUILDING.STORAGE&&this.phaseGVersion&&this.pieceStore?.some(p=>p?.type===PIECE.CHEST))return null;return baseNearest.call(this,x,y,type,rad,owner)};
 World.prototype.structureCost=function(x,y){ensureConstruction(this);if(!this.inside(x,y))return Infinity;const id=this.structure[this.idx(x,y)];if(!id)return 1;const p=this.pieceStore[id];if(!p||p.durability<=0)return 1;if(p.type===PIECE.DOOR||p.type===PIECE.GATE)return p.open?1.02:1.18;if([PIECE.WALL,PIECE.PILLAR,PIECE.FENCE,PIECE.BRANCH_SHELTER].includes(p.type))return Infinity;return 1};
 World.prototype.invalidateStructureRegion=function(x,y){this.pathfinder?.invalidateRegion?.(x,y);this.constructionMetrics.pathInvalidations++;this._territoryDirty=true;recomputeRoomsAround(this,x,y)};
 World.prototype.createBlueprint=function(type,cx,cy,owner=-1){ensureConstruction(this);return createProject(this,type,cx,cy,owner)};
 World.prototype.nextBlueprintPiece=function(ownerUid=null){ensureConstruction(this);return nextProjectTask(this,ownerUid)};
 World.prototype.completePiece=function(bp,p){ensureConstruction(this);return completeProjectPiece(this,bp,p,baseAddBuilding)};
 Object.defineProperty(World.prototype,'__phaseGInstalled',{value:true});
}
install();

function attachGroups(sim){const w=sim.world,n=sim.npcs;for(const p of w.pieceStore||[]){if(!p)continue;if(p.ownerUid>0){const i=n.indexByUid(p.ownerUid);if(i>=0){p.group=groupForNpc(sim,i);const tile=w.inside(p.x,p.y)?w.idx(p.x,p.y):-1;if(tile>=0&&w.structure[tile]===p.id)w.structureOwner[tile]=i}}}for(const bp of w.blueprints||[])if(bp.group==null&&bp.owner>0){const i=n.indexByUid(bp.owner);bp.group=i>=0?groupForNpc(sim,i):0}}
function migrateLegacy(w){if(!w.blocks?.length)return;for(const b of w.blocks){const type=b.type===BLOCK.WALL?PIECE.WALL:b.type===BLOCK.DOOR?PIECE.DOOR:b.type===BLOCK.ROOF?PIECE.ROOF:b.type===BLOCK.FIRE?PIECE.FIRE:b.type===BLOCK.WELL?PIECE.WELL:PIECE.FLOOR;const owner=w.buildings?.[b.buildingId]?.owner??-1;placePieceRecord(w,{type,x:Math.floor(b.x),y:Math.floor(b.y),ownerUid:owner,group:0,materialStyle:type===PIECE.WALL?MATERIAL.WOOD:MATERIAL.WOOD,durability:b.hp??1,maxDurability:1,legacy:true},false)}rebuildAllRooms(w)}

function serializeConstruction(w){const pieces=[];for(const p of w.pieceStore||[])if(p)pieces.push({...p,inventory:p.inventory?Array.from(p.inventory):undefined,lots:p.lots?.map(x=>({...x}))});return{version:1,nextPieceId:w.nextPieceId,pieces,metrics:w.constructionMetrics,territoryEvents:w.territoryEvents||[],fireEvents:w.fireEvents||[]}}
function hydrateConstruction(w,d){ensureConstruction(w);w.structure.fill(0);w.structureOwner.fill(-1);w.pieceStore=[null];w.nextPieceId=1;if(d?.pieces?.length){for(const raw of d.pieces){const p={...raw};if(raw.inventory)p.inventory=Float32Array.from(raw.inventory);if(raw.lots)p.lots=raw.lots.map(x=>({...x}));placePieceRecord(w,p,false)}w.nextPieceId=Math.max(d.nextPieceId||1,w.pieceStore.length)}else migrateLegacy(w);w.constructionMetrics={...w.constructionMetrics,...(d?.metrics||{})};w.territoryEvents=d?.territoryEvents||[];w.fireEvents=d?.fireEvents||[];rebuildAllRooms(w);w._territoryDirty=true}

function createProject(w,type,cx,cy,ownerUid=-1){const sim=w._constructionSim,n=sim?.npcs,oi=n?.indexByUid(ownerUid)??-1,group=oi>=0?groupForNpc(sim,oi):0;if(w.blueprints.some(b=>!b.done&&(b.owner===ownerUid||b.group===group)&&Math.hypot(b.cx-cx,b.cy-cy)<18))return null;const site=findProjectSite(w,cx,cy,type),style=chooseStyle(sim,oi,site.x,site.y),pieces=projectTemplate(type,site.x,site.y,style,ownerUid,group);if(!pieces.length)return null;const bp={id:w.blueprints.length,type,cx:site.x,cy:site.y,owner:ownerUid,group,style,createdTick:sim?.tick||0,lastTouched:sim?.tick||0,pieces,done:false,abandoned:false};w.blueprints.push(bp);return bp}
function findProjectSite(w,cx,cy,type){let best={x:Math.round(cx),y:Math.round(cy),score:-Infinity};for(let r=0;r<=5;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){if(r&&Math.abs(dx)!==r&&Math.abs(dy)!==r)continue;const x=Math.round(cx+dx),y=Math.round(cy+dy);if(!siteFits(w,x,y,type))continue;const id=w.idx(x,y),score=(w.tiles[id]===TILE_TYPE.GRASS?1:.4)-(w.slope[id]||0)/260-Math.hypot(dx,dy)*.035;if(score>best.score)best={x,y,score}}return{x:best.x,y:best.y}}
function siteFits(w,cx,cy,type){const rad=[BUILDING.CAMPFIRE,BUILDING.WELL,BUILDING.FARM].includes(type)?1:3;for(let y=cy-rad;y<=cy+rad;y++)for(let x=cx-rad;x<=cx+rad;x++){if(!w.inside(x,y))return false;const t=w.tile(x,y);if(t===TILE_TYPE.WATER||t===TILE_TYPE.MOUNTAIN)return false;if(w.structure?.[w.idx(x,y)])return false}return true}
function chooseStyle(sim,i,x,y){if(!sim||i<0)return MATERIAL.WOOD;const n=sim.npcs,t=technologyFor(sim),w=sim.world,b=w.biome(x,y),inv=n.inventory[i];if(t.knows(n,i,22)&&(inv[RESOURCE.STONE]>.8||b===BIOME.ROCK||b===BIOME.MOUNTAIN))return MATERIAL.STONE;if(t.knows(n,i,18)&&(b===BIOME.STEPPE||b===BIOME.MARSH)&&(inv[RESOURCE.CLAY]>.5||w.resourcesNear(x,y,8,RESOURCE.CLAY).length))return MATERIAL.MUD;return MATERIAL.WOOD}
function projectTemplate(type,cx,cy,style,ownerUid,group){const out=[],add=(dx,dy,piece,opts={})=>out.push(makePlanPiece(cx+dx,cy+dy,piece,style,ownerUid,group,opts));if(type===BUILDING.CAMPFIRE){add(0,0,PIECE.FIRE);return out}if(type===BUILDING.WELL){add(0,0,PIECE.WELL);return out}if(type===BUILDING.FARM){for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]])add(dx,dy,PIECE.GARDEN);return out}if(type===BUILDING.COOP){for(let x=-2;x<=2;x++){add(x,-2,PIECE.FENCE);add(x,2,x===0?PIECE.GATE:PIECE.FENCE)}for(let y=-1;y<=1;y++){add(-2,y,PIECE.FENCE);add(2,y,PIECE.FENCE)}add(0,0,PIECE.PEN,{layer:'fixture'});return out}
 const wallStyle=style,wallMat=wallStyle===MATERIAL.STONE?RESOURCE.STONE:wallStyle===MATERIAL.MUD?RESOURCE.CLAY:RESOURCE.LOG,wallTech=wallStyle===MATERIAL.STONE?22:wallStyle===MATERIAL.MUD?18:1,wallTool=wallStyle===MATERIAL.STONE||wallStyle===MATERIAL.MUD?TOOL.HAMMER:TOOL.NONE;
 for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)add(x,y,PIECE.FLOOR,{material:wallStyle===MATERIAL.STONE?RESOURCE.STONE:RESOURCE.LOG,cost:.11});
 for(let x=-2;x<=2;x++){add(x,-2,PIECE.WALL,{style:wallStyle,material:wallMat,tech:wallTech,tool:wallTool});add(x,2,x===0?PIECE.DOOR:PIECE.WALL,{style:wallStyle,material:wallMat,tech:wallTech,tool:wallTool})}for(let y=-1;y<=1;y++){add(-2,y,PIECE.WALL,{style:wallStyle,material:wallMat,tech:wallTech,tool:wallTool});add(2,y,PIECE.WALL,{style:wallStyle,material:wallMat,tech:wallTech,tool:wallTool})}add(0,0,PIECE.PILLAR,{style:wallStyle,material:wallMat,tech:wallTech,tool:wallTool});
 for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)add(x,y,PIECE.ROOF,{layer:'roof',style:style===MATERIAL.MUD?MATERIAL.THATCH:style,material:style===MATERIAL.STONE?RESOURCE.STONE:RESOURCE.LOG,cost:.13});
 if(type===BUILDING.STORAGE||type===BUILDING.CELLAR)add(1,0,PIECE.CHEST,{layer:'fixture'});if(type===BUILDING.WORKSHOP){add(1,0,PIECE.BENCH,{layer:'fixture'});add(-1,0,PIECE.LOOM,{layer:'fixture'})}if(type===BUILDING.FORGE)add(1,0,PIECE.FORGE,{layer:'fixture'});if(type===BUILDING.SHELTER)add(1,0,PIECE.BED,{layer:'fixture'});if(type===BUILDING.CELLAR)for(const p of out)if(p.pieceType===PIECE.WALL){p.material=RESOURCE.STONE;p.materialStyle=MATERIAL.STONE;p.tech=22;p.tool=TOOL.HAMMER;p.cost=.3}return out}
function makePlanPiece(x,y,pieceType,style=MATERIAL.WOOD,ownerUid=-1,group=0,opts={}){const c=PIECE_CATALOG[pieceType]||PIECE_CATALOG[PIECE.FLOOR],material=opts.material??c.material,cost=opts.cost??c.cost;return{x,y,block:compatBlock(pieceType),pieceType,material,cost,tool:opts.tool??c.tool,tech:opts.tech??c.tech,work:opts.work??c.work,materialStyle:opts.style??style,layer:opts.layer??c.layer,progress:0,done:false,reserved:false,ownerUid,group,repairId:null}}
function compatBlock(type){return type===PIECE.WALL||type===PIECE.PILLAR||type===PIECE.FENCE?BLOCK.WALL:type===PIECE.DOOR||type===PIECE.GATE?BLOCK.DOOR:type===PIECE.ROOF?BLOCK.ROOF:type===PIECE.FIRE?BLOCK.FIRE:type===PIECE.WELL?BLOCK.WELL:BLOCK.FLOOR}

function nextProjectTask(w,ownerUid){const sim=w._constructionSim,n=sim?.npcs,i=n?.indexByUid(ownerUid)??-1,group=i>=0?groupForNpc(sim,i):0;if(sim)ensureMaintenanceProjects(sim,group);let best=null,bs=-Infinity;for(const bp of w.blueprints){if(bp.done||bp.abandoned)continue;if(ownerUid!=null&&bp.owner!==ownerUid&&bp.group!==group)continue;for(let pi=0;pi<bp.pieces.length;pi++){const p=bp.pieces[pi];if(p.done||p.reserved)continue;if(!supportSatisfied(w,p))continue;if(sim&&i>=0){if(p.tech!=null&&!technologyFor(sim).knows(n,i,p.tech))continue;if(p.tool&&n.tool[i]!==p.tool&&w.tools?.[p.tool]<=0)continue;if(isBlockingPlan(p)&&!placementPreservesAccess(sim,p))continue;const d=Math.hypot(n.x[i]-p.x,n.y[i]-p.y),rel=bp.owner===ownerUid?1:relationshipFactor(sim,i,bp.owner),score=1/(1+d*.08)+rel*.22+n.skill(i,6)*.18+(p.repairId?0.2:0);if(score>bs){bs=score;best={bp,piece:p,pieceIndex:pi}}}else if(!best)best={bp,piece:p,pieceIndex:pi}}}if(best&&sim)best.bp.lastTouched=sim.tick;return best}
function relationshipFactor(sim,i,ownerUid){const j=sim.npcs.indexByUid(ownerUid);if(j<0)return.15;const r=sim.memory.relation(i,j);return clamp(.45+(r.affection||0)*.35+(r.trust||0)*.35,0,1)}
function supportSatisfied(w,p){if(p.repairId)return true;if(p.layer==='roof'){for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[0,0]]){const id=w.inside(p.x+dx,p.y+dy)?w.structure[w.idx(p.x+dx,p.y+dy)]:0,q=w.pieceStore[id];if(q&&[PIECE.WALL,PIECE.PILLAR,PIECE.DOOR].includes(q.type))return true}return false}if(p.layer==='fixture'&&![PIECE.FIRE,PIECE.WELL,PIECE.GARDEN,PIECE.PEN].includes(p.pieceType))return w.pieceStore.some(q=>q&&q.type===PIECE.FLOOR&&q.x===p.x&&q.y===p.y&&q.durability>0);return true}
function isBlockingPlan(p){return p.layer==='ground'&&[PIECE.WALL,PIECE.PILLAR,PIECE.FENCE,PIECE.BRANCH_SHELTER].includes(p.pieceType)}

export function placementPreservesAccess(sim,p){if(!isBlockingPlan(p))return true;const w=ensureConstruction(sim),tx=Math.floor(p.x),ty=Math.floor(p.y);if(!w.inside(tx,ty))return false;const nearby=sim.npcs.living().filter(i=>Math.hypot(sim.npcs.x[i]-tx,sim.npcs.y[i]-ty)<7);for(const i of nearby){const sx=Math.floor(sim.npcs.x[i]),sy=Math.floor(sim.npcs.y[i]);if(sx===tx&&sy===ty)return false;if(!localExitReachable(w,sx,sy,tx,ty))return false}return true}
function localExitReachable(w,sx,sy,blockX,blockY){const r=7,minX=Math.max(0,sx-r),maxX=Math.min(MAP_W-1,sx+r),minY=Math.max(0,sy-r),maxY=Math.min(MAP_H-1,sy+r),q=[[sx,sy]],seen=new Set([`${sx},${sy}`]);while(q.length){const [x,y]=q.shift();if(x===minX||x===maxX||y===minY||y===maxY)return true;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(nx<minX||ny<minY||nx>maxX||ny>maxY||seen.has(key)||nx===blockX&&ny===blockY)continue;const t=w.tile(nx,ny);if(t===TILE_TYPE.WATER||t===TILE_TYPE.MOUNTAIN)continue;const c=w.structureCost?.(nx,ny)??1;if(!Number.isFinite(c))continue;seen.add(key);q.push([nx,ny])}}return false}

function completeProjectPiece(w,bp,p,baseAddBuilding){const sim=w._constructionSim;if(p.repairId){const target=w.pieceStore[p.repairId];if(target){target.durability=target.maxDurability;p.done=true;p.progress=1;bp.done=true;w.constructionMetrics.repaired++;w.invalidateStructureRegion(target.x,target.y)}return null}if(p.done)return null;if(sim&&isBlockingPlan(p)&&!placementPreservesAccess(sim,p)){p.progress=.92;p.reserved=false;return null}const cat=PIECE_CATALOG[p.pieceType]||PIECE_CATALOG[PIECE.FLOOR],maxDur=(cat.durability||1)*materialDurability(p.materialStyle),record={type:p.pieceType,x:Math.floor(p.x),y:Math.floor(p.y),ownerUid:bp.owner,group:bp.group,material:p.material,materialStyle:p.materialStyle,layer:p.layer,durability:maxDur,maxDurability:maxDur,open:p.pieceType===PIECE.DOOR||p.pieceType===PIECE.GATE?false:undefined,burning:false,builtTick:sim?.tick||0,inventory:cat.container?new Float32Array(RESOURCE.COUNT):undefined,lots:cat.container?[]:undefined};placePieceRecord(w,record,true);p.done=true;p.progress=1;p.reserved=false;w.constructionMetrics.placed++;bp.lastTouched=sim?.tick||bp.lastTouched;let built=null;if(bp.pieces.every(x=>x.done)){bp.done=true;built=baseAddBuilding.call(w,bp.type,bp.cx,bp.cy,false,bp.owner);built.finished=true;built.phaseG=true;built.group=bp.group;if(sim)sim.log?.('construção',`${sim.npcs.names[sim.npcs.indexByUid(bp.owner)]||'Um grupo'} concluiu ${BUILDING.NAMES[bp.type]}.`,.78,sim.npcs.indexByUid(bp.owner))}return built}
function materialDurability(style){return style===MATERIAL.STONE?1.7:style===MATERIAL.MUD?.78:style===MATERIAL.THATCH?.55:style===MATERIAL.METAL?2.2:1}
function placePieceRecord(w,raw,invalidate=true){const id=raw.id||w.nextPieceId++,p={id,...raw};if(id>=w.nextPieceId)w.nextPieceId=id+1;w.pieceStore[id]=p;const idx=w.inside(p.x,p.y)?w.idx(p.x,p.y):-1;if(idx>=0&&p.layer!=='roof'&&p.layer!=='fixture'){w.structure[idx]=id;const sim=w._constructionSim,oi=sim?.npcs?.indexByUid?.(p.ownerUid)??-1;w.structureOwner[idx]=oi}if(invalidate)w.invalidateStructureRegion?.(p.x,p.y);mirrorBlock(w,p);return p}
function mirrorBlock(w,p){if(p.layer==='roof'||p.layer==='fixture'&&![PIECE.FIRE,PIECE.WELL].includes(p.type))return;const existing=w.blocks.find(b=>b.phaseGId===p.id);if(existing){existing.hp=p.durability/p.maxDurability;return}w.blocks.push({x:p.x,y:p.y,type:compatBlock(p.type),hp:p.durability/p.maxDurability,buildingId:-1,phaseGId:p.id,material:p.materialStyle})}

function recomputeRoomsAround(w,x,y){ensureConstruction(w);const touched=new Set();for(let yy=Math.max(0,y-8);yy<=Math.min(MAP_H-1,y+8);yy++)for(let xx=Math.max(0,x-8);xx<=Math.min(MAP_W-1,x+8);xx++){const rid=w.roomAtTile[w.idx(xx,yy)];if(rid>=0)touched.add(rid);w.roomAtTile[w.idx(xx,yy)]=-1}for(const rid of touched)w.roomCache.delete(rid);const starts=[];for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const sx=x+dx,sy=y+dy;if(w.inside(sx,sy)&&isRoomFloor(w,sx,sy))starts.push([sx,sy])}for(const [sx,sy] of starts)detectRoom(w,sx,sy);w.constructionMetrics.roomRebuilds++}
function rebuildAllRooms(w){ensureConstruction(w);w.roomCache.clear();w.roomAtTile.fill(-1);for(let y=1;y<MAP_H-1;y++)for(let x=1;x<MAP_W-1;x++)if(w.roomAtTile[w.idx(x,y)]<0&&isRoomFloor(w,x,y))detectRoom(w,x,y);w._roomDirty=false}
function detectRoom(w,sx,sy){if(!isRoomFloor(w,sx,sy))return null;const q=[[sx,sy]],tiles=[],seen=new Set([`${sx},${sy}`]);let open=false;while(q.length&&tiles.length<=ROOM_LIMIT){const [x,y]=q.shift();tiles.push(w.idx(x,y));if(x<=0||y<=0||x>=MAP_W-1||y>=MAP_H-1){open=true;break}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(boundaryBlocks(w,nx,ny))continue;const key=`${nx},${ny}`;if(seen.has(key))continue;seen.add(key);q.push([nx,ny])}}if(open||tiles.length>ROOM_LIMIT)return null;let roofed=0,doors=0,fire=false;for(const id of tiles){const x=id%MAP_W,y=(id/MAP_W)|0;if(hasRoof(w,x,y))roofed++;for(const p of fixturesAt(w,x,y)){if(p.type===PIECE.FIRE)fire=true}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const pid=w.structure[w.idx(x+dx,y+dy)],p=w.pieceStore[pid];if(p?.type===PIECE.DOOR)doors++}}const coverage=roofed/Math.max(1,tiles.length);if(coverage<.55)return null;const rid=roomIdFromTiles(tiles),seal=clamp(.68+coverage*.25-Math.min(.22,doors*.018),0,1),room={id:rid,tiles,area:tiles.length,coverage,seal,hasFire:fire,insulation:clamp(.18+seal*.38+coverage*.18+(fire?.12:0),0,.76)};w.roomCache.set(rid,room);for(const id of tiles)w.roomAtTile[id]=rid;return room}
function roomIdFromTiles(tiles){let h=2166136261;for(const id of tiles.slice().sort((a,b)=>a-b)){h^=id;h=Math.imul(h,16777619)}return h&0x7fffffff}
function boundaryBlocks(w,x,y){if(!w.inside(x,y))return false;const id=w.structure[w.idx(x,y)],p=w.pieceStore[id];if(!p||p.durability<=0)return false;if(p.type===PIECE.DOOR||p.type===PIECE.GATE)return !p.open;return[PIECE.WALL,PIECE.PILLAR,PIECE.FENCE,PIECE.BRANCH_SHELTER].includes(p.type)}
function isRoomFloor(w,x,y){if(!w.inside(x,y))return false;const t=w.tile(x,y);if(t===TILE_TYPE.WATER||t===TILE_TYPE.MOUNTAIN)return false;if(boundaryBlocks(w,x,y))return false;return w.pieceStore.some(p=>p&&p.type===PIECE.FLOOR&&p.x===x&&p.y===y&&p.durability>0)||w.structure[w.idx(x,y)]===0}
function hasRoof(w,x,y){return w.pieceStore.some(p=>p&&p.layer==='roof'&&p.x===x&&p.y===y&&p.durability>0)}
function fixturesAt(w,x,y){return w.pieceStore.filter(p=>p&&p.layer==='fixture'&&p.x===x&&p.y===y&&p.durability>0)}

function constructionTick(sim){const w=ensureConstruction(sim);if(w._lastConstructionTick===sim.tick)return;w._lastConstructionTick=sim.tick;toggleDoors(sim);if(sim.tick%60===0){degradeAndFire(sim);dryRooms(sim);chestTick(sim)}if(sim.tick%(DAY_TICKS/2|0)===0){ensureMaintenanceProjects(sim);propertyTick(sim)}if(sim.tick%DAY_TICKS===0||w._territoryDirty)rebuildTerritory(sim);if(sim.tick%120===0)territoryContactTick(sim);decayAbandonedProjects(sim)}
function toggleDoors(sim){if(sim.tick%60!==0)return;const closed=sim.meta?.().phase==='noite'||sim.meta?.().phase==='madrugada';for(const p of sim.world.pieceStore)if(p&&(p.type===PIECE.DOOR||p.type===PIECE.GATE)&&p.open===closed){p.open=!closed;sim.world.invalidateStructureRegion(p.x,p.y)}}
function degradeAndFire(sim){const w=sim.world;for(const p of w.pieceStore){if(!p||p.durability<=0)continue;const id=w.idx(p.x,p.y),moist=w.moisture?.[id]??.5,wind=Math.abs(w.wind?.dx||0)+Math.abs(w.wind?.dy||0),exposure=p.layer==='roof'||p.type===PIECE.WALL||p.type===PIECE.FENCE;let decay=exposure?(.000018+moist*.000028+wind*.000004):.000004;if(p.materialStyle===MATERIAL.STONE)decay*=.22;if(p.materialStyle===MATERIAL.MUD&&moist>.55)decay*=2.4;if(p.materialStyle===MATERIAL.THATCH)decay*=1.7;p.durability=Math.max(0,p.durability-decay*60);if(p.burning){p.durability=Math.max(0,p.durability-.008);spreadFire(sim,p)}else if(flammable(p)&&nearLiveFire(w,p.x,p.y)&&moist<.42&&noiseHash(p.id,Math.floor(sim.tick/60),sim.seed+1701)<.0009)p.burning=true;if(p.durability<=0)collapsePiece(sim,p);else mirrorBlock(w,p)}}
function flammable(p){return p.materialStyle===MATERIAL.WOOD||p.materialStyle===MATERIAL.THATCH||p.type===PIECE.BED||p.type===PIECE.CHEST}
function nearLiveFire(w,x,y){return w.pieceStore.some(p=>p&&p.type===PIECE.FIRE&&p.durability>0&&Math.hypot(p.x-x,p.y-y)<=1.5)||w.buildings.some(b=>b.finished&&b.type===BUILDING.CAMPFIRE&&b.lit&&Math.hypot(b.x-x,b.y-y)<=1.5)}
function spreadFire(sim,p){const w=sim.world;for(const q of w.pieceStore)if(q&&q.id!==p.id&&q.durability>0&&flammable(q)&&Math.hypot(q.x-p.x,q.y-p.y)<=1.45&&!q.burning&&sim.rng.chance(.035)){q.burning=true;w.constructionMetrics.fires++;sim.log?.('incêndio',`O fogo se espalhou pelas estruturas de ${MATERIAL.NAMES[q.materialStyle]||'material combustível'}.`,.9)}}
function collapsePiece(sim,p){const w=sim.world,idx=w.inside(p.x,p.y)?w.idx(p.x,p.y):-1;if(idx>=0&&w.structure[idx]===p.id){w.structure[idx]=0;w.structureOwner[idx]=-1}w.blocks=w.blocks.filter(b=>b.phaseGId!==p.id);w.constructionMetrics.collapsed++;w.invalidateStructureRegion(p.x,p.y);if(p.burning)sim.log?.('ruína','Uma peça estrutural consumida pelo fogo desabou.',.72)}
function dryRooms(sim){const p=sim.npcs.phaseF;if(!p)return;for(const i of sim.npcs.living()){const r=roomAt(sim.world,sim.npcs.x[i],sim.npcs.y[i]);if(r)p.wetness[i]=Math.max(0,p.wetness[i]-(r.hasFire?.055:.018))}}

function ensureMaintenanceProjects(sim,onlyGroup=null){const w=sim.world;for(const p of w.pieceStore){if(!p||p.durability<=0||p.durability/p.maxDurability>=.7||(onlyGroup!=null&&p.group!==onlyGroup))continue;if(w.blueprints.some(b=>!b.done&&b.repairTarget===p.id))continue;const cost=(PIECE_CATALOG[p.type]?.cost||.2)*.22,bp={id:w.blueprints.length,type:-1,cx:p.x,cy:p.y,owner:p.ownerUid,group:p.group,repairTarget:p.id,createdTick:sim.tick,lastTouched:sim.tick,done:false,abandoned:false,pieces:[makePlanPiece(p.x,p.y,p.type,p.materialStyle,p.ownerUid,p.group,{material:p.material,cost,work:20,tech:PIECE_CATALOG[p.type]?.tech??1,tool:PIECE_CATALOG[p.type]?.tool??TOOL.NONE})]};bp.pieces[0].repairId=p.id;w.blueprints.push(bp)}}
function decayAbandonedProjects(sim){const w=sim.world;if(sim.tick%DAY_TICKS!==0)return;for(const bp of w.blueprints)if(!bp.done&&!bp.abandoned&&sim.tick-(bp.lastTouched||bp.createdTick)>DAY_TICKS*6){for(const p of bp.pieces)if(!p.done){p.progress=Math.max(0,p.progress-.035);p.reserved=false}if(sim.tick-(bp.lastTouched||bp.createdTick)>DAY_TICKS*35&&bp.pieces.every(p=>!p.done&&p.progress<=.01))bp.abandoned=true}}

function rebuildTerritory(sim){const w=sim.world;w.territoryOwner.fill(-1);w.territoryStrength.fill(0);for(const p of w.pieceStore){if(!p||p.durability<=0||p.group==null)continue;let local=0;for(const q of w.pieceStore)if(q&&q.group===p.group&&q.durability>0&&Math.hypot(q.x-p.x,q.y-p.y)<5)local++;const rad=2+Math.min(5,Math.floor(local/4));for(let dy=-rad;dy<=rad;dy++)for(let dx=-rad;dx<=rad;dx++){const x=p.x+dx,y=p.y+dy;if(!w.inside(x,y))continue;const d=Math.hypot(dx,dy);if(d>rad+.2)continue;const id=w.idx(x,y),s=Math.max(1,Math.round((rad+1-d)*5));if(w.territoryOwner[id]===p.group)w.territoryStrength[id]=Math.min(255,w.territoryStrength[id]+s);else if(s>w.territoryStrength[id]){w.territoryOwner[id]=p.group;w.territoryStrength[id]=s}}}w._territoryDirty=false}
function territoryContactTick(sim){const w=sim.world;if(w._territoryDirty)rebuildTerritory(sim);w.territoryEvents=w.territoryEvents||[];for(const i of sim.npcs.living()){const own=groupForNpc(sim,i),foreign=w.territoryOwner[w.idx(sim.npcs.x[i],sim.npcs.y[i])];if(foreign<0||foreign===own)continue;const key=`${own}:${foreign}`,last=w._frontierLast?.[key]??-99999;if(!w._frontierLast)w._frontierLast={};if(sim.tick-last<DAY_TICKS*2)continue;w._frontierLast[key]=sim.tick;w.constructionMetrics.frontierContacts++;w.territoryEvents.push({tick:sim.tick,visitor:sim.npcs.uid[i],from:own,to:foreign});if(w.territoryEvents.length>240)w.territoryEvents.shift();sim.memory?.remember?.(i,{type:'fronteira',text:'Entrei numa área marcada pelas construções de outro grupo.',tick:sim.tick,valence:-1,importance:.48,reflectionKey:'território'})}}

function chestTick(sim){const w=sim.world,n=sim.npcs;for(const i of n.living()){const chest=nearestChest(sim,i,2.2,true);if(!chest)continue;withdrawForNeed(sim,i,chest);autoStore(sim,i,chest)}for(const chest of w.pieceStore)if(chest?.type===PIECE.CHEST)ageChestFood(sim,chest)}
function nearestChest(sim,i,rad=3,access=false){const w=sim.world,n=sim.npcs;let best=null,bd=rad;for(const p of w.pieceStore)if(p?.type===PIECE.CHEST&&p.durability>0){const d=Math.hypot(p.x-n.x[i],p.y-n.y[i]);if(d<bd&&(!access||canAccessChest(sim,i,p))){best=p;bd=d}}return best}
export function canAccessChest(sim,i,chest){const n=sim.npcs;if(chest.ownerUid===n.uid[i])return true;if(chest.group!==groupForNpc(sim,i))return false;const j=n.indexByUid(chest.ownerUid);if(j<0)return true;const kin=n.parents[i]?.includes(chest.ownerUid)||n.parents[j]?.includes(n.uid[i]),r=sim.memory.relation(i,j);return kin||(r.trust||0)>.22||(r.affection||0)>.35}
function autoStore(sim,i,chest){const n=sim.npcs,inv=n.inventory[i];for(let k=0;k<inv.length;k++){const keep=k===RESOURCE.WATER?.3:FOOD_KINDS.has(k)?.22:.14;if(inv[k]<=keep+.08)continue;const amt=Math.min(inv[k]-keep,.28);inv[k]-=amt;if(FOOD_KINDS.has(k)){chest.lots=chest.lots||[];chest.lots.push({kind:k,amount:amt,born:sim.tick,state:0})}else{chest.inventory=chest.inventory||new Float32Array(RESOURCE.COUNT);chest.inventory[k]+=amt}}}
function withdrawForNeed(sim,i,chest){const n=sim.npcs,inv=n.inventory[i];if(n.need(i,0)>.55&&sumFood(inv)<.12){const lot=(chest.lots||[]).find(l=>l.amount>.04&&l.state<3);if(lot){const amt=Math.min(.14,lot.amount);lot.amount-=amt;inv[lot.kind]+=amt}}if(n.need(i,1)>.55&&(chest.inventory?.[RESOURCE.WATER]||0)>.08){const amt=Math.min(.16,chest.inventory[RESOURCE.WATER]);chest.inventory[RESOURCE.WATER]-=amt;inv[RESOURCE.WATER]+=amt}}
function ageChestFood(sim,chest){if(sim.tick%DAY_TICKS!==0)return;const room=roomAt(sim.world,chest.x,chest.y),factor=room?.coverage>.6?.55:1;for(const lot of chest.lots||[]){const days=(sim.tick-lot.born)/DAY_TICKS,base=lot.kind===RESOURCE.FISH?2:lot.kind===RESOURCE.MILK?2:lot.kind===RESOURCE.MEAT?4:lot.kind===RESOURCE.BERRY?5:lot.kind===RESOURCE.GRAIN?90:18,ratio=days*factor/base;lot.state=ratio<.6?0:ratio<1?1:ratio<1.45?2:3;if(lot.state===3)lot.amount=0}chest.lots=(chest.lots||[]).filter(l=>l.amount>.01)}
function propertyTick(sim){const n=sim.npcs,w=sim.world;for(const i of n.living()){const hunger=n.need(i,0),greed=n.gene(i,GENE.GREED),loyal=n.gene(i,GENE.LOYALTY);if(hunger>.72){const chest=nearestForeignChest(sim,i,2.5);if(chest){const owner=n.indexByUid(chest.ownerUid),rel=owner>=0?sim.memory.relation(i,owner):null,score=hunger*.58+greed*.45-loyal*.28-(rel?.fear||0)*.22-(rel?.affection||0)*.16;if(score>.72&&sim.rng.chance(.24)){const lot=(chest.lots||[]).find(l=>l.amount>.05&&l.state<3);if(lot){const amt=Math.min(.12,lot.amount);lot.amount-=amt;n.inventory[i][lot.kind]+=amt;w.constructionMetrics.thefts++;sim.log?.('roubo',`${n.names[i]} roubou comida de um baú alheio.`,.72,i);if(owner>=0){sim.memory.adjust(owner,i,{trust:-.1,affection:-.06,fear:.02});sim.memory.adjust(i,owner,{debt:.03})}}}}}if(sumFood(n.inventory[i])>.9&&n.gene(i,GENE.EMPATHY)>.45){let target=-1;for(const j of n.living())if(j!==i&&n.need(j,0)>.74&&Math.hypot(n.x[i]-n.x[j],n.y[i]-n.y[j])<2.5){const r=sim.memory.relation(i,j);if((r.affection||0)>.05||(r.trust||0)>.08){target=j;break}}if(target>=0&&sim.rng.chance(.22)){const kind=[RESOURCE.BERRY,RESOURCE.GRAIN,RESOURCE.PRESERVED,RESOURCE.MEAT,RESOURCE.FISH].find(k=>n.inventory[i][k]>.16);if(kind!=null){n.inventory[i][kind]-=.12;n.inventory[target][kind]+=.12;w.constructionMetrics.gifts++;sim.log?.('dádiva',`${n.names[i]} dividiu comida com ${n.names[target]}.`,.62,i);sim.memory.adjust(target,i,{trust:.06,affection:.04,debt:.06})}}}}}
function nearestForeignChest(sim,i,rad){let best=null,bd=rad;const n=sim.npcs,g=groupForNpc(sim,i);for(const p of sim.world.pieceStore)if(p?.type===PIECE.CHEST&&p.durability>0&&p.ownerUid!==n.uid[i]&&p.group!==g){const d=Math.hypot(p.x-n.x[i],p.y-n.y[i]);if(d<bd&&(p.lots||[]).some(l=>l.amount>.05)){best=p;bd=d}}return best}
function sumFood(inv){let s=0;for(const k of FOOD_KINDS)s+=inv[k]||0;return s}
function inventoryLoad(inv){let s=0;for(const v of inv)s+=v||0;return Math.min(1,s/5)}
