import {ACTION,RESOURCE,NEED,BUILDING,TOOL,ARMOR,NUTRITION,TILE_TYPE} from '../core/constants.js';
import {finishIntent,actionSkill} from './actions.js';
import {socialLine} from '../narrative/templates.js';
const workActions=new Set([ACTION.FORAGE,ACTION.WATER,ACTION.WOOD,ACTION.STONE,ACTION.IRON,ACTION.FARM,ACTION.FISH,ACTION.HUNT,ACTION.COOK,ACTION.TAILOR,ACTION.FORGE,ACTION.CARE,ACTION.SOCIAL,ACTION.BUILD,ACTION.DUNGEON,ACTION.FIGHT]);
export function executeTick(sim,i){const n=sim.npcs,w=sim.world,int=n.intent[i];if(!int)return;const a=int.action;if(a===ACTION.DUNGEON)consumeTravelSupplies(sim,i);if(a===ACTION.EAT)return eat(sim,i);if(a===ACTION.DRINK)return drink(sim,i);if(a===ACTION.IDLE){if(sim.tick-int.started>10)finishIntent(sim,i,true);return}
 if(dynamicTarget(sim,i,int)===false){finishIntent(sim,i,false);return}
 const distance=Math.hypot(int.targetX-n.x[i],int.targetY-n.y[i]);const arrival=a===ACTION.FIGHT||a===ACTION.HUNT?.75:a===ACTION.SOCIAL||a===ACTION.CARE?1.05:.72;if(distance>arrival){moveAlongRoute(sim,i,int);return}
 n.moving[i]=0;if(a===ACTION.SLEEP){n.setNeed(i,NEED.SLEEP,n.need(i,NEED.SLEEP)-.006);n.stamina[i]=Math.min(1,n.stamina[i]+.012);n.hp[i]=Math.min(1,n.hp[i]+.0008);n.progress[i]=Math.min(1,n.progress[i]+.012);if(n.need(i,NEED.SLEEP)<.16||n.progress[i]>=1)finishIntent(sim,i,true);return}
 if(a===ACTION.WARM){n.setNeed(i,NEED.TEMP,n.need(i,NEED.TEMP)-.008);n.progress[i]=Math.min(1,n.progress[i]+.02);if(n.need(i,NEED.TEMP)<.15||n.progress[i]>=1)finishIntent(sim,i,true);return}
 if(a===ACTION.FLEE){n.setNeed(i,NEED.SAFETY,n.need(i,NEED.SAFETY)-.35);finishIntent(sim,i,true);return}
 const sk=actionSkill(a),skill=sk==null?0:n.skill(i,sk),toolBonus=toolEfficiency(n.tool[i],a),fatigue=.45+n.stamina[i]*.55,rate=(.008+skill*.006)*toolBonus*fatigue/int.required;n.progress[i]=Math.min(1,n.progress[i]+rate);if(workActions.has(a)){n.stamina[i]=Math.max(0,n.stamina[i]-.0008*(1.1-skill*.25));if(sk!=null)n.addSkill(i,sk,.00013)}if(n.progress[i]<1)return;resolveWork(sim,i,int)}
function dynamicTarget(sim,i,int){const n=sim.npcs;if(int.action===ACTION.SOCIAL||int.action===ACTION.CARE){if(int.targetId<0||!n.alive[int.targetId])return false;int.targetX=n.x[int.targetId];int.targetY=n.y[int.targetId]}else if(int.action===ACTION.HUNT){const a=sim.animals.byId(int.targetId);if(!a)return false;int.targetX=a.x;int.targetY=a.y}else if(int.action===ACTION.FIGHT){const t=int.meta.targetType==='animal'?sim.animals.byId(int.targetId):sim.world.monsters.find(m=>m.id===int.targetId&&m.hp>0);if(!t)return false;int.targetX=t.x;int.targetY=t.y}return true}
function moveAlongRoute(sim,i,int){const n=sim.npcs,w=sim.world;let route=n.route[i],ri=n.routeIndex[i];if(!route.length||ri>=route.length){route=w.pathfinder.find(n.x[i],n.y[i],int.targetX,int.targetY);n.route[i]=route;n.routeIndex[i]=0;ri=0;if(!route.length){const d=Math.hypot(int.targetX-n.x[i],int.targetY-n.y[i]);if(d>1.5){finishIntent(sim,i,false);return}}}const p=route[ri]||[int.targetX,int.targetY],dx=p[0]-n.x[i],dy=p[1]-n.y[i],d=Math.hypot(dx,dy);if(d<.11){n.routeIndex[i]++;return}const base=.028+n.derived(i).speed*.035,load=inventoryLoad(n.inventory[i]),wound=1-n.wound[i]*.45,stamina=.55+n.stamina[i]*.45,speed=base*w.moveFactor(n.x[i],n.y[i])*(1-load*.3)*wound*stamina;const step=Math.min(speed,d);n.x[i]+=dx/d*step;n.y[i]+=dy/d*step;n.moving[i]=1;n.facing[i]=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);n.stamina[i]=Math.max(0,n.stamina[i]-.00008);w.walkTile(n.x[i],n.y[i],.018);sim.autoDeposit(i)}
function eat(sim,i){const n=sim.npcs,w=sim.world;let food=null;for(const k of [RESOURCE.BERRY,RESOURCE.GRAIN,RESOURCE.MEAT,RESOURCE.FISH,RESOURCE.EGG,RESOURCE.MILK,RESOURCE.PRESERVED])if(n.inventory[i][k]>.1){const amount=Math.min(.14,n.inventory[i][k]);n.inventory[i][k]-=amount;food={kind:k,amount};break}if(!food)food=w.consumeFood(sim.tick);if(!food){finishIntent(sim,i,false);return}n.setNeed(i,NEED.HUNGER,n.need(i,NEED.HUNGER)-.58);if(food.kind===RESOURCE.BERRY)n.addNutrition(i,NUTRITION.PLANT,.2);else if(food.kind===RESOURCE.GRAIN)n.addNutrition(i,NUTRITION.GRAIN,.2);else if([RESOURCE.MEAT,RESOURCE.FISH,RESOURCE.EGG,RESOURCE.MILK].includes(food.kind))n.addNutrition(i,NUTRITION.PROTEIN,.22);else{n.addNutrition(i,NUTRITION.PROTEIN,.1);n.addNutrition(i,NUTRITION.PLANT,.08)}finishIntent(sim,i,true)}
function drink(sim,i){const n=sim.npcs,w=sim.world;if(n.inventory[i][RESOURCE.WATER]>.08)n.inventory[i][RESOURCE.WATER]-=.09;else if(w.stock[RESOURCE.WATER]>.09)w.stock[RESOURCE.WATER]-=.09;else{finishIntent(sim,i,false);return}n.setNeed(i,NEED.THIRST,n.need(i,NEED.THIRST)-.72);finishIntent(sim,i,true)}
function resolveWork(sim,i,int){const n=sim.npcs,w=sim.world,a=int.action;if([ACTION.FORAGE,ACTION.WATER,ACTION.WOOD,ACTION.STONE,ACTION.IRON,ACTION.FISH].includes(a)){const r=w.findResourceAt(int.sourceX,int.sourceY,int.targetKind,1.2);if(!r){sim.memory.observe(i,w.idx(int.sourceX,int.sourceY),sim.tick,0,0,sim.memory.spatialCapacity(n,i));sim.memory.remember(i,{type:'erro de memória',text:'Fui até um recurso lembrado, mas ele já não estava lá.',tick:sim.tick,valence:-2,importance:.55,reflectionKey:'memória espacial'});finishIntent(sim,i,false);return}let amount=a===ACTION.WATER?.7:a===ACTION.FISH?.32:.42+n.skill(i,actionSkill(a)??0)*.3;if(a===ACTION.WOOD&&n.tool[i]===TOOL.AXE)amount*=1.45;if((a===ACTION.STONE||a===ACTION.IRON)&&n.tool[i]===TOOL.PICK)amount*=1.45;const got=w.harvest(r,amount);n.inventory[i][int.targetKind]+=got;if(a===ACTION.FORAGE)sim.memory.remember(i,{type:'coleta',text:'Encontrei frutos silvestres nesta região.',tick:sim.tick,valence:1,importance:.3,reflectionKey:'comida'});finishIntent(sim,i,got>0);sim.autoDeposit(i,true);return}
 if(a===ACTION.HUNT){const prey=sim.animals.byId(int.targetId);if(!prey){finishIntent(sim,i,false);return}const hit=.18+n.skill(i,3)*.22+(n.tool[i]===TOOL.BOW?.2:n.tool[i]===TOOL.KNIFE?.08:0);prey.hp-=hit;if(prey.hp<=0){sim.animals.killForLoot(sim,prey,i);finishIntent(sim,i,true)}else{n.progress[i]=0;prey.state='fugir';int.targetX=prey.x;int.targetY=prey.y}return}
 if(a===ACTION.FARM){const farm=w.buildings.find(b=>b.id===int.targetId);if(!farm){finishIntent(sim,i,false);return}farm.crop=farm.crop||{planted:0,ready:0};if(!farm.crop.planted){if(w.stock[RESOURCE.SEED]<.15){finishIntent(sim,i,false);return}w.stock[RESOURCE.SEED]-=.15;farm.crop.planted=sim.tick;farm.crop.ready=sim.tick+840*2;sim.addBubble(i,'fala','Plantamos agora. A terra precisa de tempo.',.55);finishIntent(sim,i,true)}else if(sim.tick>=farm.crop.ready){const yieldAmt=1.1+n.skill(i,2)*1.4;w.addFoodBatch(RESOURCE.GRAIN,yieldAmt,sim.tick);w.stock[RESOURCE.SEED]+=.28+n.skill(i,2)*.08;farm.crop={planted:0,ready:0};finishIntent(sim,i,true)}else finishIntent(sim,i,true);return}
 if(a===ACTION.COOK){const k=w.stock[RESOURCE.MEAT]>.3?RESOURCE.MEAT:w.stock[RESOURCE.FISH]>.3?RESOURCE.FISH:null;if(k==null||w.stock[RESOURCE.LOG]<.08){finishIntent(sim,i,false);return}w.stock[k]-=.3;w.stock[RESOURCE.LOG]-=.08;w.addFoodBatch(RESOURCE.PRESERVED,.28,sim.tick);finishIntent(sim,i,true);return}
 if(a===ACTION.TAILOR){if(n.armor[i]!==ARMOR.NONE){finishIntent(sim,i,true);return}if(w.stock[RESOURCE.LEATHER]>=.6){w.stock[RESOURCE.LEATHER]-=.6;n.armor[i]=ARMOR.LEATHER}else if(w.stock[RESOURCE.WOOL]>=.8){w.stock[RESOURCE.WOOL]-=.8;n.armor[i]=ARMOR.CLOTH}else{finishIntent(sim,i,false);return}finishIntent(sim,i,true);return}
 if(a===ACTION.FORGE){if(w.stock[RESOURCE.IRON]<.65||w.stock[RESOURCE.LOG]<.15){finishIntent(sim,i,false);return}w.stock[RESOURCE.IRON]-=.65;w.stock[RESOURCE.LOG]-=.15;const order=[TOOL.AXE,TOOL.PICK,TOOL.HAMMER,TOOL.SWORD,TOOL.BOW,TOOL.KNIFE,TOOL.ROD],tool=order.sort((x,y)=>w.tools[x]-w.tools[y])[0];w.tools[tool]++;sim.log('produção',`${n.names[i]} forjou ${['','um machado','uma picareta','um martelo','uma faca','uma vara','um arco','uma espada'][tool]}.`,.6,i);finishIntent(sim,i,true);return}
 if(a===ACTION.CARE){const j=int.targetId;if(j<0||!n.alive[j]){finishIntent(sim,i,false);return}n.wound[j]=Math.max(0,n.wound[j]-.24-n.skill(i,12)*.2);n.infection[j]=Math.max(0,n.infection[j]-.18);n.hp[j]=Math.min(1,n.hp[j]+.035);sim.memory.adjust(j,i,{trust:.05,affection:.03,debt:.04});finishIntent(sim,i,true);return}
 if(a===ACTION.SOCIAL){const j=int.targetId;if(j<0||!n.alive[j]){finishIntent(sim,i,false);return}const warmth=.012+n.gene(i,21)*.016;sim.memory.adjust(i,j,{affection:warmth,trust:warmth*.65});sim.memory.adjust(j,i,{affection:warmth*.75,trust:warmth*.45});const shared=sim.rng.chance(1-n.gene(i,18)*.5)?sim.memory.shareSpatial(i,j,sim.rng,sim.tick,sim.memory.spatialCapacity(n,j)):null;const belief=(sim.memory.beliefs.get(i)||[]).filter(b=>String(b.key).startsWith('dungeon:')).sort((a,b)=>Math.abs(b.valence)-Math.abs(a.valence))[0];if(belief&&sim.rng.chance(.35)){sim.memory.learn(j,{key:`rumor:${belief.key}`,text:belief.text,tick:sim.tick,confidence:.5});sim.memory.remember(j,{type:'rumor',text:`${n.names[i]} compartilhou uma crença sobre uma dungeon.`,tick:sim.tick,valence:belief.valence*.5,importance:.55,reflectionKey:belief.key})}const line=socialLine(sim,i,j,shared);sim.addBubble(i,'fala',line,.75);sim.memory.remember(i,{type:'conversa',text:`Conversei com ${n.names[j]}.`,tick:sim.tick,valence:2,importance:.38,reflectionKey:`pessoa:${j}`});sim.memory.remember(j,{type:'conversa',text:`${n.names[i]} conversou comigo.`,tick:sim.tick,valence:2,importance:.38,reflectionKey:`pessoa:${i}`});n.setNeed(i,NEED.SOCIAL,n.need(i,NEED.SOCIAL)-.5);n.setNeed(j,NEED.SOCIAL,n.need(j,NEED.SOCIAL)-.25);finishIntent(sim,i,true);return}
 if(a===ACTION.BUILD){const bp=w.blueprints[int.meta.blueprint],p=bp?.pieces[int.meta.pieceIndex];if(!p||p.done){finishIntent(sim,i,false);return}if(!p.reserved){if(w.stock[p.material]<p.cost){finishIntent(sim,i,false);return}w.stock[p.material]-=p.cost;p.reserved=true}p.progress=1;const built=w.completePiece(bp,p);if(built)sim.log('construção',`${n.names[i]} concluiu ${BUILDING.NAMES[built.type]}.`,.78,i);finishIntent(sim,i,true);return}
 if(a===ACTION.DUNGEON){sim.dungeon.attempt(sim,i,int.targetId);finishIntent(sim,i,true);return}
 if(a===ACTION.FIGHT){const t=int.meta.targetType==='animal'?sim.animals.byId(int.targetId):w.monsters.find(m=>m.id===int.targetId&&m.hp>0);if(!t){finishIntent(sim,i,true);return}const damage=.08+n.derived(i).strength*.06+n.skill(i,10)*.08+(n.tool[i]===TOOL.SWORD?.1:n.tool[i]===TOOL.BOW?.07:0);t.hp-=damage;if(t.hp<=0){if(int.meta.targetType==='animal')sim.animals.killForLoot(sim,t,i);else{n.prestige[i]+=2;sim.log('combate',`${n.names[i]} derrotou uma criatura noturna.`,.7,i)}finishIntent(sim,i,true)}else{n.progress[i]=0;if(sim.rng.chance(.25)){n.wound[i]=Math.min(1,n.wound[i]+.05+(t.power||.2)*.05);n.hp[i]-=.008+(t.power||.2)*.015}}return}
 if(a===ACTION.EXPLORE||a===ACTION.FLEE||a===ACTION.RETURN){finishIntent(sim,i,true);return}finishIntent(sim,i,true)}

function consumeTravelSupplies(sim,i){const n=sim.npcs,inv=n.inventory[i];if(n.need(i,NEED.THIRST)>.58&&inv[RESOURCE.WATER]>.06){inv[RESOURCE.WATER]-=.06;n.setNeed(i,NEED.THIRST,n.need(i,NEED.THIRST)-.42)}if(n.need(i,NEED.HUNGER)>.58){for(const k of [RESOURCE.BERRY,RESOURCE.GRAIN,RESOURCE.PRESERVED,RESOURCE.MEAT,RESOURCE.FISH,RESOURCE.EGG])if(inv[k]>.06){inv[k]-=.06;n.setNeed(i,NEED.HUNGER,n.need(i,NEED.HUNGER)-.32);break}}}
function toolEfficiency(tool,action){if(action===ACTION.WOOD)return tool===TOOL.AXE?1.8:.65;if(action===ACTION.STONE||action===ACTION.IRON)return tool===TOOL.PICK?1.8:.6;if(action===ACTION.BUILD)return tool===TOOL.HAMMER?1.55:.72;if(action===ACTION.FISH)return tool===TOOL.ROD?1.7:.55;if(action===ACTION.HUNT)return tool===TOOL.BOW?1.45:tool===TOOL.KNIFE?1.15:.8;return 1}
function inventoryLoad(inv){let s=0;for(let k=0;k<inv.length;k++)s+=inv[k];return Math.min(1,s/5)}
