import {GENE,DAY_TICKS,RESOURCE,MAX_NPCS,BUILDING} from '../core/constants.js';
import {BALANCE} from '../calibration/balance.js';
import {fertilityFactor} from './survival.js';
const foodKinds=[RESOURCE.GRAIN,RESOURCE.BERRY,RESOURCE.MEAT,RESOURCE.FISH,RESOURCE.PRESERVED,RESOURCE.EGG,RESOURCE.MILK,RESOURCE.FAT];
function carriedFood(n,i){let s=0;for(const k of foodKinds)s+=n.inventory[i][k];return s}
function nearbyShelterCapacity(sim,i,j){const n=sim.npcs,w=sim.world,cx=(n.x[i]+n.x[j])/2,cy=(n.y[i]+n.y[j])/2;let shelters=0;for(const b of w.buildings)if(b.finished&&b.type===BUILDING.SHELTER&&Math.hypot(b.x-cx,b.y-cy)<=10)shelters++;return shelters}
export function socialTick(sim){const n=sim.npcs;if(sim.tick%(DAY_TICKS/2|0)!==0)return;for(const i of n.living()){if(n.age[i]<18||n.age[i]>50)continue;if(n.partner[i]>=0&&n.alive[n.partner[i]])continue;let best=-1,score=.4;for(const j of n.living()){if(i===j||n.sex[i]===n.sex[j]||n.age[j]<18||n.age[j]>50)continue;const d=Math.hypot(n.x[i]-n.x[j],n.y[i]-n.y[j]);if(d>12)continue;const r=sim.memory.relation(i,j),s=(r.affection+.5)*.48+(r.trust+.5)*.2+n.prestige[j]*.002+n.gene(i,GENE.SOCIABILITY)*.18-d*.008;if(s>score){score=s;best=j}}if(best>=0&&sim.rng.chance(.18)){n.partner[i]=best;n.partner[best]=i;sim.log('relação',`${n.names[i]} e ${n.names[best]} formaram um casal.`,.7,i)}}}
export function reproductionTick(sim){if(sim.tick%DAY_TICKS!==0)return;const n=sim.npcs,pop=n.living().length;if(pop>MAX_NPCS*.82)return;for(const i of n.living()){const j=n.partner[i];if(j<0||i>j||!n.alive[j]||n.age[i]<18||n.age[j]<18||n.age[i]>48||n.age[j]>48)continue;const fert=(n.gene(i,GENE.FERTILITY)+n.gene(j,GENE.FERTILITY))*.5,food=carriedFood(n,i)+carriedFood(n,j);if(food<.4)continue;const crowd=Math.max(.08,1-pop/(MAX_NPCS*.9)),shelters=nearbyShelterCapacity(sim,i,j),surplus=C((food-.4)/1.6),housing=shelters?Math.min(1.35,.75+shelters*.15):.55,softFloor=pop<60?1.18:1,softCeiling=pop>200?.72:1,diet=Math.sqrt(fertilityFactor(sim,i)*fertilityFactor(sim,j)),chance=BALANCE.fertilityBase*fert*crowd*(.7+surplus*.6)*housing*softFloor*softCeiling*diet;if(sim.rng.chance(chance)){const c=n.child(sim.rng,i,j,sim.tick);if(c<0)continue;sim.memory.ensure(c,sim.memory.spatialCapacity(n,c));sim.technology?.ensure(c);sim.memory.remember(i,{type:'família',text:`Nasceu ${n.names[c]}, meu filho.`,tick:sim.tick,valence:8,importance:1,reflectionKey:'família'});sim.memory.remember(j,{type:'família',text:`Nasceu ${n.names[c]}, meu filho.`,tick:sim.tick,valence:8,importance:1,reflectionKey:'família'});sim.log('nascimento',`${n.names[c]} nasceu, filho de ${n.names[i]} e ${n.names[j]}.`,1,c)}}}
function C(x){return Math.max(0,Math.min(1,x))}
