import {RNG} from './core/rng.js';
import {dayOf,dayPhase,season,isNight} from './core/clock.js';
import {World} from './world/world.js';
import {NPCStore} from './entities/npcs.js';
import {MemorySystem} from './ai/memory.js';
import {updateNeeds,criticalNeed} from './ai/drives.js';
import {scoreActions,chooseAction} from './ai/utility.js';
import {planFor} from './ai/planner.js';
import {executeAction} from './systems/actions.js';
import {socialTick,reproductionTick} from './systems/social.js';
import {lifecycleTick} from './systems/lifecycle.js';
import {updateProfessions} from './systems/professions.js';
import {Dungeon} from './dungeon/dungeon.js';
import {BUILDING,GENE,RESOURCE,NEED,ACTION,ACTIVE_SKILLS} from './core/constants.js';
const TRAVEL=new Set([ACTION.WARM,ACTION.FORAGE,ACTION.WATER,ACTION.WOOD,ACTION.STONE,ACTION.IRON,ACTION.FARM,ACTION.SOCIAL,ACTION.BUILD,ACTION.CRAFT,ACTION.DEPOSIT,ACTION.FLEE,ACTION.FIGHT,ACTION.DUNGEON]);
const SURVIVAL=new Set([ACTION.EAT,ACTION.DRINK,ACTION.WATER,ACTION.FORAGE,ACTION.WARM,ACTION.FLEE,ACTION.FIGHT]);
export class Simulation{
 constructor(seed=1){this.seed=seed;this.rng=new RNG(seed);this.tick=0;this.world=new World(this.rng);this.npcs=new NPCStore();this.memory=new MemorySystem();this.dungeon=new Dungeon(this.rng);this.chronicle=[];this.populationHistory=[];this.geneHistory=[];this.observer=null;this.metrics={travelStarted:0,travelCompleted:0,travelAbandoned:0,byAction:{}};this.initPopulation()}
 initPopulation(){for(let k=0;k<12;k++){const i=this.npcs.create(this.rng,36+this.rng.range(-5,5),36+this.rng.range(-5,5));if(i<0)break;this.memory.ensure(i);this.memory.learn(i,{key:'vila',text:'A vila é um lugar relativamente seguro.',tick:0,confidence:.7});this.memory.learn(i,{key:'rio',text:'Há água no rio a oeste.',tick:0,confidence:.7})}this.log('fundação','Doze pessoas despertaram no vale sem ordens e sem um destino comum.',.9)}
 setObserver(x,y,radius=20){this.observer={x,y,radius}}
 nearestNPC(i){const n=this.npcs;let best=-1,d=9;for(const j of n.living())if(j!==i){const dd=Math.hypot(n.x[j]-n.x[i],n.y[j]-n.y[i]);if(dd<d){d=dd;best=j}}return best}
 log(type,text,importance=.5,npc=-1){this.chronicle.push({type,text,importance,npc,tick:this.tick,day:dayOf(this.tick)});if(this.chronicle.length>800)this.chronicle.shift()}
 decisionInterval(i,threat=0){const n=this.npcs,base=(i%3)+2;if(n.action[i]===ACTION.SLEEP)return 8;if(!this.observer||n.commitment[i]||threat>.05)return base;let urgent=0;for(let k=0;k<NEED.COUNT;k++)urgent=Math.max(urgent,n.need(i,k));if(urgent>.5)return base;const o=this.observer,d=Math.hypot(n.x[i]-o.x,n.y[i]-o.y);if(d>o.radius*1.8)return 10;if(d>o.radius)return 6;return base}
 emergencyGoal(i,scores,threat){const n=this.npcs;if(threat>.42){const f=scores.find(x=>x[0]===ACTION.FIGHT),r=scores.find(x=>x[0]===ACTION.FLEE);return(f?.[1]||0)>=(r?.[1]||0)?ACTION.FIGHT:ACTION.FLEE}const[k,v]=criticalNeed(n,i);if(k===NEED.THIRST&&v<.56)return null;if(k===NEED.HUNGER&&v<.62)return null;if(k===NEED.TEMP&&v<.82)return null;if(k===NEED.SAFETY&&v<.72)return null;if(![NEED.THIRST,NEED.HUNGER,NEED.TEMP,NEED.SAFETY].includes(k))return null;if(k===NEED.THIRST)return(n.inventory[i][RESOURCE.WATER]>.08||(this.world.stock[RESOURCE.WATER]>.1&&this.world.nearBuilding(n.x[i],n.y[i],BUILDING.STORAGE,4)))?ACTION.DRINK:ACTION.WATER;if(k===NEED.HUNGER)return(n.inventory[i][RESOURCE.FOOD]>.1||(this.world.stock[RESOURCE.FOOD]>.12&&this.world.nearBuilding(n.x[i],n.y[i],BUILDING.STORAGE,4)))?ACTION.EAT:ACTION.FORAGE;if(k===NEED.TEMP)return ACTION.WARM;if(k===NEED.SAFETY)return ACTION.FLEE;return null}
 startCommitment(i,goal,plan){const n=this.npcs,action=plan[0]||goal,duration=Math.round(420+n.gene(i,GENE.STUBBORN)*300);n.commitment[i]={goal,action,until:this.tick+duration,started:this.tick};n.plan[i]=plan;if(TRAVEL.has(action)){this.metrics.travelStarted++;const m=this.metrics.byAction[action]||(this.metrics.byAction[action]={started:0,completed:0,abandoned:0});m.started++}}
 endCommitment(i,status='complete'){const c=this.npcs.commitment[i];if(c&&TRAVEL.has(c.action)){const m=this.metrics.byAction[c.action]||(this.metrics.byAction[c.action]={started:0,completed:0,abandoned:0});if(status==='complete'){this.metrics.travelCompleted++;m.completed++}else{this.metrics.travelAbandoned++;m.abandoned++}}this.npcs.commitment[i]=null;this.npcs.plan[i]=[]}
 advanceCommitment(i,status){const n=this.npcs,c=n.commitment[i];if(!c)return;if(status==='blocked'){this.endCommitment(i,'abandoned');return}if(status!=='complete')return;if(c.action!==c.goal){const plan=planFor(this,i,c.goal);c.action=plan[0]||c.goal;c.until=this.tick+Math.round(360+n.gene(i,GENE.STUBBORN)*260);n.plan[i]=plan;if(TRAVEL.has(c.action)){this.metrics.travelStarted++;const m=this.metrics.byAction[c.action]||(this.metrics.byAction[c.action]={started:0,completed:0,abandoned:0});m.started++}return}this.endCommitment(i,'complete')}
 decide(i,threat){const n=this.npcs,scores=scoreActions(this,i);n.scores[i]=scores.slice(0,5);const emergency=this.emergencyGoal(i,scores,threat),current=n.commitment[i];if(current&&this.tick>current.until)this.endCommitment(i,'abandoned');if(n.commitment[i]&&emergency&&emergency!==n.commitment[i].goal){const c=n.commitment[i],physicalThreat=threat>.42&&(emergency===ACTION.FIGHT||emergency===ACTION.FLEE);if(!SURVIVAL.has(c.goal)||physicalThreat)this.endCommitment(i,'abandoned')}if(!n.commitment[i]){const goal=emergency||chooseAction(this,i,scores);this.startCommitment(i,goal,planFor(this,i,goal))}const c=n.commitment[i],status=executeAction(this,i,c.action);this.advanceCommitment(i,status);updateProfessions(n,i)}
 step(){this.tick++;this.world.tick();this.dungeon.tick(this);const n=this.npcs;for(const i of n.living()){const threat=this.world.threatAt(n.x[i],n.y[i]);updateNeeds(n,i,{night:isNight(this.tick),season:season(this.tick),threat,nearShelter:this.world.nearBuilding(n.x[i],n.y[i],BUILDING.SHELTER)});if(n.age[i]<16){this.childStep(i);continue}if(this.tick%this.decisionInterval(i,threat)===0)this.decide(i,threat);if(this.tick%480===i%480)this.memory.reflect(i,this.tick);this.depositIfHome(i)}socialTick(this);reproductionTick(this);lifecycleTick(this);this.handleMonsters();if(this.tick%240===0)this.snapshotStats();if(this.tick%1200===0)this.applyScarcity()}
 depositIfHome(i){const n=this.npcs,w=this.world;if(!w.nearBuilding(n.x[i],n.y[i],BUILDING.STORAGE,2.2))return;const inv=n.inventory[i];for(const k of [RESOURCE.WOOD,RESOURCE.STONE,RESOURCE.IRON,RESOURCE.WHEAT,RESOURCE.LEATHER,RESOURCE.WATER,RESOURCE.FOOD]){const expedition=n.commitment[i]?.goal===ACTION.DUNGEON;const reserve=(k===RESOURCE.WATER||k===RESOURCE.FOOD)?(expedition?.22:.12):.02;const d=Math.max(0,inv[k]-reserve);if(d>0){w.stock[k]+=d;inv[k]-=d}}}
 childStep(i){const n=this.npcs,p=n.parents[i];let guardian=p?.find(x=>x>=0&&n.alive[x]);if(guardian==null||guardian<0)guardian=n.living().find(x=>x!==i&&n.age[x]>=18)??-1;if(guardian>=0){const d=Math.hypot(n.x[guardian]-n.x[i],n.y[guardian]-n.y[i]);if(d>2){n.x[i]+=(n.x[guardian]-n.x[i])/d*.22;n.y[i]+=(n.y[guardian]-n.y[i])/d*.22}if(n.age[i]>=8&&this.rng.chance(.05)){let best=ACTIVE_SKILLS[0];for(const sk of ACTIVE_SKILLS)if(n.skill(guardian,sk)>n.skill(guardian,best))best=sk;n.addSkill(i,best,.0012)}}n.action[i]=n.age[i]<8?'brincando perto da família':'aprendendo com os adultos';if(n.need(i,NEED.HUNGER)>.55&&this.world.stock[RESOURCE.FOOD]>.1){this.world.stock[RESOURCE.FOOD]-=.08;n.setNeed(i,NEED.HUNGER,n.need(i,NEED.HUNGER)-.35);n.hp[i]=Math.min(1,n.hp[i]+.004)}if(n.need(i,NEED.THIRST)>.55&&this.world.stock[RESOURCE.WATER]>.08){this.world.stock[RESOURCE.WATER]-=.07;n.setNeed(i,NEED.THIRST,n.need(i,NEED.THIRST)-.45);n.hp[i]=Math.min(1,n.hp[i]+.003)}if(n.need(i,NEED.SLEEP)>.6)n.setNeed(i,NEED.SLEEP,n.need(i,NEED.SLEEP)-.05)}
 handleMonsters(){const n=this.npcs;for(const m of this.world.monsters)if(m.hp>0){let best=-1,d=99;for(const i of n.living()){const dd=Math.hypot(n.x[i]-m.x,n.y[i]-m.y);if(dd<d){d=dd;best=i}}if(best>=0&&d>1){m.x+=(n.x[best]-m.x)/d*.12;m.y+=(n.y[best]-m.y)/d*.12}else if(best>=0&&d<=1&&this.rng.chance(.025)){n.hp[best]-=.008+m.power*.012;this.memory.remember(best,{type:'ataque',text:'Uma criatura da dungeon me atacou perto da vila.',tick:this.tick,valence:-7,importance:.85,reflectionKey:'monstros'})}}this.world.monsters=this.world.monsters.filter(m=>m.hp>0&&this.tick-(m.born||this.tick)<720);if(this.world.monsters.length>50)this.world.monsters=this.world.monsters.slice(-50)}
 snapshotStats(){const alive=this.npcs.living();this.populationHistory.push({day:dayOf(this.tick),value:alive.length});const genes=[GENE.AGGRESSION,GENE.CAUTION,GENE.AMBITION,GENE.EMPATHY].map(g=>alive.length?alive.reduce((s,i)=>s+this.npcs.gene(i,g),0)/alive.length:0);this.geneHistory.push({day:dayOf(this.tick),values:genes});if(this.populationHistory.length>400)this.populationHistory.shift();if(this.geneHistory.length>400)this.geneHistory.shift()}
 applyScarcity(){for(const r of this.world.resources)if(r.kind===RESOURCE.FOOD&&this.rng.chance(.15))r.amount*=.75;for(const b of this.world.buildings)if(b.type===BUILDING.FARM&&this.rng.chance(.08))b.ripe*=.65}
 meta(){return{day:dayOf(this.tick),phase:dayPhase(this.tick),season:season(this.tick)}}
 serialize(){return{version:2,savedAt:Date.now(),seed:this.seed,rngState:this.rng.state,tick:this.tick,world:this.world.serialize(),npcs:this.npcs.serialize(),memory:this.memory.serialize(),dungeon:this.dungeon.serialize(),chronicle:this.chronicle,populationHistory:this.populationHistory,geneHistory:this.geneHistory,metrics:this.metrics}}
 static hydrate(d){const s=Object.create(Simulation.prototype);s.seed=d.seed;s.rng=new RNG(d.seed);s.rng.state=d.rngState;s.tick=d.tick;s.world=World.hydrate(d.world,s.rng);s.npcs=NPCStore.hydrate(d.npcs);s.memory=MemorySystem.hydrate(d.memory);s.dungeon=Dungeon.hydrate(d.dungeon,s.rng);s.chronicle=d.chronicle||[];s.populationHistory=d.populationHistory||[];s.geneHistory=d.geneHistory||[];s.observer=null;s.metrics=d.metrics||{travelStarted:0,travelCompleted:0,travelAbandoned:0,byAction:{}};s.metrics.byAction||={};return s}
}
