import {Simulation} from '../simulation.js';
import {ACTION,ACTION_LIST,DAY_TICKS,GENE,TECH_COUNT} from '../core/constants.js';
import {techniqueForAction} from '../systems/technology.js';
import {balanceSnapshot,resetBalance,setBalanceOverrides} from './balance.js';

export const DEFAULT_CALIBRATION_SEEDS=Object.freeze([42,7919,1337,2026,77,909,31415,8888,1201,6543,2718,1618,404,5150,8675309,12345,54321,777,99991,24680]);
const TEMPERAMENT=[GENE.AGGRESSION,GENE.CAUTION,GENE.AMBITION,GENE.EMPATHY,GENE.SOCIABILITY,GENE.CURIOSITY];
const ALWAYS_EXPECTED=new Set([ACTION.EAT,ACTION.DRINK,ACTION.SLEEP,ACTION.FLEE,ACTION.FORAGE,ACTION.WATER,ACTION.SOCIAL,ACTION.EXPLORE]);
const mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const median=xs=>{if(!xs.length)return null;const s=[...xs].sort((a,b)=>a-b),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
const variance=xs=>{if(!xs.length)return 0;const m=mean(xs);return mean(xs.map(x=>(x-m)*(x-m)))};
const bytes=s=>typeof Buffer!=='undefined'?Buffer.byteLength(s):new TextEncoder().encode(s).length;

function knows(n,i,t){return t<32?!!(n.techKnownLo[i]&(1<<t)):!!(n.techKnownHi[i]&(1<<(t-32)))}
function knownTechCount(n,i){let c=0;for(let t=0;t<TECH_COUNT;t++)if(knows(n,i,t))c++;return c}
function knownTechSet(n,ids){const s=new Set;for(const i of ids)for(let t=0;t<TECH_COUNT;t++)if(knows(n,i,t))s.add(t);return s}
function jaccardDistance(a,b){if(!a.size&&!b.size)return 0;let inter=0;for(const x of a)if(b.has(x))inter++;return 1-inter/(a.size+b.size-inter||1)}
function originGroupAt(sim,x,y){const seeds=sim.world.spawnSeeds||[];if(!seeds.length)return 0;let best=0,bd=Infinity;for(let k=0;k<seeds.length;k++){const d=(seeds[k].x-x)**2+(seeds[k].y-y)**2;if(d<bd){bd=d;best=k}}return best}
function originForNpc(sim,t,i){const n=sim.npcs,uid=n.uid[i];if(t.originByUid.has(uid))return t.originByUid.get(uid);const parent=(n.parents[i]||[]).find(x=>x>0&&t.originByUid.has(x));const group=parent? t.originByUid.get(parent):originGroupAt(sim,n.x[i],n.y[i]);t.originByUid.set(uid,group);return group}

export function inferGroups(sim,radius=12){const n=sim.npcs,alive=n.living(),seen=new Set,groups=[];for(const start of alive){if(seen.has(start))continue;const q=[start],ids=[];seen.add(start);while(q.length){const i=q.pop();ids.push(i);for(const j of alive){if(seen.has(j))continue;if(Math.hypot(n.x[i]-n.x[j],n.y[i]-n.y[j])<=radius){seen.add(j);q.push(j)}}}groups.push(ids)}groups.sort((a,b)=>b.length-a.length);return groups}
function groupMetrics(sim){const groups=inferGroups(sim),formed=groups.filter(g=>g.length>=2),sets=formed.map(g=>knownTechSet(sim.npcs,g)),pairs=[];for(let a=0;a<sets.length;a++)for(let b=a+1;b<sets.length;b++)pairs.push(jaccardDistance(sets[a],sets[b]));return{groups:formed.length,isolated:groups.filter(g=>g.length===1).length,largestGroup:groups[0]?.length||0,techDivergence:+mean(pairs).toFixed(4)}}
function geneticMetrics(sim){const n=sim.npcs,alive=n.living(),vars=TEMPERAMENT.map(g=>variance(alive.map(i=>n.gene(i,g))));return{meanTemperamentVariance:+mean(vars).toFixed(6),temperamentVariance:vars.map(x=>+x.toFixed(6))}}
function professionMetrics(sim){const n=sim.npcs,alive=n.living().filter(i=>n.age[i]>=16),counts=new Map;for(const i of alive)counts.set(n.prof[i],(counts.get(n.prof[i])||0)+1);const entries=[...counts.entries()].filter(([p])=>p!==0),total=entries.reduce((s,[,c])=>s+c,0);return{professionConcentration:total?Math.max(...entries.map(([,c])=>c))/total:0,professionCounts:Object.fromEntries(entries)}}
function taskRates(sim){const out={};for(const [a,started] of Object.entries(sim.tasks?.byAction||{})){const completed=sim.tasks?.completedByAction?.[a]||0,failed=sim.tasks?.failedByAction?.[a]||0;out[a]={started,completed,failed,completion:+(completed/Math.max(1,started)).toFixed(3)}}return out}
function zeroActionGuard(sim){const hist=sim.actionHistogram||{},n=sim.npcs,worldKnown=new Set;for(let i=0;i<n.count;i++)for(let t=0;t<TECH_COUNT;t++)if(knows(n,i,t))worldKnown.add(t);const zeros=[];for(const a of ACTION_LIST){if([ACTION.IDLE,ACTION.RETURN,ACTION.WARM,ACTION.CARE,ACTION.FIGHT,ACTION.DUNGEON,ACTION.TEACH].includes(a))continue;const tech=techniqueForAction(a),expected=ALWAYS_EXPECTED.has(a)||(tech!=null&&worldKnown.has(tech));if(expected&&(hist[a]||0)===0)zeros.push(a)}return zeros}
function founderAlive(sim,telemetry){if(!telemetry?.founders?.size)return null;let alive=0;for(const uid of telemetry.founders){const i=sim.npcs.indexByUid(uid);if(i>=0&&sim.npcs.alive[i])alive++}return alive}

export function snapshotMetrics(sim,telemetry=null){const n=sim.npcs,alive=n.living(),techCounts=alive.map(i=>knownTechCount(n,i)),g=groupMetrics(sim),gen=geneticMetrics(sim),prof=professionMetrics(sim),knownSet=new Set;for(const i of alive)for(let t=0;t<TECH_COUNT;t++)if(knows(n,i,t))knownSet.add(t);const founders=founderAlive(sim,telemetry),crossEncountered=telemetry?alive.filter(i=>telemetry.contact.has(n.uid[i])).length:0;return{day:sim.tick/DAY_TICKS,tick:sim.tick,population:alive.length,founderAlive:founders,founderMortality:founders==null?null:+(1-founders/Math.max(1,telemetry.founders.size)).toFixed(4),created:n.nextUid-1,groups:g.groups,isolated:g.isolated,largestGroup:g.largestGroup,techDivergence:g.techDivergence,techniquesDistinct:knownSet.size,techniquesMean:+mean(techCounts).toFixed(3),techniquesMax:techCounts.length?Math.max(...techCounts):0,crossGroupTransfers:sim.technology?.crossGroupTransfers||0,activeDisease:alive.filter(i=>n.activeDisease[i]).length,encountered:alive.filter(i=>n.humanSeen[i]).length,crossGroupEncountered:crossEncountered,firstCrossGroupContactDay:telemetry?.firstCrossGroupContactTick==null?null:telemetry.firstCrossGroupContactTick/DAY_TICKS,firstCrossGroupTransferDay:telemetry?.firstCrossGroupTransferTick==null?null:telemetry.firstCrossGroupTransferTick/DAY_TICKS,coverageMean:+mean(alive.map(i=>sim.memory.coverageRatio(i))).toFixed(4),highEvents:sim.chronicle.filter(e=>e.importance>=.8).length,professionConcentration:+prof.professionConcentration.toFixed(4),professionCounts:prof.professionCounts,meanTemperamentVariance:gen.meanTemperamentVariance,temperamentVariance:gen.temperamentVariance,bossDefeated:!sim.dungeon.boss.alive,bossDay:sim.dungeon.victoryTick?sim.dungeon.victoryTick/DAY_TICKS:null,travelCompletion:+((sim.travel?.completed||0)/Math.max(1,sim.travel?.started||0)).toFixed(3),taskRates:taskRates(sim),zeroExpectedActions:zeroActionGuard(sim),deaths:telemetry?.deaths||0,births:telemetry?.births||0,deathBeforeContact:telemetry?.deathBeforeContact||0,deathAfterContact:telemetry?.deathAfterContact||0,diseaseIncidence:telemetry?.diseaseIncidence||0,diseaseByTech:telemetry?.diseaseByTech||{}}}

function makeTelemetry(sim){const disease=new Map,seenUids=new Set,contact=new Map,founders=new Set,originByUid=new Map;for(let i=0;i<sim.npcs.count;i++)if(sim.npcs.uid[i]){const uid=sim.npcs.uid[i];seenUids.add(uid);founders.add(uid);originByUid.set(uid,originGroupAt(sim,sim.npcs.x[i],sim.npcs.y[i]));disease.set(uid,sim.npcs.activeDisease[i]||0)}return{disease,seenUids,contact,founders,originByUid,chronicleCursor:sim.chronicle.length,techCursor:sim.technology?.discoveries?.length||0,firstCrossGroupContactTick:null,firstCrossGroupTransferTick:null,births:0,deaths:0,deathBeforeContact:0,deathAfterContact:0,diseaseIncidence:0,diseaseByTech:{}}}
function updateTelemetry(sim,t){const n=sim.npcs;for(let i=0;i<n.count;i++){const uid=n.uid[i];if(!uid)continue;if(!t.seenUids.has(uid)){t.seenUids.add(uid);if(n.birthTick[i]>0)t.births++}const gi=originForNpc(sim,t,i),p=sim.lastPerception?.[i];for(const h of p?.humans||[]){const j=h.id;if(j<0||!n.uid[j])continue;const gj=originForNpc(sim,t,j);if(gi===gj)continue;const other=n.uid[j];if(!t.contact.has(uid))t.contact.set(uid,sim.tick);if(!t.contact.has(other))t.contact.set(other,sim.tick);if(t.firstCrossGroupContactTick==null||sim.tick<t.firstCrossGroupContactTick)t.firstCrossGroupContactTick=sim.tick;break}const prev=t.disease.get(uid)||0,cur=n.activeDisease[i]||0;if(cur&&!prev){t.diseaseIncidence++;const k=String(knownTechCount(n,i));t.diseaseByTech[k]=(t.diseaseByTech[k]||0)+1}t.disease.set(uid,cur)}const discoveries=sim.technology?.discoveries||[];for(;t.techCursor<discoveries.length;t.techCursor++){const d=discoveries[t.techCursor];if(!(d.sourceUid>0))continue;const learnerGroup=t.originByUid.get(d.npc),sourceGroup=t.originByUid.get(d.sourceUid);if(learnerGroup==null||sourceGroup==null||learnerGroup===sourceGroup)continue;if(t.firstCrossGroupTransferTick==null||d.tick<t.firstCrossGroupTransferTick)t.firstCrossGroupTransferTick=d.tick}for(;t.chronicleCursor<sim.chronicle.length;t.chronicleCursor++){const e=sim.chronicle[t.chronicleCursor];if(e.type!=='morte')continue;t.deaths++;const i=e.npc,uid=i>=0?n.uid[i]:0;if(uid&&t.contact.has(uid))t.deathAfterContact++;else t.deathBeforeContact++}}

export function runHeadless({seed=42,days=30,ticks=null,sampleEveryDays=10,simulationFactory=null,balance=null}={}){resetBalance();if(balance)setBalanceOverrides(balance);const appliedBalance=balanceSnapshot();try{const sim=simulationFactory?simulationFactory(seed):new Simulation(seed),total=ticks??Math.round(days*DAY_TICKS),sampleEvery=Math.max(1,Math.round(sampleEveryDays*DAY_TICKS)),telemetry=makeTelemetry(sim),series=[],started=Date.now();for(let k=0;k<total;k++){sim.step();updateTelemetry(sim,telemetry);if(sim.tick%sampleEvery===0||k===total-1)series.push(snapshotMetrics(sim,telemetry))}const final=snapshotMetrics(sim,telemetry),save=sim.serialize(),saveBytes=bytes(JSON.stringify(save)),saveSections={};for(const [k,v] of Object.entries(save))saveSections[k]=bytes(JSON.stringify(v));return{seed,days:sim.tick/DAY_TICKS,balance:appliedBalance,runtimeMs:Date.now()-started,series,final:{...final,saveBytes},saveSections,actionHistogram:{...sim.actionHistogram},taskRates:taskRates(sim),deathsByCause:deathCauses(sim),discoveries:sim.technology?.discoveries?.map(d=>({...d,day:d.tick/DAY_TICKS}))||[]}}finally{resetBalance()}}
function deathCauses(sim){const n=sim.npcs,out={};for(let i=0;i<n.count;i++)if(!n.alive[i]&&n.deathCause[i])out[n.deathCause[i]]=(out[n.deathCause[i]]||0)+1;for(const a of n.archive||[])if(a.deathCause)out[a.deathCause]=(out[a.deathCause]||0)+1;return out}

export function summarizeBatch(runs){const finals=runs.map(r=>r.final),firstFire=runs.map(r=>r.discoveries.find(d=>d.tech===3)?.day).filter(Number.isFinite),fireSeeds=runs.filter(r=>r.discoveries.some(d=>d.tech===3)).length,bossDays=finals.map(x=>x.bossDay).filter(Number.isFinite),contactDays=finals.map(x=>x.firstCrossGroupContactDay).filter(Number.isFinite),transferDays=finals.map(x=>x.firstCrossGroupTransferDay).filter(Number.isFinite),extinct=finals.filter(x=>x.population===0).length,founderMortality=finals.map(x=>x.founderMortality).filter(Number.isFinite),saveSectionBytesMax={};for(const r of runs)for(const [k,v] of Object.entries(r.saveSections||{}))saveSectionBytesMax[k]=Math.max(saveSectionBytesMax[k]||0,v);return{seeds:runs.length,days:Math.max(0,...runs.map(r=>r.days)),population:{min:Math.min(...finals.map(x=>x.population)),median:median(finals.map(x=>x.population)),max:Math.max(...finals.map(x=>x.population)),mean:+mean(finals.map(x=>x.population)).toFixed(2)},founderMortality:{min:founderMortality.length?Math.min(...founderMortality):null,median:median(founderMortality),max:founderMortality.length?Math.max(...founderMortality):null},extinct,extinctionRate:+(extinct/Math.max(1,runs.length)).toFixed(3),groupsMedian:median(finals.map(x=>x.groups)),techDivergenceMean:+mean(finals.map(x=>x.techDivergence)).toFixed(4),fireDiscoveryRate:+(fireSeeds/Math.max(1,runs.length)).toFixed(3),firstFireMedian:firstFire.length?median(firstFire):null,crossGroupContactRate:+(contactDays.length/Math.max(1,runs.length)).toFixed(3),firstCrossGroupContactMedian:contactDays.length?median(contactDays):null,techTransferRate:+(transferDays.length/Math.max(1,runs.length)).toFixed(3),firstCrossGroupTransferMedian:transferDays.length?median(transferDays):null,crossGroupTransfersMean:+mean(finals.map(x=>x.crossGroupTransfers)).toFixed(2),bossDefeatRate:+(bossDays.length/Math.max(1,runs.length)).toFixed(3),earliestBoss:bossDays.length?Math.min(...bossDays):null,highEventsMean:+mean(finals.map(x=>x.highEvents)).toFixed(2),saveBytesMax:Math.max(...finals.map(x=>x.saveBytes||0)),saveSectionBytesMax,tickMsMean:+mean(runs.map(r=>r.runtimeMs/Math.max(1,r.final.tick))).toFixed(4),seedDistance:+meanPairwiseSeedDistance(finals).toFixed(4),zeroActionSeeds:runs.filter(r=>r.final.zeroExpectedActions.length).map(r=>({seed:r.seed,actions:r.final.zeroExpectedActions}))}}
function meanPairwiseSeedDistance(finals){if(finals.length<2)return 0;const keys=['population','groups','techniquesDistinct','techDivergence','highEvents','professionConcentration','activeDisease'],ranges={};for(const k of keys){const xs=finals.map(x=>+x[k]||0),lo=Math.min(...xs),hi=Math.max(...xs);ranges[k]=Math.max(1e-6,hi-lo)}const ds=[];for(let a=0;a<finals.length;a++)for(let b=a+1;b<finals.length;b++){let sum=0;for(const k of keys){const d=((+finals[a][k]||0)-(+finals[b][k]||0))/ranges[k];sum+=d*d}ds.push(Math.sqrt(sum/keys.length))}return mean(ds)}
export function runBatch({seeds=DEFAULT_CALIBRATION_SEEDS.slice(0,10),days=30,sampleEveryDays=10,balance=null}={}){const runs=seeds.map(seed=>runHeadless({seed,days,sampleEveryDays,balance}));return{config:{seeds,days,sampleEveryDays,balance:balance||{}},summary:summarizeBatch(runs),runs}}
export function compareBatches(a,b){const A=a.summary||summarizeBatch(a.runs||[]),B=b.summary||summarizeBatch(b.runs||[]),delta={};for(const k of['extinctionRate','groupsMedian','techDivergenceMean','fireDiscoveryRate','firstFireMedian','crossGroupContactRate','firstCrossGroupContactMedian','techTransferRate','firstCrossGroupTransferMedian','bossDefeatRate','earliestBoss','highEventsMean','saveBytesMax','tickMsMean','seedDistance'])if(typeof A[k]==='number'&&typeof B[k]==='number')delta[k]=+(B[k]-A[k]).toFixed(4);return{before:A,after:B,delta}}
